### ISSUE TITLE
iOS crash on start if "Player Settings/Splash Image" is disabled or has no image when enabled

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/cardboard#170] opened 2020-12-04 16:08 UTC
Our UI is 2D non-VR portrait and we activate VR mode manually with a separate scene for VR.

On iOS it crashes immediately on start if "Made with Unity" splash screen is disabled.

Additionally, the app restarts 2-3 times without crashing even with splash screen enabled. Then it runs normally. I can see the restarts because splash screen is displayed again and again until the app runs normally.

It rarely sends a crash report to Unity services. It doesn't send any reports when Development Build is enabled in cloud builder options. So the crash report is filled with undefined symbols. I tried uploading symbols manually but had no help with missing symbols. Here is the stack trace I have:
[stack-trace.txt](https://github.com/googlevr/cardboard/files/5643846/stack-trace.txt)

Unity 2019.4.15f1, Cardboard SDK v1.3.0, iOS 14.2

Here is the repro project:
[splash-screen-disabled-ios-crashes-on-start.zip](https://github.com/googlevr/cardboard/files/5643832/splash-screen-disabled-ios-crashes-on-start.zip)
[splash-screen-enabled-ios-does-not-crash.zip](https://github.com/googlevr/cardboard/files/5643833/splash-screen-enabled-ios-does-not-crash.zip)

For a limited time you can use these branches as well:
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/splash-screen-disabled-ios-crashes-on-start
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/splash-screen-enabled-ios-does-not-crash

**Comment by guneyozsan** [comment] 2020-12-13 22:16
It happens on Cardboard SDK v1.4.0 as well.
After 1.4.0 using OpenGLES2 or OpenGLES3 has no effect, issue persists.

- These combinations of player settings crash directly at start on iOS:
    - Show splash screen: False
    - Show splash screen: True, Show Unity logo: False, Logos list: Empty
- These combinations of player settings does NOT crash on iOS:
    - Show splash screen: True, Show Unity logo: True
    - Show splash screen: True, Show Unity logo: False, Logos list: A custom logo image

Even with splash screen, sometimes app restarts (not crashes and disappears) with different stack traces on Cloud Diagnostics:
All "Native Crash - Unknown Function":
 - (/System/Library/Extensions/AppleMetalGLRenderer.bundle/AppleMetalGLRenderer)
[stack-trace-1.txt](https://github.com/googlevr/cardboard/files/5685279/stack-trace-1.txt)
- (/usr/lib/system/libsystem_kernel.dylib)
[stack-trace-2.txt](https://github.com/googlevr/cardboard/files/5685284/stack-trace-2.txt)
- (/System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib)
[stack-trace-3.txt](https://github.com/googlevr/cardboard/files/5685287/stack-trace-3.txt)

**Comment by jballoffet** [comment] 2020-12-18 20:13
Thank you for reporting this issue. I confirm that I'm able to reproduce the crash with the provided project, but I cannot do it with the VrMode scene in HelloCardboard sample app. By taking a look at the logs, I see this:
```
2020-12-18 16:57:52.177548-0300 GoogleCardboardTest[6628:3186360] *** Assertion failure in -[UnityDefaultViewController supportedInterfaceOrientations], /Users/jballoffet/Downloads/UnityGoogleCardboardTestTemp/provided-project/Classes/UI/UnityViewControllerBase+iOS.mm:124
2020-12-18 16:57:52.217393-0300 GoogleCardboardTest[6628:3186360] Uncaught exception: NSInternalInconsistencyException: UnityDefaultViewController should be used only if unity is set to autorotate
```

Taking this into account, @guneyozsan it would be great if you could change the repro project to switch between VR and non-VR mode without rotating the screen and check if the issue persists. On the other hand, it would also be great if you could try the VrMode scene from HelloCardboard sample app and check if the splash screen issue shows up there for you. 

This issue has been added to our backlog and will be prioritized along with other issues.

**Comment by jballoffet** [comment] 2022-06-09 15:37
Closing this issue since we haven't been able to reproduce the crash using the VrMode sample scene nor with autorotate enabled. In case you are still having this issue, please reopen it and it would be really helpful if you could provide us with a modified version of the VrMode scene where the issue can be depicted. Thanks!

**Closed by jballoffet** 2022-06-09 15:37 UTC
Labels: bug
