### ISSUE TITLE
[Unity] Mask component cannot be used

### ISSUE THREAD

**Issue by 3493000** [googlevr/cardboard#289] opened 2021-08-02 11:06 UTC
Everything is normal in the editor mode,
But when packaged on an android phone, the Mask component fails. Is the stencil buffer useless? How to fix it?

**Comment by 3493000** [comment] 2021-08-02 11:08
![123](https://user-images.githubusercontent.com/43593494/127852273-dd127cb6-0ac5-4d25-a7b4-4301516514d1.jpg)
![lADPDiCpvsq8AEXND8DNC9A_3024_4032 jpg_720x720q90g](https://user-images.githubusercontent.com/43593494/127852349-cc742f6f-800d-4cb5-b836-ce76bfdf3f21.jpg)

**Comment by 3493000** [comment] 2021-08-02 11:11
![Dingtalk_20210802191104](https://user-images.githubusercontent.com/43593494/127852741-2bcb5533-090a-4ec7-ab23-a88b1c818f22.jpg)
![Dingtalk_20210802191015](https://user-images.githubusercontent.com/43593494/127852758-85b5d89c-4416-4066-8379-ae173ebc1f54.jpg)

**Comment by 3493000** [comment] 2021-08-02 11:13
![Dingtalk_20210802191235](https://user-images.githubusercontent.com/43593494/127852963-4be5b1e4-27bf-4adf-b00c-225ac269a9d3.jpg)

**Comment by jballoffet** [comment] 2021-08-09 13:07
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of #162. Please feel free to leave comments on that issue if needed. Thanks!

**Closed by jballoffet** 2021-08-09 13:07 UTC
Labels: duplicate
