### ISSUE TITLE
Black Screen in VR mode on redmi note 8 (2021)

### ISSUE THREAD

**Issue by GMAGD** [googlevr/cardboard#389] opened 2022-12-21 15:56 UTC
Hello,
I've tried to use VR on mobile so i downloaded cardboard xr plugin and followed the steps  here : 
https://developers.google.com/cardboard/develop/unity/quickstart
i followed everything but everytime i do build a get a black screen no matter what render api i'm using i've tried vulkain, GL ES 3.0/2.0

Unity Version : 2020.3.16f1
Google Cardboard XR Plugin for Unity : Version 1.19.0 

![image](https://user-images.githubusercontent.com/21009210/208947440-94539dd3-67ac-400b-aea7-c78dab3fe9a4.png)
![image](https://user-images.githubusercontent.com/21009210/208947486-b6ebaf26-bd63-47f5-a9cc-de981283ae32.png)
![image](https://user-images.githubusercontent.com/21009210/208947556-7cfa9e12-470b-4cf4-8cae-33e1d2691b18.png)

**Comment by arilow** [comment] 2022-12-21 17:08
Thanks @GMAGD  for reaching out to us! In order to allow us to reproduce this issue, could you please provide:
- The required steps to expose the issue. You shared images with some configuration, but please write each step you are doing. So we can check any differences there might be.
- Device fingerprint. You can get it using adb with the following command:
```
adb shell getprop ro.build.fingerprint
```
- A simple Unity project where this issue is depicted would also be very helpful.
- Do you have another device to test? If so, please test it. In this way we can check if the issue is related to configuration or  to the Cardboard XR Plugin.

Thanks!

**Comment by GMAGD** [comment] 2022-12-21 17:32
Hello @arilow 

my device fingerprint : Redmi/biloba_global/biloba:11/RP1A.200720.011/V12.5.8.0.RCUMIXM:user/release-keys
i have android logcat stack trace : 
![image](https://user-images.githubusercontent.com/21009210/208968030-7d238955-42ee-4b48-803e-b68074dd67f4.png)

**Comment by arilow** [comment] 2022-12-22 17:51
Thanks @GMAGD for the quick response!In order to allow us to reproduce this issue, could you please provide:
- The required steps to expose the issue. You shared images with some configuration, but please write each step you are doing. So we can check any differences there might be.
- A simple Unity project where this issue is depicted would also be very helpful.
- Do you have another device to test? If so, please test it. In this way we can check if the issue is related to configuration or  to the Cardboard XR Plugin.

Thanks!

**Comment by arilow** [comment] 2023-04-18 18:18
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:18 UTC

**Comment by GMAGD** [comment] 2023-04-26 14:53
To solve the issue just upgrad to the latest android api for me api 33 solved the problem
