### ISSUE TITLE
Metal graphics API renders image flipped upside-down.

### ISSUE THREAD

**Issue by Acciai0** [googlevr/cardboard#307] opened 2021-10-25 16:21 UTC
### SPECIFIC ISSUE ENCOUNTERED
Using Metal causes the image to be rendered upside-down, as in the floor is rendered above and moving the head to the right causes the view to rotate to the left.

### SMARTPHONE (please complete the following information):
- Device: iPad 6th gen, iOS 15.0.2

### STEPS TO REPRODUCE THE ISSUE
Build any scene using the given versions described here of all the tools.

### EXPECTED BEHAVIOR
Even using Metal, the scene is rendered in the right orientation.

### VERSIONS USED
Google Cardboard version: Cardboard SDK/Cardboard XR Plugin 1.9.0
Unity version: 2020.3.20f1

Select in which graphics API you can reproduce the bug.
- Metal

### ADDITIONAL CONTEXT
I managed to set the graphics API to OpenGL ES3 manually on ProjectSettings.asset and it rendered correctly, but since then Unity keeps resetting the value to Metal automatically each time I build. Since I'm using Unity 2020.3, the editor doesn't allow to explicitly set any graphics API aside from Metal, making this issue literally unsolvable.

**Comment by jballoffet** [comment] 2021-11-11 15:32
Thanks @Acciai0 for reaching out to us and for sharing what solved the issue on your end. Given that I cannot reproduce the issue and it is not blocking you anymore, I'm closing this ticket. In case this issue is reported again, I'll point the reported to this ticket. Thanks!

**Closed** 2021-11-11 15:33 UTC
Labels: bug
