### ISSUE TITLE
Black screen with Linear Color Space + URP

### ISSUE THREAD

**Issue by CenekStrichel** [googlevr/cardboard#199] opened 2021-02-02 17:02 UTC
I wanted to migrate my cardboard project with a new XR-Plugin. But screen is a black (Unity 2020.2.2f1 - phone: Pixel XL). I found that problem is Linear Color Space. It works good with Gamma Color Space. Is it bug or limitation? Is there some workaround? I really need linear color space. I also use it with URP.

**Comment by sammorris-fss** [comment] 2021-02-11 13:52
I'm having the exact same issue. Unity 2020.2.3f1, Linear Colour Space, on URP. If I allow the XR framework to initialise at startup, I don't even see the Unity logo splash. If I delay the initialization, I actually get constant flickering (it'll render one frame, then black for another, then renders the frame again - repeat at 60hz).

I can look at switching colour space if required, but we've been setting up the lighting for the scenes for a little while now and re-doing that work is not ideal.

**Comment by jballoffet** [comment] 2021-03-10 21:52
Thanks for reporting this issue. I confirm we've been able to reproduce the reported bug. These are the findings:

- URP disabled:
  - Gamma color space: App works properly.
  - Linear color space: App works properly.
- URP enabled:
  - Gamma color space: Unity's splash screen is black, but the sample app works as expected after that.
  - Linear color space: The screen is black.

A ticket for doing some research into this issue has been added to our backlog and will be prioritized along with other issues. Patches are also welcome.

**Comment by dipaw** [comment] 2021-03-27 03:41
Hello, is there any news on URP + Linear?

**Comment by jballoffet** [comment] 2021-04-01 15:44
At the moment, our highest priority is getting Metal and therefore a new release of Cardboard out. We'll update this issue once we have some updates about it. In case you'd like to propose the required changes, please feel free to do so. Patches are welcome.

**Comment by Layfully** [comment] 2021-05-23 20:57
Thank you for looking into this. Any news?

**Comment by jballoffet** [comment] 2021-06-18 15:36
This has not been prioritized in the short run (here you can find the [Roadmap](https://github.com/googlevr/cardboard/projects/1)). Nevertheless, in case you would like to send changes in order to fix it, please feel free to do so. Patches are welcome.

**Comment by Varollo** [comment] 2021-07-13 18:42
Hi, in the issue #283 the [provided project](https://github.com/Varollo/cardboard-urp-rendererfeature-issue) uses Gamma Color Space and it's still broken, please look into it

**Comment by jballoffet** [comment] 2021-07-13 19:21
@Varollo, will do, thanks for pointing that out!

**Comment by Varollo** [comment] 2021-07-19 17:23
Ok so I tested the problem I wrote about on issue #283 with the urp renderer feature on unity 2019.4.28 and it worked fine, the problem seens to be related to either unity 2020 or urp 10.6

**Comment by diegodias** [comment] 2021-07-26 15:02
> @Varollo, will do, thanks for pointing that out!

Any news on this one? (or any leads where we can look)
Trying to use with Unity 2020.3 but can't do it because we are having the same problem (not working with the urp renderer feature )

**Comment by Layfully** [comment] 2021-07-29 06:50
> 
> 
> This has not been prioritized in the short run (here you can find the [Roadmap](https://github.com/googlevr/cardboard/projects/1)). Nevertheless, in case you would like to send changes in order to fix it, please feel free to do so. Patches are welcome.

Hopefully this will be fixed before unity decides to deprecate built-in renderer pipeline. Because using it with URP requires having unity license  because you are not showing unity screen which probably breaks rules for personal license

**Comment by Ghostbird** [comment] 2021-11-08 20:49
This bug means that Unity development for cardboard is basically dead until it's fixed. I'm not going to create a game for a deprecated rendering pipeline, and unless you're developing for very specific hardware, using gamma colour space makes everything in the game render bright white except the sky box.

**Comment by Layfully** [comment] 2022-01-08 21:37
Update: In unity 2021.2 The issue changed. Now there is a rectangle rendered with view of the eyes, but its not displayed correctly. 
![obraz](https://user-images.githubusercontent.com/15947565/148660830-18378c97-7cb1-4380-9ac8-a0f75cfcb559.png)

**Comment by Layfully** [comment] 2022-01-16 14:28
I tried to find the exact version of unity, which introduced this issue. Turns out it doesn't matter which version you use, but if you use default packages the latest version which works is 2020.2.0b7 with URP 10.0.26-preview (all previous betas and alphas work too). If you use the exact same unity version with newer URP version >= 10.1.0 it breaks, which leads me to the conclusion that the issue was introduced somewhere in URP 10.1.0.

**Comment by Layfully** [comment] 2022-01-16 18:23
In addition to the previous research I've checked if the issue is solved in the newest version of unity and it seems different. ![obraz](https://user-images.githubusercontent.com/15947565/149672681-57f24063-3c46-4d90-a3e8-d2440ea75271.png). The same image as previously appears on the screen but there is also correct view being rendered in red color only.

**Comment by Layfully** [comment] 2022-01-16 18:24
In addition the content in this rectangle is not updating. Red view is being updated and allows to play the game

**Comment by arilow** [comment] 2022-02-23 15:00
Sorry for the long delay here. We have some updates with respect to this ticket. We have tried with several Unity versions and, as stated in comments above, the behavior is different depending on the version being used. We have gathered all the results is the following table:


| Unity supported version | URP version | Works with URP + Linear color space? |
|-------------------------|-------------|--------------------------------------|
| 2019.4.35               | 7.7.1       | Yes                                  |
| 2020.1.17     | 8.3.1       | Yes                                  |
| 2020.2.0      | 10.2.2      | No: black screen                     |
| 2020.3.28               | 10.7.0      | No: black screen                     |
| 2021.2.11               | 12.1.3      | No: black screen                     |
| 2022.1.0                | 13.1.5      | No: everything is red                |


In consequence, we have reported this behavior to Unity. We will come back here as soon as we receive any news.


Thanks!

**Comment by Ghostbird** [comment] 2022-02-23 15:03
Thanks for the progress. I hope it turns out a relatively easily resolved issue.

**Comment by AkaiShiki** [comment] 2022-02-23 15:41
Thanks for the update. 
Hope it gets fixed soon !

**Comment by Layfully** [comment] 2022-03-07 11:16
https://issuetracker.unity3d.com/issues/android-black-screen-is-displayed-when-using-xr-plug-in-plus-urp-with-linear-color-space?fbclid=IwAR0nl0mtonYu9x013KhVmGFczeZE744r9H9qw116X9DKc8Ilg4VuPV5sy14 here is the link to the issue. We can vote on it and maybe it will help in increasing priority.

**Comment by mtschoen** [comment] 2022-03-14 07:45
Hey there! I was digging into this issue some and I think I have a fix! At least in the case of an entirely blank screen, it looks like the newer versions of URP include a special case to early-out on Android when drawing the Mirror View. I'm not _exactly_ sure how this translates to an empty back buffer, but in my case just getting rid of this if/return fixed the issue! Hope this helps!

https://github.com/Unity-Technologies/Graphics/blob/018098f5a605f316f4828098fb616ecaf7052083/com.unity.render-pipelines.core/Runtime/XR/XRMirrorView.cs#L20

Note: this code lives in slightly different places depending on the version of URP. Also, for those unfamiliar with modifying package code:
- Navigate to Library\PackageCache in your project, after importing whatever version of URP you need
- Move or copy the com.unity.render-pipelines.universal@x.y.z folder from there into Packages, and drop the @x.y.z from the folder name
- Modify Runtime/XR/MirrorView.cs or Runtime/XR/System.cs (depending on the URP version) to get rid of the early-out for Android
- Open the project (or focus Unity), let things compile, and hit Build

You will need to do this on every local machine, or create a .tgz or .zip of the package to make it easier for folks to set up the workaround.

_Do not_ attempt to just modify the file in-place in Library/PackageCache as Unity will  overwrite the contents of that folder on build and/or import.

**Comment by arilow** [comment] 2022-03-29 18:15
A fix for this issue has been submitted and it will be included in v1.14.0. Thanks for reaching out!

**Comment by xinyunh0929** [comment] 2022-04-04 22:51
This was fixed in v1.14.0

**Closed by xinyunh0929** 2022-04-04 22:51 UTC
Labels: bug, fixed in upcoming release

**Comment by playg8** [comment] 2024-08-26 03:20
Same issue in my project. I fixed it by config ProjectSettings>Graphics>Instancing Variants:KeepAll; BatchRendererGroup Variants: Keep All.
