### ISSUE TITLE
From XR mode into 2d mode

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#136] opened 2020-10-07 06:21 UTC
Hi, how can I change in runtime using XR form VR to 2d mode  and back
Unity 2020.1

**Comment by JoaoBorks** [comment] 2020-10-07 13:37
This is a very common question. [Here](https://docs.unity3d.com/Packages/com.unity.xr.management@3.0/manual/EndUser.html) is the official documentation for Unity's XR Management.

Basically what you have to do to disable the VR view is this:
```csharp
var manager = XRGeneralSettings.Instance.Manager;
manager.StopSubsystems();
manager.DeinitializeLoader();
```

Once you have to turn it on again, just:
```csharp
var manager = XRGeneralSettings.Instance.Manager;
if (!manager.isInitializationComplete)
  yield return manager.InitializeLoader();
manager.StartSubsystems();
```

---
@jballoffet @chaosemer maybe we should create this functionality on the sample scene since people will want to have this feature. I'll see if I can make a PR later this week.

**Comment by andyz** [comment] 2020-10-09 14:21
Toggling in & out of Cardboard VR has some big issues on Android currently
1. You must be sure you are in landscape-left, if the screen is still rotating it might think your screen is tall not wide and draw the VR mode all wrong (current hack for me is wait half a second for screen to rotate to landscape left if not currently there!)
2. I can not get out of VR mode - I close it down as above, as Unity shows, but there is a static image of the cardboard view left on the screen. Not sure where this issue lies yet for me & did not try minimal test...

**Comment by rajandeepsingh13** [comment] 2020-10-09 14:39
I also don't see the settings and the 'x' icons when I enter the VR mode after the app has already been started. @andyz any luck with this?

**Comment by andyz** [comment] 2020-10-09 14:48
Also I get an app crash on entering VR for second time...

@rajandeepsingh13 Are you in landscape left and rendering only to safe area?

**Comment by rajandeepsingh13** [comment] 2020-10-09 15:03
> 
> 
> Also I get an app crash on entering VR for second time...
> 
> @rajandeepsingh13 Are you in landscape left and rendering only to safe area?

Yes, I am. If I tap on where the buttons should be, it works. But I just can't see the buttons. Also, the image that is being rendered isn't stereo. It's the same for both eyes.

![image](https://user-images.githubusercontent.com/32610322/95599264-7b862000-0a6e-11eb-840c-b75546d06a04.png)

**Comment by jballoffet** [comment] 2020-10-16 15:23
As @JoaoBorks suggested, Unity's XR Management must be used to control the XR plugin lifecycle. We’ll add a new section to the [Unity quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) soon to make this clearer and we’ll also add a simple sample that depicts how this should be performed within the XR plugin package. I’m closing this issue as a duplicate of #53.

**Closed** 2020-10-16 15:23 UTC
Labels: duplicate, question
