### ISSUE TITLE
Question: Problem with display on Android?

### ISSUE THREAD

**Issue by cloud-cove** [googlevr/cardboard#434] opened 2023-09-24 17:32 UTC
Hello! I am trying to run the Hello Cardboard scene on my Android phone. It runs, but the display seems to be rotated? Screenshot is attached. It seems like the left eye is being displayed 90 degrees to the right, and the rest of the screen is being filled with the corner of the left eye display.
![Screenshot_20230924-131138](https://github.com/googlevr/cardboard/assets/91750570/5f4aaf12-ae2d-42d7-8aa4-ae43132efebc)
I am holding my phone in landscape left position, and in the Unity project I have set landscape left as the default orientation. I have also tried setting the default orientation to Auto and then unchecking both portrait modes, and unchecking everything but landscape left. I have also tried turning autorotate on and off on my phone, and starting another app that forces my phone display to landscape before running the Unity project. None of these changes seem to have made a difference in the display.
I am using Unity 2021.3.9f1 and the latest version of the cardboard SDK, and my phone is a Moto G Stylus 2021, using Android 11. 

Is there a way to make the project display correctly?

**Comment by arilow** [comment] 2023-09-25 14:24
Thanks @cloud-cove for reaching out to us!


This looks like a duplicate of #391. If that solution doesn't work for you, could you please provide:


- The required steps to expose the issue. Even if you are following the Quickstart, please write each step you are doing. So we can check any slight difference that might be.
- Device fingerprint. You can get it using adb with the following command:
```
adb shell getprop ro.build.fingerprint
```
- A simple Unity project where this issue is depicted would also be very helpful.
- Do you have another device to test? If so, please test it. In this way we can check if the issue is device specific.


Thanks!

**Comment by cloud-cove** [comment] 2023-09-25 16:24
Thank you so much @arilow ! I hadn't seen issue #391 and you were right, I had forgotten to uncheck the Apply Display Rotation box. It works now! Thank you again for your help.

**Comment by arilow** [comment] 2023-09-28 15:47
Closing as this is fixed. 

Thanks!

**Closed by arilow** 2023-09-28 15:47 UTC
