### ISSUE TITLE
crash when calling `CardboardQrCode_scanQrCodeAndSaveDeviceParams`

### ISSUE THREAD

**Issue by arumons** [googlevr/cardboard#112] opened 2020-09-15 18:19 UTC
Environment
Unity ver: 2019.3.15f1
cardboard ver: 1.2.0
Google Analytics for Firebase ver: 6.15.2(installed from unity package manager)

test device: galaxy s9

When firebase is included, if the contents of gradle are as follows, the build failed.

```
  implementation 'com.android.support:appcompat-v7:28.0.0'
  implementation 'com.android.support:support-v4:28.0.0'
  implementation 'com.google.android.gms:play-services-vision:15.0.2'
  implementation 'com.google.protobuf:protobuf-lite:3.0.0'
```

Therefore, when I rewrote gradle with reference to issune #98 , the build passed.
```
implementation 'com.google.android.material:material:1.1.0'
implementation 'com.google.android.gms:play-services-vision:15.0.2'
implementation 'com.google.protobuf:protobuf-lite:3.0.0'
```

But when I call CardboardQrCode_scanQrCodeAndSaveDeviceParams(for reading qr code) , the app seems to crash.

I would like to know if there is a way to read the QR code while using firebase.

**Comment by agalbachicar-gg** [comment] 2020-11-17 21:02
We tried to reproduce the provided steps but could not make it build without any crash. Would you please attach a repro project so we can take another look?

**Comment by arumons** [comment] 2020-11-18 12:16
@agalbachicar-gg 

I uploaded the reproducible project to the URL below.
https://drive.google.com/file/d/1tDYLDlr4ZXUARcjYELXHZi7WPLq5Mlcd/view

**Comment by jballoffet** [comment] 2021-01-29 22:17
@arumons, sorry for the long delay here. I confirm I’m able to repro the issue locally with the provided project. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it. Thanks!

**Comment by jballoffet** [comment] 2021-06-09 14:59
In the last release (v1.6.0), the gradle dependencies have changed since Cardboard SDK has been migrated to use AndroidX libraries. @arumons, I'd really appreciate if you could check whether the issue still takes place when release v1.6.0 is used. Thanks!

**Comment by jballoffet** [comment] 2022-06-09 13:02
Closing this ticket since the gradle dependencies have changed throughout the releases. Please retry using release v1.15.0 and reopen this issue if the error persists. Thanks!

**Closed by jballoffet** 2022-06-09 13:02 UTC
Labels: bug
