### ISSUE TITLE
Failed to create apk file (Gradle build failed)

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#401] opened 2023-04-13 11:47 UTC
### SPECIFIC ISSUE ENCOUNTERED
While building an apk file getting  errors. 

- OS
  -  Android

### STEPS TO REPRODUCE THE ISSUE
1. Create empty unity project
2. Via git add cardboard-xr-plugin
3. Set the project according to the doc (https://developers.google.com/cardboard/develop/unity/quickstart?hl=ru)

### VERSIONS USED
cardboard-xr-plugin version 1.20.0 
Unity version 2021.3.22f1 (LTS)

- Select in which graphics API you can reproduce the bug.
   - OpenGL ES3

<img width="783" alt="Screenshot 2023-04-13 at 14 45 17" src="https://user-images.githubusercontent.com/55288472/231749185-bba45e72-c605-4c71-8503-9cc0e5e5ea01.png">
<img width="784" alt="Screenshot 2023-04-13 at 14 45 07" src="https://user-images.githubusercontent.com/55288472/231749209-dd53296f-d940-4839-ad33-6da6a0c96872.png">
<img width="797" alt="Screenshot 2023-04-13 at 14 45 01" src="https://user-images.githubusercontent.com/55288472/231749233-d3d56678-3de0-4984-aca8-2b9b800dec8b.png">

**Comment by arilow** [comment] 2023-04-13 18:27
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of #386. Please feel free to leave comments on that issue if needed.

Thanks!

**Closed by arilow** 2023-04-13 18:27 UTC
Labels: bug
