### ISSUE TITLE
Rotational response time slower than Youtube VR

### ISSUE THREAD

**Issue by tokunodont** [googlevr/cardboard#163] opened 2020-11-19 08:28 UTC
Hi! 

Compared to Youtube's VR, the speed at which the video comes with the head rotation feels slow.
Is there any way to make it faster?

I would appreciate it if you could give me some tips on how to improve.

Please help. Thank you!

**Comment by jballoffet** [comment] 2020-11-24 12:36
Could you please provide more information about the issue, such as:
- Is this taking place on Android or iOS?
- Is Unity being used?
- The phone and OS version being used.

In the meanwhile, the sensor fusion is performed by a Kalman filter in the SensorFusionEkf class. You can find details about its implementation [here](https://github.com/googlevr/cardboard/blob/master/sdk/sensors/sensor_fusion_ekf.cc). You can try to apply changes there and check if them improve your experience.

**Comment by tokunodont** [comment] 2020-11-26 07:31
Thank you!

Developed on unity 2019.4.14f, iPhoneXR iOS14

I would like to see that script.

I will take a look at it here.
Please help me again when I'm in trouble.

Thank you for your help.

**Comment by CreaProjects** [comment] 2020-12-21 09:01
Same here. Before iOS 14 I was using Unity 2018 with the integrated Cardboard SDK it was working fluently.
Now with iOS 14, I had to update Unity to 2019 and manually install the new Cardboard SDK. It's very laggy, like 25fps instead of 60...

**Comment by Mandelbrow** [comment] 2021-01-12 16:14
Would say it's a bit saggy in Android too, compared to Unity 2018. It's like there are an initial slow start when moving the head, which catches up later. Like a rubber band. Perhaps the low pass filter for the gyro can be adjusted for it?

**Comment by jballoffet** [comment] 2021-01-15 19:43
Thanks @tokunodont for the details. Taking into account that this is taking place on iOS 14, this seems to be a duplicate of #164. @Mandelbrow, about the Android effect described, please take a look at #173.

**Closed** 2021-01-15 19:44 UTC
Labels: duplicate, question
