### ISSUE TITLE
Not compatible with Sprite Mask

### ISSUE THREAD

**Issue by HeavyArmoredMan** [googlevr/cardboard#319] opened 2021-12-20 10:56 UTC
### SPECIFIC ISSUE ENCOUNTERED
Unity Sprite Masks stop camera from tracking and displaying.

### SMARTPHONE (please complete the following information):
- Device: [Motorola Edge S]
- OS
  - [X] Android
- OS version [Android 11]

### STEPS TO REPRODUCE THE ISSUE
1. Setup URP for the "VrMode" sample scene;
2. Add a Sprite Mask Gameobject to the scene;
3. Build and run;
4. See the issue.

### EXPECTED BEHAVIOR
Sprite Masks should not stop camera from tracking and displaying.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard XR Plugin 1.10.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2021.2.7f1

- Select in which graphics API you can reproduce the bug.
   - [x] OpenGL ES3

### SCREENSHOTS
![SpriteMaskWCardboardXRPluginIssue](https://user-images.githubusercontent.com/30695317/146755604-db733eef-a990-4a74-93b9-d0a9993fb03d.jpg)

### ADDITIONAL CONTEXT
[Add any other context about the problem here.](https://user-images.githubusercontent.com/30695317/146756394-9764d0fa-4c4d-46b5-a4c3-fe29281c8064.mp4)

**Comment by arilow** [comment] 2022-05-11 17:02
Thanks @HeavyArmoredMan for reaching out to us! And sorry for the long delay. We have followed the steps you mentioned in order to try to reproduce the issue without success:
- Set up a Cardboard sample project by following the steps in the [Cardboard Quickstart for Unity](https://developers.google.com/cardboard/develop/unity/quickstart).
- Setup URP as it is shown in the following [Unity video](https://youtu.be/m6YqTrwjpP0?t=174).
- Add a Sprite Mask Gameobject to the scene;
- Build and run;
- The Cardboard sample works as it should.


Useful information:
- Cardboard OSS version: 1.15
- Phone: Samsung Galaxy S20 FE
- OS: Android 12
- Unity version: 2020.3
- URP version: 10.8.1


Could you please give it a try again using the latest release of the Cardboard XR Plugin? Some issues related to URP have been solved lately so this issue might have been solved as well.


In case the issue hasn’t been solved, it would be great if you could share a simple repro project with us so as to continue debugging it.


Thanks!

**Comment by arilow** [comment] 2023-04-18 18:24
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:24 UTC
Labels: bug
