### ISSUE TITLE
It doesn't support Vulkan and OpenGL 3.2 API.

### ISSUE THREAD

**Issue by fakeeyes** [googlevr/cardboard#69] opened 2020-06-26 12:34 UTC
It only support OpenGL 2.0 API. Anybody who knows for applying plan of Vulkan and OpenGL 3.2 API in Cardboard VR SDK?

**Comment by Handicap** [comment] 2020-07-08 11:52
I would like to know this too. The project I'm currently working on depends on OpenGLES3 for AR functionality so downgrading to OpenGLES2 is not an option.

**Comment by jballoffet** [comment] 2020-07-21 13:12
I’m closing this issue as is partially a duplicate of #40. For the Vulkan feature request, please open a new issue.

**Closed** 2020-07-21 13:12 UTC
Labels: duplicate
