### ISSUE TITLE
Motion blur

### ISSUE THREAD

**Issue by Mandelbrow** [googlevr/cardboard#269] opened 2021-05-31 09:41 UTC
Is there a setting to turn off the added motion blur when the head camera is moved?
I mean, the original Cardboard 5+ years ago rendered better when looking around in a scene. On that hardware.

**Comment by AlphaCircle** [comment] 2021-06-09 09:21
Hello Cardboard Team
When testing SDK1.5.0, I found there is still blurring in display when head moving around. When testing the same file with Google VR (old version of cardboard), I could not see any blurring on display in head move. My test phone is Android phone, Galaxy S11+.

I tested with applying the filter on gyro but that did not make a big change on the blur. Even worse thing is when looking up or down, I found the display speed can't meet my head move. The screen catches up when I stop moving.

I still suspecting the quaternion update using gyro data. But it's not comfortable to debug your Kalman and Quaternion code. Do you have any progress on it?

**Comment by jballoffet** [comment] 2021-06-18 15:06
Thanks for reaching out to us. I'm closing this issue as it is a duplicate of #173. Please feel free to leave comments on that issue. Thanks!

**Closed by jballoffet** 2021-06-18 15:06 UTC
Labels: bug, duplicate

**Comment by AlphaCircle** [comment] 2021-06-20 12:27
Hello jballoffset
I do agree with your approach. Just one tag is good enough for me to look at the progress. I wish you make success in solving this issue as soon as possible. I believe many of developers are waiting for the solution to this.
