### ISSUE TITLE
Migrating from gvr-unity-sdk to cardboard-xr-plugin in Unity

### ISSUE THREAD

**Issue by vishnu6266** [googlevr/cardboard#215] opened 2021-02-18 20:16 UTC
Hi,

 We had a mobile app developed in Unity using gvr-unity-sdk 2 years back. In the app users can view 360-degree videos and answer multiple-choice questions on top of the video to go to the next level. We are using video player and custom build prefabs for multiple-choice questions.

Because of recent spinning issues in iOS with gvr-unity-sdk, we are migrating the code to the cardboard-xr-plugin. 

The team is new to cardboard-xr-plugin and we are unable to display multiple-choice question prefab on top of the video through script or configuration just like we did with gvr-unity-sdk and we are blocked.

We searched for documents or guidelines that can help us migrate the code from gvr-unity-sdk to cardboard-xr-plugin,  but couldn't find one. 

Appreciate any help in this matter 

Thanks
Vishnu

**Comment by agalbachicar** [comment] 2021-02-19 21:59
Thanks a lot for filing this ticket. Would you please try to share a sample iOS project using our Cardboard XR Plugin with a minimalistic Scene that shows the error? You can share it as an attachment or with a link to a public Github repository.

Also, we would be interested in:

- The specific Unity version you are developing on.
- The specific iOS version you are targeting.
- You mentioned the questions were displayed in 360-degree videos... are you intending to work with or without distortion? Have you seen the [`VRMode.unity`](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Samples~/hellocardboard-unity/Scenes/VrMode.unity) scene? It allows you to get in out from VR (note that head tracker will also be disabled - if you need to keep it we can help you to do that).

**Comment by jballoffet** [comment] 2021-06-09 15:55
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by jballoffet** 2021-06-09 15:55 UTC
Labels: bug
