### ISSUE TITLE
 Is this a problem of depth？

### ISSUE THREAD

**Issue by wei292224644** [googlevr/cardboard#174] opened 2020-12-09 13:18 UTC
In the early version of gvr, I found that the depth of the object is different for the left and right eyes.
![407a6a0496fe787e9db3ed82f461052](https://user-images.githubusercontent.com/16398073/101634192-50667f80-3a63-11eb-851b-4c28af387e96.png)
![db231716e2929b4a9e5f75e14b54c6b](https://user-images.githubusercontent.com/16398073/101634224-5eb49b80-3a63-11eb-99c1-91a4af581769.png)
But in cardboard, I cannot reproduce this phenomenon
![f2966b4be185be80e22c0dcb8321335](https://user-images.githubusercontent.com/16398073/101634597-e6020f00-3a63-11eb-9c19-166eb67a5329.jpg)
![8b0314a4262757a40d21335eb10035b](https://user-images.githubusercontent.com/16398073/101634605-e8646900-3a63-11eb-8b92-d45cb3d0fd3a.png)

**Comment by jballoffet** [comment] 2020-12-18 21:07
Closing this issue as it seems to be a duplicate of #128.

**Closed** 2020-12-18 21:08 UTC
Labels: duplicate
