### ISSUE TITLE
Can you disable Stereoscopic Rendering like some kind of setting?

### ISSUE THREAD

**Issue by LuisKu** [googlevr/cardboard#226] opened 2021-03-13 04:01 UTC
**I know its a weird question, but how do you disable stereoscopic as an option.**
![try2](https://user-images.githubusercontent.com/61000456/111018450-d35ee500-8386-11eb-8c9f-59287927fd0e.jpeg)
To 
![try](https://user-images.githubusercontent.com/61000456/111018458-da85f300-8386-11eb-9a6d-e68ebce916c2.png)

**Comment by jballoffet** [comment] 2021-04-28 18:58
Sorry, but AFAICS, both images show stereoscopic rendering. Could you please provide more details about what the issue is and the purpose of the requested feature? Thanks!

**Comment by kaolin** [comment] 2021-05-24 02:54
I think the second pair is showing the /same/ image in left and right eye.

**Comment by jballoffet** [comment] 2021-09-17 14:38
@LuisKu I'm closing this issue since I'm not able to understand the question / feature request and it's been a while since the last comment. In case this is still an issue for you, please feel free to reopen this ticket. Thanks!

**Closed by jballoffet** 2021-09-17 14:38 UTC
Labels: question
