### ISSUE TITLE
Issues with Moto G8 on Android 10

### ISSUE THREAD

**Issue by naiteon** [googlevr/cardboard#130] opened 2020-10-05 03:33 UTC
Hi, I have a Moto G8 and unfortunately no Cardboard game works on it because of a cardboard bug.
It renders the left and right camera's textures wrongly! 

Youtube App also renders the two eyes right BUT there is something wrong with the field of view/alignment.... It causes instant eye strain :). So far this is the 6th device that i tested, and the only one to display these issues.

Please fix this, it is so annoying buying such a good phone for finding out it wont work with cardboard.
Thankfully its specs are good enough to run ARCore. So I'm using two cameras and ARCore to get around this bug.

Is it on the roadmap?

**Comment by naiteon** [comment] 2020-10-16 15:25
@jballoffet Is this also included in the next release 1.1.3?

**Comment by jballoffet** [comment] 2020-10-16 17:09
Given the issue description and the fact that a certain Cardboard game and the YouTube app were mentioned, I suspect this is not related to the new Cardboard SDK but to the old one. Please bear in mind that GVR and the old Cardboard SDK have been deprecated and this new version should be used instead. Having said that, if you’re still having issues with the new SDK, please reach out to us again, providing a repro project and the steps required to reproduce the issue.

**Comment by naiteon** [comment] 2020-10-29 18:15
Yes this is a problem with the Newest Google SDK (Unity XR Plugin version not the old one).

**Comment by agalbachicar-gg** [comment] 2020-11-17 21:22
Would you please attach a repro project? We have not encountered this issue on Android 9, 10 nor 11.

**Comment by naiteon** [comment] 2020-12-04 18:46
This does not happen in other devices, just on this Motorola G8!  There is a famous VR game called xTime! It runs smoothly on many devices BUT on Motorola G8!  I found out why now! Any project with both the new or old sdk is a valid reproducible project. If I share any project here that would be equivalent to you doing git clone ANY google cardboard example. As long as you do that on a Motorola G8 (Not G8 Play, nor G8 Plus) , I know they have some models only sold in some other countries. And I believe this is the case here, there is no such a thing as Moto G8 outside Brazil that is not either G8 Power, G8 Play or G8 Plus. But here they have a cheaper "Moto G8" and that happens 100% of the time i clone any google cardboard vr project independently if that is the old or new sdk based on XR Plugin. No Google Cardboard SDK game runs on this device because of this problem. Well not only that but Unity gyro.attitude also returns null because it has no magnetometer. But Google Cardboard's head tracking works perfectly, it is just the Eye sockets / Barrels not rendering correctly!

**Comment by naiteon** [comment] 2020-12-04 18:48
@chaosemer  Please dude! Check this out

**Comment by jballoffet** [comment] 2021-01-06 12:41
Can you please share the output of running `adb shell getprop ro.system.build.fingerprint` with the Moto G8 attached? This will allow us to know the exact variant affected.

Given that this issue is only reproducible on a very specific phone (Motorola G8), we will not be able to take care of it in the short run. It has been added to our backlog and will be prioritized along with other issues. We may not have access to this device if it is a Brazil-only device and would want to lean on you for help identifying the issue. Are you familiar with building via Android Studio?

**Comment by naiteon** [comment] 2021-01-15 20:36
Hey @jballoffet sure, I'll do that this weekend.

**Comment by jballoffet** [comment] 2021-06-09 15:08
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share the required details.

**Closed by jballoffet** 2021-06-09 15:08 UTC
Labels: bug
