### ISSUE TITLE
FOV second eye, objects wrongly not rendered on edge of screen?

### ISSUE THREAD

**Issue by friggasaint** [googlevr/cardboard#54] opened 2020-06-03 14:58 UTC
I'm observing objects wrongly not being rendered on the second camera, when objects are about to leave the FOV. 
Does anybody else also have this problem?
![Screenshot_20200603-164010 2](https://user-images.githubusercontent.com/1319045/84023698-defd2580-a988-11ea-9d09-df21ad50debd.png)

**Comment by RossMck** [comment] 2020-06-12 08:48
I have same issue,

**Comment by jballoffet** [comment] 2020-06-18 14:41
I’m not able to reproduce this issue. Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide:
- The required steps to expose the issue.
- The version of Unity being used.
- The phone being used.
- The viewer’s parameters being used.

**Comment by JacobBWaggoner** [comment] 2020-06-18 14:46
I am seeing the same issue in Unity 2019.3.12 on a Pixel 2 without changing the viewer perameters. It happens in any scene if objects move too far to one side of the view.

**Comment by friggasaint** [comment] 2020-06-21 17:05
I'm already getting this on a fresh project only conducting the quickstart steps for unity
unity 2019.3.13f
Sony Xperia XZ1 Compact
not changing viewer parameters

**Comment by friggasaint** [comment] 2020-06-30 14:10
My impression has become that the effect grows stronger with smaller screens.
We tested this on an old Iphone SE with a 4 inch screen, which seemingly gave an even worse effect than on my Sony Xperia XZ1 Compact (4.7 inch screen).
On a HTC U Ultra (5.7inch) we couldn't see any issues.
We tested all without changing the viewer params.

One problem might be that one camera is squinted too strongly inside.

**Comment by sammyvrmadman** [comment] 2020-09-18 10:09
Can confirm that I have the same issue on unity 2019.4.1.1f with an Iphone SE.

**Comment by jballoffet** [comment] 2020-10-16 15:26
Thanks for the details. We could not reproduce the bug in a Pixel 3XL. We would appreciate the confirmation of Cardboard V1 Viewer (default viewer) to know the device parameters in use. We will prioritise this issue along the others.

**Comment by dletozeun** [comment] 2020-10-16 15:30
Stumbling upon this issue, this makes me think of a problem with Occlusion Culling. Could you try disabling it on the camera? If you want to keep it you might need to make it again but maybe you can't use it properly in stereo.

**Comment by sammyvrmadman** [comment] 2020-10-20 09:48
> Thanks for the details. We could not reproduce the bug in a Pixel 3XL. We would appreciate the confirmation of Cardboard V1 Viewer (default viewer) to know the device parameters in use. We will prioritise this issue along the others.

When no other QR code is scanned does that mean the default is selected ? if so I can confirm that this happens on the Cardboard V1 Viewer (default viewer)

**Comment by BrianPickens** [comment] 2020-11-10 08:08
I've run into the same problem. Here is some info on it:

Repro Steps
-Download the linked GitHub Project
-Build the iOS project
-Use xCode 12.1 to build onto phone
-Open App
-Deny Camera Permissions (still occurs if you allow permission and scan a cardboard viewer)
-Look around and watch the objects on the left side of the right camera. They will disappear before they leave the players view.

Unity 2020.1.11f1
iPhone 7

[GitHub Project Link]( https://github.com/BrianPickens/VR-Bug.git)
[iPhone 7 Screen Record](https://github.com/googlevr/cardboard/files/5515662/VRBugVideo.zip)

**Comment by whizzkid** [comment] 2020-11-10 10:26
Same problem  here.
from the looks of it, it seems to me that if an object is culled for the left eye after leaving the screen, it's also culled for the right. which still has the object in the camera's frustum and shouldnt cull
unity 2019.4.14f1,  iphone SE

**Comment by jballoffet** [comment] 2021-01-18 15:12
Sorry for the long delay here. Thanks @BrianPickens for the repro project, I confirm that I’m able to reproduce the issue on an iPhone XR. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by jeff-rey-unity** [comment] 2021-02-28 15:56
Same on iPhone 6s

**Comment by RuudvanReenen** [comment] 2021-03-20 21:49
I can confirm the same issue here with an iPhone 6S and Cardboard SDK 1.4.1, Unity 2019.4.18f1. 
Left camera always renders correctly, but the right camera doesn't render objects that aren't visible in the left camera anymore, (at the left edge of the right camera view).

Is there a fix or workaround for this?

**Comment by RuudvanReenen** [comment] 2021-03-21 09:42
Noticed also that the right camera can see more of what's on the left than the left camera. You can see this clearly in the image of the first post. Are the cameras reversed?

Can this issue be related to https://github.com/googlevr/cardboard/issues/207 where the math goes wrong?

**Comment by Layfully** [comment] 2021-05-23 09:38
Can someone have a look at this the issue is still there. Is there any hack to prevent it from happening? Is this happening because of frustum culling?

**Comment by Vincze01** [comment] 2021-08-24 15:44
Same problem here.
Unity 2020.3.15f2, iPhone SE

**Comment by drfede** [comment] 2021-12-06 11:06
I found a solution, not the best one but it worked for me, I found out the issue it's caused by the camera's frustum which gets distorted, so what I did is manually modify the culling matrix of the camera to COMPLETELY disable the frustum culling.
Briefly what I did is:

```  
      void Start()
        {           
             UnityEngine.Rendering.RenderPipelineManager.beginCameraRendering += OnBeginCameraRendering;
        }

       private void OnBeginCameraRendering(ScriptableRenderContext context, Camera camera)
        {
            camera.cullingMatrix = Matrix4x4.Ortho(-99999, 99999, -99999, 99999, 0.001f, 99999) *
                    Matrix4x4.Translate(Vector3.forward * -99999 / 2f) *
                    camera.worldToCameraMatrix;
        }
        
  ```

**Comment by Layfully** [comment] 2021-12-07 09:54
This is good start! I will try to look into this deeper. My solution was to increase mesh bounds of every mesh. Your solution is simpler, but less performant.

**Comment by jballoffet** [comment] 2022-01-18 11:52
A fix for this issue has been submitted and it will be included in v1.12.0. Thanks for reaching out!

**Comment by xinyunh0929** [comment] 2022-02-01 23:49
This was fixed in v1.12.0.

**Closed by xinyunh0929** 2022-02-01 23:49 UTC
Labels: bug, fixed in upcoming release
