### ISSUE TITLE
OPENGL NATIVE PLUG-IN ERROR

### ISSUE THREAD

**Issue by UnityKR** [googlevr/cardboard#150] opened 2020-10-27 11:56 UTC
HelloCardboard (Sample Scene)

After set as
Project Settings > Quality > Anti Aliasing > 2x Multi Sampling

The following message is displayed repeatedly on iPhone

=================================================

OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range 
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 354)

=================================================

please fix it.

**Comment by JoaoBorks** [comment] 2020-10-29 13:44
As far as I know, MSAA is not supported by Google Cardboard. I don't know if they have plans to support it.

**Comment by jballoffet** [comment] 2020-11-09 18:39
I’m not able to reproduce this issue by using HelloCardboard sample scene and setting “2x Multi Sampling” anti aliasing option. Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide the required steps to expose the issue and details such as the phone being used, Unity version, etc.

**Comment by UnityKR** [comment] 2020-11-15 14:06
> I’m not able to reproduce this issue by using the HelloCardboard sample scene and setting “2x Multi Sampling” anti aliasing option. Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide the required steps to expose the issue and details such as the phone being used, Unity version, etc.


HelloCardboard Sample Project
Unity 2019.4.5f1
iPhone 11
iOS 14.1

on iPhone.

In addition, UI Mask is not applied to the iPhone.

**Comment by agalbachicar-gg** [comment] 2020-11-17 21:30
Would you please share a repro project? I think we are going to get to the configuration problem faster. Thanks!

**Comment by UnityKR** [comment] 2020-12-08 11:39
> I’m not able to reproduce this issue by using the HelloCardboard sample scene and setting “2x Multi Sampling” anti aliasing option. Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide the required steps to expose the issue and details such as the phone being used, Unity version, etc.

jballoffet
I sent a sample project by email.

**Comment by jballoffet** [comment] 2021-01-29 21:48
@UnityKR, sorry for the delay here. I cannot download the project that you've sent via email, would you be so kind as to share a link to download it here? Thanks!

**Comment by jballoffet** [comment] 2021-06-09 15:24
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by jballoffet** 2021-06-09 15:24 UTC
Labels: bug
