### ISSUE TITLE
[Unity] [1.11.0] [Android] Api.SaveDeviceParams only works with URLs that have at least one redirect

### ISSUE THREAD

**Issue by johnfriedrich** [googlevr/cardboard#323] opened 2022-01-18 15:00 UTC
### SPECIFIC ISSUE ENCOUNTERED
Trying to save Device Params manually via Api.SaveDeviceParams(string url). But it doesnt save the params. Isnt able to get it. See error below.

```
Api.SaveDeviceParams("https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI");
```
On the phone the  following error pops up:
```
Following redirects for original URI: https://arvr.google.com/cardboard/download/?p=CgZIT01JRE8SBEdSQUIdCtcjPSWPwnU9KhAAAEhCAABIQgAASEIAAEhCWAE1KVwPPToIexSuPs3MzD1QAGAD
01-18 15:48:06.792 11019 11047 I CardboardParamsUtils: Response code: 200
01-18 15:48:06.792 11019 11047 E CardboardParamsUtils: Error when following URI redirects
01-18 15:48:06.792 11019 11047 E CardboardParamsUtils: Error when trying to get the Cardboard params from URI: https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
```

When using the shortened url, in this case ``` goo.gl/cfliQY ``` (which redirects to the url above) it works.
Seems like there is an logic error in the follow redirect method in the android native part of the sdk, probably somewhere here:
https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L537

Urls only work, if there is at least one redirect I guess.

### SMARTPHONE (please complete the following information):
- Device:Nokia 7.2

### STEPS TO REPRODUCE THE ISSUE
Try to set Api.SaveDeviceParams in Unity when targeting Android. (Did not test iOS, *could* be the same issue here)

### EXPECTED BEHAVIOR
Sdk should download device params

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.11.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2020.3.25f1

- Select in which graphics API you can reproduce the bug.
   - OpenGL ES3

**Comment by arilow** [comment] 2022-01-21 19:38
Thanks @johnfriedrich for reaching out to us, I confirm that I’m able to reproduce the issue on an Android phone.

## Investigation

I added some logs and a `null` validation in [followCardboardParamRedirect()](https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L537) to see the URI redirections. This is what I’ve found:

1. By calling:
```
Api.SaveDeviceParams(“goo.gl/cfliQY”);
```

The Logs are:
```
01-20 11:19:37.956 26382 28929 D CardboardParamsUtils: https://goo.gl/cfliQY
01-20 11:19:38.296 26382 28929 D CardboardParamsUtils: https://google.com/cardboard/cfg?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
```

And it works (the device params are properly saved).

2. By calling:
```
Api.SaveDeviceParams("https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI");
```

The logs are:
```
01-20 11:25:02.078 26938 31976 D CardboardParamsUtils: https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
01-20 11:25:02.357 26938 31976 E CardboardParamsUtils: Error when following URI redirects
01-20 11:25:02.399 26938 31976 E CardboardParamsUtils: Error when trying to get the Cardboard params from URI: https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
```

And the device params aren’t saved. The problem is that the URI to which both cases redirect is different (`https://goo.gl/cfliQY` redirects to `https://google.com/cardboard/cfg?p=` which is different from `https://arvr.google.com/cardboard/download/?p=`). 

## Workaround 1

Instead of using:
```
Api.SaveDeviceParams("https://arvr.google.com/cardboard/download/?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI");
```

Use:

```
Api.SaveDeviceParams("https://google.com/cardboard/cfg?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI");
```
The device params should be properly saved. It worked properly on my end.

## Workaround 2

Now, if you need to use the prefix `https://arvr.google.com/cardboard/download/?p=`, then you’ll need that [`isCardboardUri(uri)`](https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L540) returns true when it receives an URI with that prefix. It is validated [here](https://github.com/googlevr/cardboard/blob/e7a1c22e456ff67116dd016c760dcc469bfa973e/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L243). Lastly, the constants that you’ll need to modify are: [`URI_HOST_GOOGLE`](https://github.com/googlevr/cardboard/blob/e7a1c22e456ff67116dd016c760dcc469bfa973e/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L60) and [`URI_PATH_CARDBOARD_CONFIG`](https://github.com/googlevr/cardboard/blob/e7a1c22e456ff67116dd016c760dcc469bfa973e/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L66).

Once all changes have been applied, you’ll need to follow the [instructions to generate the sdk.aar file](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/Android/generate_sdk_aar.md) in order to rebuild the Cardboard SDK with your changes and update it within the Cardboard XR Plugin.

I am closing this issue given that this is expected behavior. Feel free to reopen it if you need any help or this is still an issue for you.

**Closed** 2022-01-21 21:05 UTC
Labels: bug
