### ISSUE TITLE
Quickstart Android Static Screen

### ISSUE THREAD

**Issue by STWFuller** [googlevr/cardboard#183] opened 2020-12-22 21:11 UTC
Hello I followed the quickstart guide for android, every step of the way
I am using an Oppo A5 2020, color os7.1 Android 10.
Unity 2020.2.0f1.3688.6 personal

I manage to run HelloCardboard and VrMode on the phone but the gyroscope does not work.
I only see a frozen image of the CubeRoom with the cube in the middle, no interaction.

Any ideas?

Thanks in advance,

Samuel

**Comment by venim1103** [comment] 2021-01-04 16:32
I have the same problem with Xiaomi 9 SE. I installed the Google Play Services for AR and at first I got everything working with only using OpenGLES2 ( cardboard-xr plugin version 1.41 ) and building the VrMode demo with Unity 2019.4.17f1 personal.

After trying to build with OpenGLES3 ( cardboard-xr plugin version 1.41 ) there were no errors and the application built and ran,  but the same thing happened as with STWFuller here that the app didn't load the Cardboard double slit view nor did it have any reaction from gyroscope. Just a frozen image.

I hope this information helps with locating the problem...

**Comment by jballoffet** [comment] 2021-01-04 19:42
Thanks for reporting this issue. Unfortunately, I cannot repro it locally on my devices. Could you please share a simple repro project with us where the issue is shown and the steps required to reproduce it?

**Comment by venim1103** [comment] 2021-01-04 20:43
Hi sorry for raising this problem without further research.
I was struggling with this for a while but I found out what was the problem in my system.
As I was moving from older Unity version and having used the OpenGLES2 before, I now made a new project testing out any updates. While going through the Quickstart Guide I didn't realize that after the update I also had updated to the newest Android SDK (not 28 anymore which I still assumed mine being as I never needed newer than Android 9 version for testing...) meaning that the highest installed API was now higher than 29 thus I required to add the enabling of android:requestLegacyExternalStorage="true" into the Androidmanifest.xml as it was mentioned in the Guide. After those changes everything now works as expected.
So I guess a lesson for anyone here, remember to make sure you read the Guide carefully :)

**Comment by STWFuller** [comment] 2021-01-06 18:39
Hey venim1103,

Thanks for engaging with my question.
I double checked and I had added android:requestLegacyExternalStorage="true" into the Androidmanifest.xml as it was mentioned in the Guide.

That does not seem to be the problem.
I tried changing to OpenGLES3 but that didn't change anything.

@jballoffet I followed every step of the quickstart guide unity android and exported to Oppo A5 2020, color os7.1 Android 10..

What do you mean with sharing a repro?

Thanks in advance. STWF

**Comment by jballoffet** [comment] 2021-01-08 20:19
Sorry if I wasn't clear enough. In order to help you, I'd need the Unity project that you have created so I can build it and install it on a phone and check whether I can reproduce the issue. In case that I'm able to do so, having the project would allow me to take a look at it at debug the issue. It's ok if it was created just following the quickstart guide. Please also attach the steps required to reproduce the issue.

**Comment by jballoffet** [comment] 2021-06-09 15:40
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by jballoffet** 2021-06-09 15:40 UTC
Labels: bug
