### ISSUE TITLE
CRASH! DeinitializeLoader Re-enable VR

### ISSUE THREAD

**Issue by iwellsSI** [googlevr/cardboard#73] opened 2020-07-02 14:48 UTC
The app crashes after turning off the VR and re-enabling VR.  Logcat reports a "**Null Point Dereference**".

I have tried to not call the DeinitializeLoader which looked like it fixed the crash but when I re-enable the VR, a tiny camera view window appears in the top left corner at the same time as the screen is showing the camera view in VR mode.  The app will again crash at the 4th time of re-enabling VR with a "**signal 6 (SIGABRT), CODE -6 (SI_TKILL), fault addr --------**" and at the end of the log "**other thread is trapped; signum = 6**" error.

Please help!

**Comment by MrETea** [comment] 2020-07-03 06:57
It looks like a few people have had this problem can we get any sort of update or help please. There appears to be no fix and it is crippling development. We are at a total standstill.

**Comment by ankityudiz** [comment] 2020-07-03 13:38
Yes face this issue today with same scenario turning off the VR and re-enabling VR app get crashed.
Cause of crash is: Null Point Dereference.
Please Help with this issue if anybody has solved it.

**Comment by myserioushenri** [comment] 2020-07-06 13:25
Same problem for us, our development is blocked because of this bug.

**Comment by RajatPatel5** [comment] 2020-07-06 13:39
I was also facing the same issue and later I just removed DeInitializeLoader call. I just used StopSubsystems to stop VR and later I can start it again with StartSubsystems. This works for me but the only issue I get is for Blacked out close and settings button. 
[](https://github.com/googlevr/cardboard/issues/50) 
Note: I used `UnityEngine.XR.Management.XRGeneralSettings.Instance.Manager.InitializeLoaderSync();` for initialization and 
`UnityEngine.XR.Management.XRGeneralSettings.Instance.Manager.StartSubsystems();` and `UnityEngine.XR.Management.XRGeneralSettings.Instance.Manager.StopSubsystems();` for starting and stopping VR cardboard view.

**Comment by D3m0n92** [comment] 2020-07-08 09:34
Same issue...

**Comment by D3m0n92** [comment] 2020-07-09 14:48
Solution: https://assetstore.unity.com/packages/tools/camera/cardboard-net-168945

Buy this package (the cost is very sustainable) and you will solve all the problems of this officially shameful SDK. I solved it this way.

**Comment by TrveFenris** [comment] 2020-07-14 03:21
Having the exact same issue.

Calling just the `StartSubsystems()` and `StopSubsystems()` didn't work as expected since the application goes back to 2D mode but if you change apps and focus the Unity application again, it starts in VR mode. I'm using `Unity 2019.3.13f1` and bulding on an Android 10 device.

I'm also experiencing a "cropped" screen issue if I try to initialize the XR Manager manually via scripts (while the option to initialize at start works flawlessly...).

**Comment by jballoffet** [comment] 2020-07-21 13:24
Duplicate of #59.

**Closed** 2020-07-21 13:24 UTC
Labels: duplicate

**Comment by iLyxa3D** [comment] 2020-07-31 09:34
Was broken in my Unity 2019.3 project, month ago, but works fine now in Unity 2020.1.0.. Unbelievable :)

**Settings:**
![VR Othereality v2020 - MainScene - Android - Unity 2020 1 0f1 DX11](https://user-images.githubusercontent.com/7745856/89022014-08ec1c00-d32a-11ea-8585-b7ebe58c0b37.jpg)


**Code:**
```
/*  if (!Api.HasDeviceParams())   // lead to crash on Samsung Galaxy S7 (at void Start)
        {
            Debug.Log("Api.ScanDeviceParams");
            Api.ScanDeviceParams();
        }*/

 IEnumerator DelayCardboardIn()
    {    
        screenBrightOnStart = Screen.brightness;
        sleepTimeoutOnStart = Screen.sleepTimeout;

        Screen.sleepTimeout = SleepTimeout.NeverSleep;
        Screen.brightness = 1.0f;

        
        if (!XRGeneralSettings.Instance.Manager.isInitializationComplete)
        {
            Debug.Log("> InitializeLoaderSync");
            XRGeneralSettings.Instance.Manager.InitializeLoaderSync();
            yield return new WaitForSeconds(1f);
        }
        Debug.Log("> StartSubsystems");
        XRGeneralSettings.Instance.Manager.StartSubsystems();
}

 IEnumerator DelayCardboardOut()
    {     
        Debug.Log("> StopSubsystems");
        XRGeneralSettings.Instance.Manager.StopSubsystems();  // no screen freeze here!

        Screen.brightness = screenBrightOnStart;
        Screen.sleepTimeout = sleepTimeoutOnStart;
}
```
