### ISSUE TITLE
Left/right inverted when in VR

### ISSUE THREAD

**Issue by lz7cjc** [googlevr/cardboard#316] opened 2021-12-09 12:17 UTC
Hi 
This has only started happening in the last few months. I can't think of anything changing with my setup and i have tested on two devices. It works as expected, in editor mode

Obviously looking the right way is fundamental to my experience so any help in tracking down the problem would be hugely appreciated.

I found
https://answers.unity.com/questions...n-vie.html?childToView=1874486#answer-1874486
https://github.com/googlevr/gvr-unity-sdk/issues/1031
but neither have resolved the problem

I would hugely appreciate some help in getting this fixed
thanks

2019.4.31f1
Google 1.8.0

**Comment by arilow** [comment] 2022-01-20 15:06
Thanks for reaching out to us! Sorry for the long delay here. Could you please provide more information about the issue, such as:

- Does the issue take place with the sample app, Hello Cardboard?
- Is this taking place on Android or iOS phones?
- The phone and OS version being used.
- What orientation is being used by default? Is the orientation changed at runtime?
- Does the issue take place when using the latest release of the Cardboard SDK (v1.11.0)? Bear in mind that some orientation issues have been fixed since v1.8.0.  


It would also be really helpful if you could provide a repro project and the steps required to reproduce the issue.


Thanks!

**Comment by lz7cjc** [comment] 2022-01-24 19:17
> Thanks for reaching out to us! Sorry for the long delay here. Could you please provide more information about the issue, such as:
> 
>     * Does the issue take place with the sample app, Hello Cardboard?
> 
>     * Is this taking place on Android or iOS phones?
> 
>     * The phone and OS version being used.
> 
>     * What orientation is being used by default? Is the orientation changed at runtime?
> 
>     * Does the issue take place when using the latest release of the Cardboard SDK (v1.11.0)? Bear in mind that some orientation issues have been fixed since v1.8.0.
> 
> 
> It would also be really helpful if you could provide a repro project and the steps required to reproduce the issue.
> 
> Thanks!

only 5 weeks .... 
the problem was a negative value in the transform component of the object containing the camera

**Comment by arilow** [comment] 2022-01-25 14:47
We're glad to hear that you were able to solve this issue. Therefore, we're closing this ticket now. 

Thanks!

**Closed by arilow** 2022-01-25 14:47 UTC
Labels: bug
