### ISSUE TITLE
Issue with google VR unity SDK in ios and Migration to cardboard-xr-plugin due to the same

### ISSUE THREAD

**Issue by vaishakhcherukat** [googlevr/cardboard#216] opened 2021-02-19 06:02 UTC
we are developing an app which gives the users an option to add VR content to the app by scanning respective QR codes and play the content by either downloading the video to the device or streaming it directly from the server.

We have implemented these features too and when we started testing the VR content in the devices, its playing correctly in android devices. But in iOS devices with iOS version 14 or above, the video is continuously spinning when we open it in the video player.

On further investigation we got to know that this issue is only there with the iOS devices with OS version 14 or above. in all the other devices with os Version 13 or lower, this issue is not there and we are able to play the video correctly.

After checking multiple blogs and issues in github, we got to know that this issue is happening due to the error in the calibration of gyroscopic sensors in iOS 14 devices.
and a temporary fix to the issue is to toggle the location services and restart the devices. This will reset the gyroscopic sensors But  the temp fix will only last for a few hours or even a few minutes.

We checked other VR applications available and found out that the issue is with google VR SDK. So as an alternative solution, we started with a new SDK (google-cardboard-xr). Did a sample application and tested the same in iOS 14 devices and found that the spinning issue is not there.

Now when we started migrating the actual app into the new SDk, we are facing issues with integrating the interactions(which are multiple choice questions presented to the users so that user can select one from them to progress tot he next scene) into the VR content videos. 

It would be really helpful if you could help us in debugging the issues and fixing the same.

**Comment by lalabye** [comment] 2021-02-20 06:38
now, our app has the same question!   It would be really helpful if you could help us in debugging the issues. thanks

**Comment by maartenslaa** [comment] 2021-02-22 08:14
I would like to share I'm on iOS 14 and I do not have this issue. I don't think there is iOS 14 specific code in the SDK.

Some information on the Cardboard SDK: it does try to compensate for gyro drift. It resets the bias when it notices the device is steady, when it lays on a flat surface for instance. This value is saved between app restarts. If you have calibrated the device with the location services but have not done the cardboard calibration in the app, it may try to offset an error that is not there anymore and will start spinning the other way. You can calibrate by laying the device flat on a table (when the app is running) for a couple of seconds and see if that helps.

**Comment by jballoffet** [comment] 2021-04-28 21:06
Thanks for reaching out to us! Sorry for the long delay here. AFAICS, the issue is related to the overlay of assets (multiple choice questions) on top of the VR scene, and as such, it seems to be a duplicate of #238. In case you consider this is due to a different reason, please reach out to us again, providing a simple repro project where the issue is depicted and the steps required to reproduce it. Please also feel free to comment or share the repro project in #238. Thanks!

**Closed by jballoffet** 2021-04-28 21:06 UTC
