### ISSUE TITLE
Is it possible to set cardboard profile in script?

### ISSUE THREAD

**Issue by dreconater** [googlevr/cardboard#406] opened 2023-05-05 13:10 UTC
Hello. 
Is it possible to set cardboard profile in script?

**Comment by arilow** [comment] 2023-05-08 13:19
Thanks @dreconater for reaching out to us!

Yes it is possible to set a Cardboard profile in a script, you can call [CardboardQrCode_saveDeviceParams()](https://github.com/googlevr/cardboard/blob/master/sdk/include/cardboard.h#L673). 

Please let us know if you need further help regarding this.

Thanks!

**Comment by arilow** [comment] 2023-05-08 14:32
Closing as duplicate of #375.

Feel free to add any questions you might have on that ticket. 

Thanks!

**Closed by arilow** 2023-05-08 14:32 UTC
Labels: duplicate, question
