### ISSUE TITLE
[iOS] [1.5.0] [Unity] Split Line and Ui Buttons are rendered at the wrong position on notch devices

### ISSUE THREAD

**Issue by johnfriedrich** [googlevr/cardboard#268] opened 2021-05-28 12:19 UTC
I used Unity 2020.3.10f with the Demo scene on an iPhone XS with iOS 14.6.

On the first start, the cross and settings icon are correctly positioned outside the notch area and the split line seems to be at the correct position.
When hitting the cross to quit vr, the app crashes.

When restarting the app, vr renders inside notched area. Buttons stop working and the splitline renders at the wrong location.
It fixes itself when I manage to somehow hit the settings button and press skip. Button touch zone seems to be at anothe rposition

![image](https://user-images.githubusercontent.com/4679374/119982827-9f778100-bfbf-11eb-950c-ecaf7f25448b.png)

**Comment by jballoffet** [comment] 2021-05-31 11:40
Thanks for reaching out to us. I'm closing this issue as it is a duplicate of #253.

**Closed** 2021-05-31 11:40 UTC
Labels: duplicate
