### ISSUE TITLE
[Bug] Button Click is happened only when touching Left Eye area

### ISSUE THREAD

**Issue by andrewio** [googlevr/cardboard#113] opened 2020-09-15 18:58 UTC
Cardboard XR
iOS 13.7
iPhone XS Max
Unity 2019.4.10

**Comment by andrewio** [comment] 2020-09-16 09:12
Also, this button click in left eye area is happened when touching the button on its physical area and NOT on entire left area when center gazed at this button. How to fix this also?

**Comment by agalbachicar-gg** [comment] 2020-11-17 21:07
We have a similar issue which was addressed on #100 and we reproduced it with an iPhone X. We are making this issue as fixed in upcoming release because of their similarity but please do tell us if you think the problem is another or after upgrading to release v1.4 the problem persists.

**Comment by chaosemer** [comment] 2020-12-04 18:40
v1.4.0 is out. Resolving this as fixed. Please reopen if you still have issues with the v1.4.0 release.

**Closed by chaosemer** 2020-12-04 18:40 UTC
Labels: bug, fixed in upcoming release
