### ISSUE TITLE
Unity Build Failure: A failure occured while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by MonolithMan** [googlevr/cardboard#386] opened 2022-12-03 03:03 UTC
![Build Failure](https://user-images.githubusercontent.com/119715434/205419111-abdc7ba1-3704-4350-aa8e-3b9ff07d57c1.JPG)
Hi! I always get this build failure whenever I try to build with the google cardboard XR plugin. I can build my project perfectly fine without the google cardboard XR plugin so I figured there was something wrong with the plugin or I did something wrong. 

I use unity version 2020.3.36f1
I've tried switching versions but the same thing 
I've tried reinstalling the android build support 
I've tried reimporting the google cardboard XR Plugin and followed the quickstart for google cardboard

Here's what the console says:
![Console Pic](https://user-images.githubusercontent.com/119715434/205419132-04564af5-d970-4407-876b-4c9c91caed15.JPG)

Details of the 1st error:

Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:javaPreCompileRelease
> Task :launcher:prepareLintJar
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:processReleaseManifest
> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:collectReleaseDependencies
> Task :launcher:sdkReleaseDependencyData
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :launcher:mergeReleaseResources
> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibCompileToJarRelease
> Task :unityLibrary:bundleLibRuntimeToJarRelease
> Task :launcher:processReleaseResources FAILED
> Task :launcher:mergeReleaseJavaResource
> Task :launcher:desugarReleaseFileDependencies
37 actionable tasks: 37 executed

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Details of 2nd error:

Note: C:\Users\ADMIN\My project (3)\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:4:5-94: AAPT: error: resource android:color/system_neutral1_900 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:5:5-93: AAPT: error: resource android:color/system_neutral1_0 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:6:5-94: AAPT: error: resource android:color/system_neutral1_800 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:7:5-94: AAPT: error: resource android:color/system_neutral1_700 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:8:5-94: AAPT: error: resource android:color/system_neutral1_600 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:9:5-94: AAPT: error: resource android:color/system_neutral1_500 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:10:5-94: AAPT: error: resource android:color/system_neutral1_400 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:11:5-94: AAPT: error: resource android:color/system_neutral1_300 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:12:5-94: AAPT: error: resource android:color/system_neutral1_200 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:13:5-94: AAPT: error: resource android:color/system_neutral1_100 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:14:5-93: AAPT: error: resource android:color/system_neutral1_50 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:15:5-93: AAPT: error: resource android:color/system_neutral1_10 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:16:5-102: AAPT: error: resource android:color/system_neutral2_1000 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:17:5-102: AAPT: error: resource android:color/system_neutral2_900 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:18:5-101: AAPT: error: resource android:color/system_neutral2_0 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:19:5-102: AAPT: error: resource android:color/system_neutral2_800 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:20:5-102: AAPT: error: resource android:color/system_neutral2_700 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:21:5-102: AAPT: error: resource android:color/system_neutral2_600 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:22:5-102: AAPT: error: resource android:color/system_neutral2_500 not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Details of 3rd error:

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Note: C:\Users\ADMIN\My project (3)\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:4:5-94: AAPT: error: resource android:color/system_neutral1_900 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:5:5-93: AAPT: error: resource android:color/system_neutral1_0 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:6:5-94: AAPT: error: resource android:color/system_neutral1_800 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:7:5-94: AAPT: error: resource android:color/system_neutral1_700 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:8:5-94: AAPT: error: resource android:color/system_neutral1_600 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:9:5-94: AAPT: error: resource android:color/system_neutral1_500 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:10:5-94: AAPT: error: resource android:color/system_neutral1_400 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:11:5-94: AAPT: error: resource android:color/system_neutral1_300 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:12:5-94: AAPT: error: resource android:color/system_neutral1_200 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:13:5-94: AAPT: error: resource android:color/system_neutral1_100 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:14:5-93: AAPT: error: resource android:color/system_neutral1_50 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:15:5-93: AAPT: error: resource android:color/system_neutral1_10 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:16:5-102: AAPT: error: resource android:color/system_neutral2_1000 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:17:5-102: AAPT: error: resource android:color/system_neutral2_900 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:18:5-101: AAPT: error: resource android:color/system_neutral2_0 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:19:5-102: AAPT: error: resource android:color/system_neutral2_800 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:20:5-102: AAPT: error: resource android:color/system_neutral2_700 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:21:5-102: AAPT: error: resource android:color/system_neutral2_600 not found.
         
     C:\Users\ADMIN\.gradle\caches\transforms-2\files-2.1\a0ebba694f8e6a95bc427eaef4894530\material-1.6.1\res\values-v31\values-v31.xml:22:5-102: AAPT: error: resource android:color/system_neutral2_500 not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\UnityEditorFolder\2020.3.36f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:javaPreCompileRelease
> Task :launcher:prepareLintJar
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:processReleaseManifest
> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:collectReleaseDependencies
> Task :launcher:sdkReleaseDependencyData
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :launcher:mergeReleaseResources
> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibCompileToJarRelease
> Task :unityLibrary:bundleLibRuntimeToJarRelease
> Task :launcher:processReleaseResources FAILED
> Task :launcher:mergeReleaseJavaResource
> Task :launcher:desugarReleaseFileDependencies
37 actionable tasks: 37 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <544f727be82940559155d775b51cba8c>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <544f727be82940559155d775b51cba8c>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <544f727be82940559155d775b51cba8c>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by CamiloMGS** [comment] 2022-12-04 17:03
Hello,
Did you select Target API Level -> API Level 31?

**Comment by arilow** [comment] 2022-12-19 15:20
Thanks @MonolithMan for reaching out  to us, and sorry for the delay!


I was able to reproduce the log you are mentioning by setting the **Target API Level** to a value lower than 31.


So, as @CamiloMGS is poting out, I would recommend you to try setting the **Target API Level** to 31 as it is mentioned in the [Quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#other_settings).


On the other hand, the **Target API Level** is directly related to the dependencies added in `mainTemplate.gradle` (Some of them require API level 31 to build, you can check them [here](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings)). So, if for any reason you can’t set it to 31, then you will need to adapt those dependencies to the target API level you are using.


I’m closing this issue as it should be resolved. Please feel free to reopen if that is not the case.


Thanks!

**Closed by arilow** 2022-12-19 15:20 UTC

**Comment by rowialfata** [comment] 2023-02-21 07:41
> 

This works for me. Thanks!
