### ISSUE TITLE
Stuttery at ~60fps and smooth at ~30fps 

### ISSUE THREAD

**Issue by garydoesthings** [googlevr/cardboard#165] opened 2020-11-19 19:20 UTC
Android, using Unity 2020.1.13f1. Test device is a Pixel 1 XL (baseline target hardware).

I have an FPS tracker running when I test my builds on the device. When the counter reports ~60fps, the experience is stuttery as if frames are being dropped or tracking is locking up. However, when the app caps down to 30fps (I understand that mobile devices do this when performance can't sustain higher rates) all stuttering disappears and the experience is far more smooth though obviously at a lower framerate. I'm can't quite tell, but since the frame rate is high, my guess is that something is going wrong on with tracking when rendering at the higher rate. 

This behavior is not limited to my specific project. In using the Hello Cardboard sample scene, it is easy to reach maximum FPS, at which point the stuttering occurs.

**Comment by TediumInteractive** [comment] 2020-11-29 13:47
I also experience severe stuttering in scenes with low graphical fidelity even though profiling indicates a high framerate. Cranking up the graphics quality removes the stuttering. Quite unintuitive. 😄 

Experienced on Unity 2020.1 and 2019.4, when building to android device Moto G7 Play.

**Comment by TediumInteractive** [comment] 2020-11-29 16:07
Ok, so I did some further thinking and testing and realized that it is actually the enabling of the vertical sync in the quality settings that make the stuttering go away. In my case at least.

However, the game still stutters heavily during the display of the "Made with Unity Logo" before the first scene has been loaded even if vertical sync is enabled. Due to the nature of the stuttering, it seems to be a related issue.

**Comment by jballoffet** [comment] 2020-12-01 14:41
This seems to be a duplicate of issue #99. I am closing this as a duplicate, however if the experienced issue is not related, please reopen, providing a video in which the issue is depicted, the steps required to repro and the phones being used.

**Closed** 2020-12-01 14:42 UTC
Labels: bug, duplicate

**Comment by TediumInteractive** [comment] 2020-12-01 16:00
It's far from obvious how it could be regarded as the same issue as #99. It looks like a deeper issue than just poor Gyro tracking, I thought it was just poor gyro tracking at first, although adding a spinning cube to the scene makes it obvious that frames are definitely being dropped.

The weird thing is that it is resolved by forcing the project to be throttled to a lower frame rate of 30 rather than 60 fps by increasing the graphical fidelity. This should give strong hints to somebody with the knowledge of the project's rendering logic to find and fix the issue.

**Comment by TediumInteractive** [comment] 2020-12-01 22:01
@jballoffet @garydoesthings 

Okay so I have dug around and I believe I have found the setting that causes the issue. 🥳 

The frame stutter seems to be caused by having `Optimized Frame Pacing` (Swappy) enabled. In unity `2019.4.15f` this is turned off by default. However, in unity `2020.1.15f` it is turned on by default.

Device: Moto G7 Play
Unity Version: `2020.1.15f`, `2019.4.15f`

Reproduction steps:
1. Create a new unity project
2. Follow the [quickstart instructions](https://developers.google.com/cardboard/develop/unity/quickstart) for android 
3. Make sure `Optimized Frame Pacing` is checked under `Project Settings > Player > Resolution and Presentation`
4. Build the `HelloCardboard` scene and Observe the stutter

Video example: [stutter.zip](https://github.com/googlevr/cardboard/files/5625560/stutter.zip)

In the `HelloCardboard` scene, it might be mistaken for jittery gyro tracking. Add an object with a smooth motion to the scene and behold its laggy motion. I would suggest adding such an object to the scene by default to make it easier to differentiate between these kinds of issues.

**Comment by Excubitor** [comment] 2020-12-02 15:47
iOS seems to also work better with a lower fixed fps (when turning speedily) and there is no optimize pacing option there.
