### ISSUE TITLE
Fresh build on iOS not showing VR till leave and come back

### ISSUE THREAD

**Issue by hawkwood** [googlevr/cardboard#27] opened 2020-04-09 21:33 UTC
iPhone X running iOS 13.4, build with Xcode 11.4.  I followed the Quick Start instructions, and the project compiles and runs without error (lots of OpenGL related warnings), but the screen is black except for the white dividing line, back arrow, and gear. 

On launch, Xcode console says:
2020-04-09 13:17:48.464530-0700 HelloCardboard[2402:649311] Metal GPU Frame Capture Enabled
2020-04-09 13:17:48.466022-0700 HelloCardboard[2402:649311] Metal API Validation Enabled

If I tap the gear, then "Switch Cardboard", camera prompt shows, then QR scanner with camera passthrough showing.  I scan the QR code, and immediately get prompted to scan again (which it does almost automatically as it is still aligned), then back to the mostly black screen.

If I swipe up to show the app switcher, then select the app again, the VR room is showing and responding.

If I rescan the QR code, the VR room will be frozen till I switch away and back to the app.

One issue seems to be in the initial settings of _isPaused.  If I change line 75of HelloCardboardViewController.mm to
  _isPaused = YES;

then, on first launch the QR scan prompt is triggered, and on future launches, the VR room is active immediately.

The other issue seems to be that _updateParams isn't getting set to NO after the QR scan process; maybe the QR scan overlay isn't being presented properly and thus not triggering the GLKViewController automatic pause/resume functionality?

**Comment by jballoffet** [comment] 2020-06-22 13:37
I executed the steps described above and I wasn’t able to reproduce this issue. Could you please try this again, taking the following into account:
- Use Cardboard SDK [last release](https://github.com/googlevr/cardboard/releases/tag/v1.1.0) (v1.1.0)
- Uninstall HelloCardboard app before reinstalling (to avoid the usage of cashed parameters).
- Check that you have internet connection before running the app (this is required if you are scanning a Cardboard V2 viewer).

**Comment by chaosemer** [comment] 2020-10-08 18:11
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by chaosemer** 2020-10-08 18:11 UTC
Labels: bug
