### ISSUE TITLE
Android 10 Scanning Headsets Qr Codes not working

### ISSUE THREAD

**Issue by OleksandrPereverziev** [googlevr/cardboard#138] opened 2020-10-08 15:34 UTC
When in Cardboard mode we tap setting button to scan QR code 
Android 7, 8, 9 is scanning fine and almost instantaneously 
Android 10 **not showing anything** or showing **"QR Code is wrong"** (tested on 2 Android 10 devices)

**Comment by rajandeepsingh13** [comment] 2020-10-09 14:24
Works fine on my Poco F1 (Android 10)

**Comment by OleksandrPereverziev** [comment] 2020-10-10 09:43
> Works fine on my Poco F1 (Android 10)
Thanks for testing on your device 😊

We've experienced it on Samsung Galaxy S10 and Xiaomi mi note 8 (Android 10 also)

**Comment by jballoffet** [comment] 2020-10-27 13:28
Thanks for reporting this issue, @OleksandrPereverziev. We have added some changes related to the QR Code scanner in the [last release](https://github.com/googlevr/cardboard/releases/tag/v1.3.0), so I’d suggest that you should try to reproduce the issue again with the aforementioned version. If you’re still able to see the issue, please reach out to us again with the following information:

- Devices’ models where the error is exposed.
- Have you tried a custom QR Code? Would you please try with Cardboard Viewer V1 or V2 to verify the behaviour?
- Is the error shown when using the Hello Cardboard sample app?
- Are you using native Android or Unity? If the latter, please provide a repro project where the issue is shown and the steps required to repro it.

**Comment by jballoffet** [comment] 2021-06-09 15:11
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with the required details.

**Closed by jballoffet** 2021-06-09 15:11 UTC
Labels: bug
