### ISSUE TITLE
App failing to toggle between VR and standard 

### ISSUE THREAD

**Issue by lz7cjc** [googlevr/cardboard#231] opened 2021-03-22 14:29 UTC
Hi 
According to this issue: https://github.com/googlevr/cardboard/issues/98 this was resolved in an update to the package; "This was fixed in v1.3.0."
However I have the latest version  (3.2.16) and still getting the error when I go back to VR having been there before. 
Start in 2d - works
Switch to 3d- works
Back to 2d- works
Switch to 3d - doesn't work. The app will respond to the reticle pointer but you can't view in the headset and it is a single screen, not a split screen

I think this warning may have something to do with it but not sure how to resolve

Call to StartSubsystems without an initialized manager.Please make sure wait for initialization to complete before calling this API.
UnityEngine.XR.Management.XRManagerSettings:StartSubsystems()
<StartVR>d__1:MoveNext() (at Assets/MyStuff/Scripts/VRTogglestart.cs:19)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I am using 2019.4.0f1 since I need to use the old GVR reticle pointer as there is no easy replacement within the XR system. 

Is this still a known issue? Is there a fix? 
thanks

**Comment by amjadalth9** [comment] 2021-03-27 01:58
I have the same problem! Did anyone solve it?

**Comment by marcolbx** [comment] 2021-03-27 07:48
Same issue*

**Comment by jballoffet** [comment] 2021-04-28 18:28
Thanks for reaching out to us and sorry for the long delay here.

Based on the issue description it seems that you are using the GVR SDK, since the latest version of the Cardboard SDK is "v1.4.1" and currently it does not provide a reticle pointer. Please bear in mind that GVR and the old Cardboard SDK have been deprecated and this new version should be used instead.

About turning VR mode on and off, I'd recommend that you take a look at the sample scene, [VrMode],(https://developers.google.com/cardboard/develop/unity/quickstart#turning_vr_mode_on_and_off) for guidance about how to do it by using the Unity XR Plugin Management API. I also want to point out that I wasn't able to reproduce the reported issue with it.

Having said that, if you’re still having issues with the new SDK, please reach out to us again by reopening this issue, providing a repro project and the steps required to reproduce the issue.

**Comment by lz7cjc** [comment] 2021-04-29 06:23
I am using the XR plugin manager and need to toggle in code.
This is how i have set it up:

 IEnumerator StartVR()
    {
        var xrManager = XRGeneralSettings.Instance.Manager;
        if (!xrManager.isInitializationComplete)
         yield return xrManager.InitializeLoader();
        xrManager.StartSubsystems();
        Screen.sleepTimeout = SleepTimeout.NeverSleep;
        SceneManager.LoadScene("everything");
    }
 void StopXR()
    {
        var xrManager = XRGeneralSettings.Instance.Manager;
        if (!xrManager.isInitializationComplete)
            return; // Safety check
        xrManager.StopSubsystems();
        xrManager.DeinitializeLoader();
    }

It works fine the first time i..e non VR -> VR - >non VR but after that it won't toggle back into VR

**Comment by lz7cjc** [comment] 2021-04-29 06:25
not sure why you closed this before getting confirmation of resolution but please reopen since I can't see how to do this

**Comment by jballoffet** [comment] 2021-04-29 17:00
Sure thing. In order to be able to help you, we'll need a repro project and the steps required to reproduce the issue. Thanks!

**Comment by Mandelbrow** [comment] 2021-04-29 20:39
> SceneManager.LoadScene("everything");

Hi lz7cjc, are you sure your app work as expected if the same scene is loaded multiple times?

**Comment by lz7cjc** [comment] 2021-04-30 06:36
> 
> 
> > SceneManager.LoadScene("everything");
> 
> Hi lz7cjc, are you sure your app work as expected if the same scene is loaded multiple times?

I am sorry , I don't understand what you mean!

**Comment by lz7cjc** [comment] 2021-04-30 06:38
> 
> 
> not sure why you closed this before getting confirmation of resolution but please reopen since I can't see how to do this

**Comment by lz7cjc** [comment] 2021-04-30 06:49
You can find the project here: 
https://gitlab.com/lz7cjc/masterchange_unity
You can download the app on Google Play: https://play.google.com/store/apps/details?id=com.Beriro.Masterchange
After opening the app, choose to enter MasterChange (bottom right button). After the confirmation screen you will launch the VR. You will be in the training section. Skip this level and you will be in the main area. Choose the sign that says "dashboard" and you will return to the 2d screens. Launch MasterChange again and the app will either crash or freeze in 2d when you go back into the VR world

**Comment by lz7cjc** [comment] 2021-04-30 06:56
![InkedScreenshot_20210430-074228_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116658904-a2635f80-a988-11eb-8027-dca5447f26a4.jpg)
![InkedScreenshot_20210430-074428_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116658919-ab543100-a988-11eb-903e-7924da395cf5.jpg)
![InkedScreenshot_20210430-074456_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116659039-dcccfc80-a988-11eb-9ebd-763b55f32f54.jpg)
![InkedScreenshot_20210430-074504_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116659071-eb1b1880-a988-11eb-9df5-2e7bb077c0c9.jpg)
![InkedScreenshot_20210430-074520_Samsung Experience Home_LI](https://user-images.githubusercontent.com/8480055/116659090-f1a99000-a988-11eb-8190-85110b4ab6a9.jpg)

**Comment by lz7cjc** [comment] 2021-04-30 06:58
and these are the screens when you first enter VR, the training level, which you need to skip to get to the main area
![InkedScreenshot_20210430-075423_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116659568-b65b9100-a989-11eb-8b34-0bf6d540b3e3.jpg)
![InkedScreenshot_20210430-075448_MasterChange_LI](https://user-images.githubusercontent.com/8480055/116659605-c2dfe980-a989-11eb-8f58-cdec7f67d888.jpg)

**Comment by Mandelbrow** [comment] 2021-04-30 17:33
> > > SceneManager.LoadScene("everything");
> > 
> > 
> > Hi lz7cjc, are you sure your app work as expected if the same scene is loaded multiple times?
> 
> I am sorry , I don't understand what you mean!

This line in your code will run every time you start the Coroutine StartVR(). Are you sure that's what you want?

**Comment by lz7cjc** [comment] 2021-05-01 08:02
oh i see - thank you for explaining
I don't imagine it is best practice but it is the only way i could think to structure the app. There are a number of 2d scenes and one VR scene. So as I move between the two types I need to turn VR on/off

**Comment by lz7cjc** [comment] 2021-05-05 09:24
> 
> 
> Sure thing. In order to be able to help you, we'll need a repro project and the steps required to reproduce the issue. Thanks!

Hi 
all files and full description posted 5 days ago - when do you expect to have a response, for me? 
thanks
Nick

**Comment by Mandelbrow** [comment] 2021-05-06 04:21
Isn't it much easier for you to track down the problem in your own code? I have no problems loading, and unloading XR in Unity 2019, nor 2020. How about starting with some simple tests running the app in the Editor to see what happens when the scene "everything", or any scene are loaded multiple times? And if thats not the problem continue by trying to replicate the error in the DemoScene, or testing on other devices to see if its related to for example the Android version?

**Comment by lz7cjc** [comment] 2021-05-06 06:36
thanks but i have done all that which is why i have ended up here. I am flummoxed and was hoping for some help in working out what is going wrong.

**Comment by lz7cjc** [comment] 2021-05-08 10:48
still hoping for a resolution
this is where the story started: 
https://forum.unity.com/threads/toggle-between-2d-and-google-cardboard.902378/
as you can see I am not the only one to suffer from this problem so it would be great if you could let us know where we have goen wrong
It really doesn't help with you telling me that it works fine for you as it clearly isn't working for everyone. 
thanks

**Comment by lz7cjc** [comment] 2021-05-08 10:49
> 
> 
> Isn't it much easier for you to track down the problem in your own code? I have no problems loading, and unloading XR in Unity 2019, nor 2020. How about starting with some simple tests running the app in the Editor to see what happens when the scene "everything", or any scene are loaded multiple times? And if thats not the problem continue by trying to replicate the error in the DemoScene, or testing on other devices to see if its related to for example the Android version?

perhaps you could post the exact code you are using? this would be very helpful

**Comment by Mandelbrow** [comment] 2021-05-08 14:46
I'm using pretty much the same code you are, except for the loading of the scene "everything" every time VR is enabled.
I also call _Screen.sleepTimeout = SleepTimeout.NeverSleep;_ before the XR system is loaded, not sure if the order are important.

**Comment by lz7cjc** [comment] 2021-05-10 07:54
> 
> 
> Sure thing. In order to be able to help you, we'll need a repro project and the steps required to reproduce the issue. Thanks!

Hi - still waiting for you to help me out! What is your timeline for looking into this? 
thank

**Comment by jballoffet** [comment] 2021-05-10 14:47
@lz7cjc, it seems I don't have access to the provided repro project (https://gitlab.com/lz7cjc/masterchange_unity), since I'm getting a 404 page on GitLab. Would you be so kind as to check this please? It would be really helpful for debugging this issue. Thanks!

**Comment by lz7cjc** [comment] 2021-05-14 13:28
> 
> 
> @lz7cjc, it seems I don't have access to the provided repro project (https://gitlab.com/lz7cjc/masterchange_unity), since I'm getting a 404 page on GitLab. Would you be so kind as to check this please? It would be really helpful for debugging this issue. Thanks!

did you get access? 

I have also noticed something very weird that has started in the past week. See attached screenshot - I have two mini boxes about a cm squared top left and top right. 

![Screenshot_20210225-113920](https://user-images.githubusercontent.com/8480055/118277317-95825800-b4c0-11eb-8dee-a9f11bc34aa4.png)

**Comment by lz7cjc** [comment] 2021-05-31 14:38
@jballoffet getting less and less patient. is this the right place to get the fix sorted? how do i escalate? 
thanks

**Comment by jballoffet** [comment] 2021-05-31 15:11
Sorry for the delay here. I confirm I'm still getting a 404 page on GitLab (https://gitlab.com/lz7cjc/masterchange_unity). Is the repository public? If not, you'll need to either make it public or give me visibility to it (JIC, my GitLab user is jballoffet as well). Thanks!

**Comment by lz7cjc** [comment] 2021-06-01 13:31
@jballoffet hopefully you have received an invite
thanks

**Comment by lz7cjc** [comment] 2021-06-03 08:48
@jballoffet do you have access now? what is eta for taking a look? thanks

**Comment by jballoffet** [comment] 2021-06-08 18:48
Thanks, I confirm that I'm able to access the provided repository. Assuming that I should be taking a look at the master branch, I've found the following things:
- According to [here](https://gitlab.com/lz7cjc/masterchange_unity/-/blob/master/ProjectSettings/ProjectVersion.txt), the provided project uses Unity 2019.2.5f1. Please notice that [Unity 2019.3.15f1 or later](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment) is required.
- I have downloaded the project and AFAICS, the old GVR SDK is being used (since it is enabled on Project Settings > Player > XR Settings > Virtual Reality SDKs). This SDK is deprecated and should be removed in favor of the new Cardboard XR Plugin.
- In addition to the bullet above, I don't see the new Cardboard XR Plugin package being included [here](https://gitlab.com/lz7cjc/masterchange_unity/-/blob/master/Packages/manifest.json).

Please let me know in case I'm looking at the wrong location.

Please also bear in mind that the provided repro project is a very large one (more than 5GB in assets) and that prevents us from quickly iterate in order to find a solution and be helpful here (it took me several minutes just to change the target platform). It would be really useful to have a project as small and simple as possible in order to debug and solve the reported issue.

**Comment by lz7cjc** [comment] 2021-06-09 07:54
thanks for getting back to me. That is the wrong branch - the latest is ProductionReleases. This uses 2019.4. I can't go any higher since I need to be able to use GVRReticlePointer when testing in the editor but I use XR Plugin for the actual app builds. Once there is a way to test in Editor with the XR manager, I can upgrade and remove all the legacy stuff

To find the problem, it is pretty simple. Just open up the app, go to MasterChange, then choose Dashboard from the HomeZone (you will need to get past the training level first, for speed you can just skip)

When you try to go back into MasterChange, having gone into 2d you will see it either crashes, or else doesn't go to split screen.

The relevant files to look at are: 
Scenes: 
MainVR (VR)
dashboard (2d)

Scripts
VRToggleStart
VRToggleStop

I don't believe that you need to look at anything else in the repository unless of course these in turn have system dependencies that I am not aware of

thanks

**Comment by lz7cjc** [comment] 2021-06-15 10:07
turns out it was a very simple fix so not sure why this has been ongoing since March!
for anyone else finding they have the same problem the solution (from Unity Forums)

If you want to repeatedly start and stop the subsystem, don't call to

Deinitialize

. You should generally just initialize once and deinitialize once. Then just call to

StartSubsystems

or

StopSubsystems

as needed in your code when you need to stop or restart VR mode. 

this has fixed my problem

**Comment by jballoffet** [comment] 2021-06-15 12:28
Thanks @lz7cjc for sharing the details! I'm glad to know this is solved now. Nonetheless, I'm curious about why initialize and deinitialize should be called only once given that the Unity code snippet [here](https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/EndUser.html) adds them to the StartXR and StopXR methods. Would you be so kind as to share the Unity forums links so we can take a look at it and if needed, fix the VrMode scene in the sample?

**Comment by lz7cjc** [comment] 2021-06-16 08:10
exactly - that is where I took my code from
here is the link:
https://forum.unity.com/threads/iap-not-working-in-testflight.1112011/#post-7240421

**Comment by Layfully** [comment] 2021-06-16 19:29
@lz7cjc I think you gave us a wrong link, since this one is about in-app pucharses.

**Comment by lz7cjc** [comment] 2021-06-17 08:37
oops! 
https://forum.unity.com/threads/not-launching-in-split-screen-some-of-the-time.1073834/#post-7224103

**Comment by jballoffet** [comment] 2021-06-18 13:20
Thanks a lot @lz7cjc! We'll add this to our backlog to investigate and improve the documentation (and the VrMode sample scene if needed). I'm closing this issue since it's solved now. Thanks again!

**Closed by jballoffet** 2021-06-18 13:20 UTC
Labels: bug

**Comment by lz7cjc** [comment] 2021-06-19 09:36
sorry to be the bearer of bad news but commenting out deinitialise has a knock on effect in that some buttons used to switch scenes stop working when you return to 2d from VR.... not sure if this is something you can help with?

**Comment by jballoffet** [comment] 2021-06-25 16:04
Based on your comment, it seems to me that there's something wrong between the initialize/deinitialize lifecycle and some buttons on your 2D view, but I'm convinced that it's something strictly related to the Cardboard XR Plugin. I'll do some research to double check whether the initialize/deinitialize methods should be called or not when switching from 2D to 3D and vice versa and I'll come back here in case I find something useful. Thanks!

**Comment by lz7cjc** [comment] 2021-06-26 09:28
ok thanks - is it worth me sharing a link to the apk where it is happening? Source control is up to date and it is the "earnriros" screen which can be found under assets-mystuff-scenese-2d

**Comment by lz7cjc** [comment] 2021-06-27 10:14
so just to be clear, my choice is
1. don't deinitialize and  (some) buttons stop working in 2d
2. do deinitialize and app crashes when I go back into VR
Obviously both of those are showstoppers. I am not getting anything from Unity forums so really hoping you can work out what is going on! 
thanks
