### ISSUE TITLE
IOS14 Cardboard view is continues spinning.

### ISSUE THREAD

**Issue by Mianpatel** [googlevr/cardboard#305] opened 2021-10-22 11:38 UTC
IOS14 Cardboard view is continues spinning.
I have need video demo for working in VR 180 for IOS

**Comment by arilow** [comment] 2022-02-17 15:18
Thanks @Mianpatel for reaching out to us! Sorry for the long delay. 


Are you using Google VR SDK or Cardboard SDK (this repository)?


Please notice that Google VR SDK is deprecated and therefore we won’t be able to be of much help if that’s the one you are using.


If you are using the Cardboard SDK, in order to allow us to reproduce this issue, could you please provide:

- The required steps to expose the issue.
- The Cardboard SDK version being used.
- The Xcode version being used.
-  Are you using Unity? Which version?
- A video depicting the described behavior would also be very helpful.


Thanks!

**Comment by jballoffet** [comment] 2022-06-09 16:41
Closing this ticket given that Cardboard SDK (this repository) does not provide a Cardboard View (this seems to be an issue related to the currently deprecated Google VR SDK). In case you are still having this issue (using the Cardboard SDK), please feel free to reopen this ticket and point us to a repro project with steps to reproduce. Thanks!

**Closed by jballoffet** 2022-06-09 16:41 UTC
Labels: bug
