### ISSUE TITLE
Black Screen in VR mode on older phone

### ISSUE THREAD

**Issue by mattwcook** [googlevr/cardboard#388] opened 2022-12-10 22:44 UTC
The Cardboard SDK is working perfectly for me on most of the phones I'm testing on, except on one specific phone type I'm getting a black screen. That black screen is in VR mode, it has the split screen with the white line down the middle. Building to this device works and renders perfectly if I remove the Tracked Pose Driver Script from the camera, but as soon as I add it back in, I get that split black screen again. I am testing in blank projects with only the SDK in them so there are no other possible variables. I also get error messages telling me

I ran my build using the android logcat tool and I am getting the following critical error, it seems like every frame: "Error CardboardSDK GL error OpenGlEs2DistortionRenderer::RenderDistortionMesh: 1280". I believe this error is what's causing things not to render, I do not get it on other devices. In my non-blank test project, I also get error messages on the device on open saying "Your device does not match the hardware requirements for this application." I do not know what hardware requirement specifically is the issue.

To me this suggests OpenGLES2 is the issue. I've tried removing it, but this particular device requires it, and I get an immediate error when trying to build to the device without it. OpenGLES3 and Vulkan appear to be incompatible. My original project uses Unity 2021.3.9f1, in which I see OpenGLES2 is marked Deprecated. I tried in another project using Unity 2020.3.36f1, before GLES2 was deprecated, and it still didn't work

The device that is failing is the Infinix HOT 6. It is running XOS version 3.3.0 and Android Version 8.1.0
It is successfully running on an Infinix HOT S and a Samsung Galaxy A50.

On the HOT 6, I downloaded random other cardboard apps from the app store and they worked fine, so the device is clearly capable of running VR. I also installed an APK of a different project that uses the old Google VR SDK and ran on Unity 2019.2.21f1 and it also worked. I don't know what differences there might be between the Google VR SDK and the Cardboard SDK that would cause one to work on this device and not the other.

Other things I have tried:

- Removing Vulkan Graphics API 
- Checking Auto Graphics API
- Moving OpenGLES2 to the top of the Graphics API list
- Technically I did NOT change the Color Space from Gamma to Linear (this required removing GLES2 which of course did not work because the device requires GLES2)
- Unchecked Multithreaded Rendering
- Changed to the Mono Scripting Backend
- I tried disabling the ARMv7 or the ARM64 Target Architectures but one is required by IL2CPP and the other is required by the device.

I'm very lost and confused and am running out of things I can try. It is very important for my project that I get this to work on the HOT 6 so I can't just give up on it. This project is meant to be deployed in low resource regions of Africa and we want it to work on as many older phones as we possibly can anyway.
Can someone please help me make this work? 
Thank you

**Comment by arilow** [comment] 2022-12-21 14:10
Thanks @mattwcook for reaching out to us, and sorry for the delay!


Unfortunately, we are not able to reproduce the issue you are mentioning on our side. So we will need your help to debug this. 


As you mentioned, this seems to be an issue related to OpenGL 2. 1280 in decimal is equal to 0x0500 (hexadecimal). [Here](https://www.khronos.org/opengl/wiki/OpenGL_Error) you can see the meaning of the GL errors: 0x0500 is `GL_INVALID_ENUM`. Which is not telling us much yet, but it should help us find the bug.


You can find which enum is causing the error by using [renderdoc](https://renderdoc.org/). This link might also help: https://learnopengl.com/in-practice/debugging 


There are some tests that I would ask you to do:
- Test the Hello Cardboard Sample scene with OpenGL 2 on the device where you are having issues. Do you get the same black screen? What about the logs?
  - Instructions: [Quickstart for Unity](https://developers.google.com/cardboard/develop/unity/quickstart)
- Test the native sample App for Android. It is using OpenGL 2. If you can reproduce this same issue with this app we can be sure that it is not related to Unity. Also it would be easier to debug.
  - Instructions: [Quickstart for Android NDK](https://developers.google.com/cardboard/develop/c/quickstart)


Some additional information: The log "Error CardboardSDK GL error OpenGlEs2DistortionRenderer::RenderDistortionMesh: 1280" comes from this line in the SDK: https://github.com/googlevr/cardboard/blob/master/sdk/rendering/opengl_es2_distortion_renderer.cc#L284 


It might take us some time, but I hope we can find a solution together. Feel free to ask as many questions as you need in order to get this fixed.


Thanks!

**Comment by arilow** [comment] 2023-04-18 18:19
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:19 UTC
