### ISSUE TITLE
What is the minimum android version required for hellocardboard to work?

### ISSUE THREAD

**Issue by jharan55** [googlevr/cardboard#332] opened 2022-02-04 23:42 UTC
I've been trying to get the hellocardboard app to build and work on my old Samsung Galaxy S4 running Android 4.4.2. Initially the app would not install on my phone with this warning message from Android Studio:

```
Warning

minSdk(API 24) > deviceSdk(API 19) on device samsung
SAMSUNG-SGH-I337Z
```

The build.gradle files contained this comment block:

```
        // #gles3 #vulkan - You can reduce minSdkVersion down to 16 depending
        // on rendering APIs supported:
        //
        // OpenGL ES 2.0 - Requires 16 or higher
        // OpenGL ES 3.0 - Requires 18 or higher
        // Vulkan        - Requires 24 or higher
        //
        // See the release notes for details.
        minSdkVersion 24
```
So given that my old S4 is at API level 19 I modified minSdkVersion to 18 and rebuilt hellocardboard. After that I was able to successfully download the hellocardboard that I built to my S4. I now see "Hello Cardboard" application in the Apps page of my S4.

Now the problems are when I run it. When I run it I get the expected side by side windows and there are graphic images being displayed in them that look much like the pictures shown in the quickstart documentation, but instead of seeing steady images that move when I move the phone, what I see is basic shapes in pastel colors flashing randomly around the screen at high speed. It's as if the viewer position and orientation is changing rapidly on each screen refresh.

When I click the Settings icon in the upper right corner and click "Switch Cardboard Viewer", the camera activates and I get a window saying "Find this Cardboard symbol on your viewer" and I can pan the phone around until I actually get the QR code in the viewer at which point the app stops with a "Unfortunately, Hello Cardboard has stopped.  OK".

Note that the cardboard viewer I bought, a Shinecon G10, did not include a printed qr code in its packaging, but I found their QR code doing a search on my new phone. Its the bringing of the image of that QR code on my new phone into view on the S4 that causes hellocardboard to stop.

I've written an application using Opengl and GLFW that runs fine on my Lenovo Laptop running Ubuntu 20.04 (native GL code, no Unity or Unreal engine). I'd like to get it ported to run on cardboard so I figured that the best way to get there is to start with something that works like this demo app. It seems that others are successful at getting the stock hellocardboard to work on their phones, so perhaps my Galaxy S4 is just too old to expect success, despite the claims in the documentation and the gradle files. I'd rather avoid buying a brand new Android phone just for this porting effort, so I'm trying to figure out what kind of used Android phone I should get in order to get stock hellocardboard to function properly as a known starting point.

So if you've gotten hellocardboard to run successfully on your Android phone, what version of Android was it running?

Thanks

**Comment by Warwlock** [comment] 2022-02-05 09:57
I'm using Samsun Galaxy J7 Pro. First android version was 7.0 (API 24). After some updates latest supported android version 9.0 (API 28). 
I don't know how did you do that but in Unity version 2021.2.8 you can't select less than Android 5.1 (API 22).
Also in the [documentation](https://developers.google.com/cardboard/develop/unity/quickstart#other_settings) says `Select Minimum API level Android 7.0 (API 24) or Higher`. So opening a vr app in your device should be a miracle.

**Comment by jharan55** [comment] 2022-02-05 19:49
Thanks for replying.

The hellocardboard application is part of the native development kit (Android NDK), not Unity. The documentation I'm referring to is at:

https://developers.google.com/cardboard/develop/c/quickstart

and states:

> Hardware requirements:
> 
>     Android device running Android 4.4 "KitKat" (API level 16) or higher

My old S4 runs Android 4.4.2 and API level 19 so hellocardboard should work on it. The doc says 16 is ok, the unmodified code requires 24 but has comments about reducing it. When I did that it installs but does not appear to function correctly. I'm not sure which is wrong, the documentation or the code. That would depend on the intent of the maintainers, I suppose.

Just to make sure I'm understanding you, are you saying you ran the hellocardboard app on your Android 7.0, API 24 phone and it worked correctly at the time?

**Comment by arilow** [comment] 2022-04-12 12:23
Thanks for reaching out to us @jharan55! And sorry for the long delay. Let me split the reply into 3 sections:

### Downgrade minSdkVersion

As the comment you shared says, you can reduce the minSdkVersion down to 16 depending on the rendering APIs supported if you change the Gradle scripts here:
- Hello Cardboard [build.gradle](https://github.com/googlevr/cardboard/blob/cc8b826e9ac66e6a0fc5d52fb57a62293d1b3d77/hellocardboard-android/build.gradle#L18).
- Cardboard SDK [build.gradle](https://github.com/googlevr/cardboard/blob/cc8b826e9ac66e6a0fc5d52fb57a62293d1b3d77/sdk/build.gradle#L18).


If you want to downgrade the minSdkVersion to 19, you'll need to remove all the Vulkan-related lines from the CMake script:
- [rendering_vulkan_srcs](https://github.com/googlevr/cardboard/blob/master/sdk/CMakeLists.txt#L82)
- [rendering_vulkan_wrapper_srcs](https://github.com/googlevr/cardboard/blob/master/sdk/CMakeLists.txt#L83)
- [add_definitions](https://github.com/googlevr/cardboard/blob/master/sdk/CMakeLists.txt#L97)
- [dl](https://github.com/googlevr/cardboard/blob/master/sdk/CMakeLists.txt#L110)

### Head tracking issue

The bug you mentioned about “shapes flashing randomly around the screen at high speed” is pretty similar to #302. If you take a look at [this comment](https://github.com/googlevr/cardboard/issues/302#issuecomment-1043064596), you may find a workaround for that.

### Tested devices.

About your last question, in the [release notes](https://github.com/googlevr/cardboard/releases), you can find a list with the devices used to test each version of the SDK.

I'm closing this issue as it is a duplicate of #302. Please feel free to leave comments on that issue if needed.

Thanks!

**Closed by arilow** 2022-04-12 12:23 UTC
Labels: duplicate
