### ISSUE TITLE
'Exit button' and 'Settings gear' Blacked out and unresponsive after changing scenes

### ISSUE THREAD

**Issue by JacobBWaggoner** [googlevr/cardboard#50] opened 2020-05-28 20:51 UTC
We're running into an issue with the new system in which the built in Cardboard UI turns black after switching scenes, and the buttons become unresponsive. All steps from the starter guide were followed. All other elements of the system seem to be working aside from this.

**Comment by hawkwood** [comment] 2020-05-29 20:48
Here too.  Unity 2019.3.13, Android 8.1.  For me, I am delaying enabling VR by unchecking "Initialize XR on startup" then calling 
`
yield return XRGeneralSettings.Instance.Manager.InitializeLoader();
XRGeneralSettings.Instance.Manager.StartSubsystems();
`
To enter VR. The first time I do, the back and gear buttons are actually showing the content of one of the eyes (and are non-functional), when I leave that scene (and VR) then return, the buttons are not visible at all.

**Comment by CedoSnr** [comment] 2020-06-09 13:27
> Here too. Unity 2019.3.13, Android 8.1. For me, I am delaying enabling VR by unchecking "Initialize XR on startup" then calling
> `yield return XRGeneralSettings.Instance.Manager.InitializeLoader(); XRGeneralSettings.Instance.Manager.StartSubsystems();`
> To enter VR. The first time I do, the back and gear buttons are actually showing the content of one of the eyes (and are non-functional), when I leave that scene (and VR) then return, the buttons are not visible at all.

Use the script provided in the hellocardboard included with the plugin. I think it's called something like 'initialise VR'

**Comment by friggasaint** [comment] 2020-06-09 20:47
> > Here too. Unity 2019.3.13, Android 8.1. For me, I am delaying enabling VR by unchecking "Initialize XR on startup" then calling
> > `yield return XRGeneralSettings.Instance.Manager.InitializeLoader(); XRGeneralSettings.Instance.Manager.StartSubsystems();`
> > To enter VR. The first time I do, the back and gear buttons are actually showing the content of one of the eyes (and are non-functional), when I leave that scene (and VR) then return, the buttons are not visible at all.
> 
> Use the script provided in the hellocardboard project included with the plugin. I think it's called something like 'initialise VR'

This somehow helped me. Name of the script in the package is "CardboardStartUp".
Buttons still black out on scene change though but are responsive.

**Comment by npig** [comment] 2020-06-10 07:34
I'm having an issue with the buttons being unresponsive. Upgraded from old SDK, using Unity 2019.3.15. Magicwindow application, using this sequence to initialise.

                Screen.orientation = ScreenOrientation.LandscapeLeft;
                XRGeneralSettings.Instance.Manager.InitializeLoaderSync();
                XRGeneralSettings.Instance.Manager.StartSubsystems();

**Comment by CedoSnr** [comment] 2020-06-10 08:52
> > > Here too. Unity 2019.3.13, Android 8.1. For me, I am delaying enabling VR by unchecking "Initialize XR on startup" then calling
> > > `yield return XRGeneralSettings.Instance.Manager.InitializeLoader(); XRGeneralSettings.Instance.Manager.StartSubsystems();`
> > > To enter VR. The first time I do, the back and gear buttons are actually showing the content of one of the eyes (and are non-functional), when I leave that scene (and VR) then return, the buttons are not visible at all.
> > 
> > 
> > Use the script provided in the hellocardboard project included with the plugin. I think it's called something like 'initialise VR'
> 
> This somehow helped me. Name of the script in the package is "CardboardStartUp".
> Buttons still black out on scene change though but are responsive.

Yes, that's the one.

Are the buttons still blacked out if you run this again when you change scenes?

**Comment by npig** [comment] 2020-06-11 00:32
Having the same problem, using Google.XR.Cardboard for the cardboard buttons - worked the first time - on restarting the subsystem buttons are unresponsive.

**Comment by JacobBWaggoner** [comment] 2020-06-18 14:49
Following the steps outlined throughout this chain, I was able to get the buttons to be responsive, but they are blacked out. I'm experimenting to see if I can bring them back.

**Comment by jballoffet** [comment] 2020-06-22 13:42
I’m not able to reproduce this issue as HelloCardboard sample project currently doesn’t have multiple scenes. Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide the required steps to expose the issue.

**Comment by JacobBWaggoner** [comment] 2020-06-22 16:07
Hey @jballoffet here is a link to a repo I just made with a very basic test project. The same behavior is being demonstrated here as is on my main project. It's a very basic project with the plugin imported and the HelloCardboard scene modified to let you switch back and forth between 2 scenes.
https://github.com/JacobBWaggoner/GoogleCardboardUnityDebugging
I have been testing on a Pixel 2, project is built with Unity 2019.3.12f1

**Comment by JacobBWaggoner** [comment] 2020-06-22 16:08
The issue can be reproduced by switching scenes while in Cardboard, there is text in the scene that should walk you through it.

**Comment by JacobBWaggoner** [comment] 2020-07-23 18:01
@jballoffet Is there any news on a fix for this one? The release of our apps has been delayed for 2 months due to the issues on iOS, and we have the app ready to go aside from this issue. I know you get a lot of requests on here, but we'd definitely like to know a timeline if there is one!

**Comment by hawkwood** [comment] 2020-07-23 18:27
Not to denigrate the work these devs are doing, but I've moved to https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK for projects.

**Comment by jballoffet** [comment] 2020-09-15 14:30
@JacobBWaggoner, we are sorry for the slow response with this ticket. This task has been prioritised and we are currently working on it. I want to thank you for the sample project and let you know that it has been helpful, we can reproduce the bug with it. Hopefully we will get it solved for next release.

**Comment by JoaoBorks** [comment] 2020-10-01 17:06
@jballoffet do you have an ETA for the next release and maybe a public roadmap? I just discovered this same issue today

**Comment by jballoffet** [comment] 2020-10-01 17:30
A fix for this has been submitted and it will be included in the next release (to be released very soon, currently working through the QA process). Thank you for your patience.

**Comment by chaosemer** [comment] 2020-10-20 21:49
This was fixed in v1.3.0.

**Closed by chaosemer** 2020-10-20 21:49 UTC
Labels: bug, fixed in upcoming release
