### ISSUE TITLE
The Unity sample (HelloCardboard) works in Unity but is not in stereo

### ISSUE THREAD

**Issue by LukeFarrer** [googlevr/cardboard#128] opened 2020-10-04 17:10 UTC
The page

https://developers.google.com/cardboard/develop/unity/quickstart

describes how to build the basic HelloCardboard example. It also says the app shows you how to "Render stereoscopic images by setting the correct distortion for each eye". Where?

When building it in Unity 2019.4.11f1 everything works with one exception: exactly the same image is rendered in both the left and right eyes. So there is no stereo. See the attached screenshot.

![Screenshot_20201004-130702](https://user-images.githubusercontent.com/67607471/95022042-a4f41580-0642-11eb-8c6c-f79fc7843808.png)

What needs to be done to create a stereo view?

Note that the equivalent page for building for the Android NDK (https://developers.google.com/cardboard/develop/c/quickstart) shows different images being rendered for each eye and therefore a stereo result.

Is this a bug?

Luke

**Comment by rajandeepsingh13** [comment] 2020-10-09 14:20
Yeah facing the same issue. It'll be really nice to see this fixed!

**Comment by LukeFarrer** [comment] 2020-10-26 14:19
Is this issue a bug? Do you have any idea how it might be solved or is there a workaround in the meantime?

**Comment by DaniMateD** [comment] 2020-11-06 20:48
I'm having the same issue with any scene published on Android. **Stereo rendering** is supposed to be a **must have feature** on the plugin... Maybe there is a setting to toggle it on, however I haven't found it :/

Can anybody shed some light on this issue please?

Thanks!

**Comment by DaniMateD** [comment] 2020-11-07 08:51
After some testing I can confirm that this issue is caused by the parameters of the default cardboard device. If you scan the QR code of any viewer, stereo starts displaying, since the stereo separation is contained in this settings.

From my point of view, this is still an issue, since **the default viewer should contain some stereo separation and convergence to properly display stereo rendering by default**.

Hope this helps somebody!

@jballoffet @LukeFarrer @rajandeepsingh13

**Comment by LukeFarrer** [comment] 2020-11-12 19:46
I tried scanning the QR code while the app was running but the view remained mono. I restarted the app several times after scanning the Google cardboard QR code but to no avail.

**Comment by jballoffet** [comment] 2020-12-02 14:35
This seems to be intended behaviour for the default parameters (Cardboard Viewer v1). Due to its physical specs, the distortion seems not to be stereo with a naked eye, but it is the appropriate one for the v1 viewer. The reason why the image shown in the [Android quickstart](https://developers.google.com/cardboard/develop/c/quickstart) is different from the provided one is because Cardboard Viewer v2 parameters were being used when those screenshots were taken. Find also below the same sample app but using the old GVR SDK and you'll see the same behaviour taking place in it.

Cardboard Viewer v1
![pic1](https://user-images.githubusercontent.com/20689187/100885955-fdecf800-3491-11eb-81a0-0bf4b8aff208.jpg)
Cardboard Viewer v2
![pic2](https://user-images.githubusercontent.com/20689187/100885981-06ddc980-3492-11eb-9bef-7d4937626725.jpg)

Furthermore, you could modify the default parameters in [CardboardV1DeviceParams.java](https://github.com/googlevr/cardboard/blob/master/sdk/device_params/android/java/com/google/cardboard/sdk/deviceparams/CardboardV1DeviceParams.java) and you'll see that the default distortion changes accordingly.
I’m closing this issue as it is intended behaviour.

**Closed** 2020-12-02 14:35 UTC
Labels: bug
