### ISSUE TITLE
Cardboard SDK .meta files in .ipa cause code signing issue

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/cardboard#257] opened 2021-05-02 17:09 UTC
In our release pipeline, we generate our .ipa file using Unity cloud, and then re-sign and upload using [iOS Project builder](https://assetstore.unity.com/packages/tools/utilities/ios-project-builder-for-windows-15522). However 2 meta files (`qrSample.png.meta` and `tickmarks.png.meta`) make their way into .ipa file and prevent re-signing in our release pipeline.

The error presented by iOS Project Builder is:
_CRITICAL WARNING: .meta files are present in this bundle. These files cause code signatures to be rejected. In order to produce a valid signature, please delete the following files from your bundle before signing_

Manually opening .ipa archive with 7zip and deleting these 2 .meta files solve the problem.

Setup:
Unity 2019.4.15f1
Google Cardboard XR plugin v1.4.1
Xcode 12.4.0 (determined by cloud builder)
iOS project builder v3.34 (Only _itcuploader_ tool is used)

![image](https://user-images.githubusercontent.com/19275187/116821027-ba053880-ab80-11eb-9445-6cee79cfc4c6.png)

**Comment by jballoffet** [comment] 2021-05-10 12:03
Thanks @guneyozsan for reaching out to us! I confirm that I'm able to see the .meta files in the generated Xcode project (only .meta files that seem to make their way through Unity's project build). We'll investigate this to figure out what the issue is and find a way to prevent those files from being added to the Xcode project. In the meantime, I guess you could write a simple script that removed them in the appropriate pipeline stage.

**Comment by guneyozsan** [comment] 2021-05-10 16:10
Thank you @jballoffet , this is how we deal with it for now.

**Comment by jballoffet** [comment] 2021-09-09 16:29
@guneyozsan, I've got some updates related to this issue. It seems it's been detected by Unity, but the issue needs to be voted in order to get it prioritized. It would be great if you could vote for it here: https://issuetracker.unity3d.com/issues/possibly-ios-unity-meta-files-are-generated-in-the-plugin-directory-and-then-copied-to-plugins-directory-in-the-xcode-build.

Thanks!

**Comment by jballoffet** [comment] 2021-11-30 18:19
Thanks @guneyozsan !

**Comment by xinyunh0929** [comment] 2021-11-30 23:37
This was fixed in v1.10.0

**Closed by xinyunh0929** 2021-11-30 23:37 UTC
Labels: known issue, fixed in upcoming release
