### ISSUE TITLE
No preview in editor ?

### ISSUE THREAD

**Issue by DaReign** [googlevr/cardboard#407] opened 2023-05-14 15:44 UTC
In editor I can't get preview. 
![image](https://github.com/googlevr/cardboard/assets/11806754/649be118-05e5-4f2b-9be9-fd357186d1c8)

If it is feature not bug :) then I would ask to add preview :) like in depreciated https://github.com/googlevr/gvr-unity-sdk/releases

Well this preview is really helpful in development so I am suprised that so basic functionality is missing :)

**Comment by arilow** [comment] 2023-05-15 14:04
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of #51. Please feel free to leave comments on that issue if needed.

**Closed by arilow** 2023-05-15 14:04 UTC
Labels: duplicate, feature request
