### ISSUE TITLE
Issue on ios14.2 device

### ISSUE THREAD

**Issue by prabhukumardasari12** [googlevr/cardboard#185] opened 2020-12-23 11:30 UTC
I am using unity 2019.4 and latest cardboard sdk. The objects in the right screen are not rendering properly(disappearing) in ios 14.2. The same thing is working properly in all the versions below 14.2 version.

Attached screenshot for reference. 
<img width="305" alt="ios14 2" src="https://user-images.githubusercontent.com/49179148/102991940-4606b400-4540-11eb-9088-84b00f3686cd.png">

**Comment by CreaProjects** [comment] 2020-12-23 14:25
Same here, I have disappearing objects too. A shader issue perhaps? It only happens when the Google Cardboard SDK is ON. If it's off, everything is rendered correctly.

**Comment by prabhukumardasari12** [comment] 2020-12-23 15:27
> Same here, I have disappearing objects too. A shader issue perhaps? It only happens when the Google Cardboard SDK is ON. If it's off, everything is rendered correctly.

Actually my 3d objects are also disappearing. The white color is the camera color. Did you find any solution or do we need to wait for the new sdk?

**Comment by CreaProjects** [comment] 2020-12-23 17:19
I just found this issue, no solutions found yet.

**Comment by jballoffet** [comment] 2021-01-05 18:34
Thanks for reporting this issue. Does the issue show up when using Hello Cardboard sample scene? If not, could you please share a simple repro project with us where the issue is shown and the steps required to reproduce it?

**Comment by prabhukumardasari12** [comment] 2021-01-07 04:11
Yes. This issue is also in the Hello Cardboard sample.

**Comment by jballoffet** [comment] 2021-01-22 20:43
Closing this issue as it seems to be a duplicate of #54. If that's not the case, please reopen this ticket providing a screen record where the issue is depicted.

**Closed** 2021-01-22 20:43 UTC
Labels: duplicate
