### ISSUE TITLE
How to integrate in an existant iOS Xcode - CocoaPods Project?

### ISSUE THREAD

**Issue by Neogene** [googlevr/cardboard#432] opened 2023-09-20 15:40 UTC
The tutorial page teaches only how to download and use the tutorial project, but what are the steps to configure a preexistent cocoa pods (and project too) of a new/old project to use the new googlevr lib? 

We are migrating from the old GVRSDK pod.

Any help will be appreciated.

**Comment by arilow** [comment] 2023-09-25 14:23
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of [#349](https://github.com/googlevr/cardboard/issues/349) . Please feel free to leave comments on that issue if needed.

**Closed by arilow** 2023-09-25 14:23 UTC
Labels: bug
