### ISSUE TITLE
On Android magenta flashses appear when loading scenes and the screen stays magenta after loading is done

### ISSUE THREAD

**Issue by ChaosAlfa** [googlevr/cardboard#167] opened 2020-11-25 00:15 UTC
When switching scenes we use a custom loading system. On iOS the system works without issue, but when loading on Android the screen flashes magenta and stays magenta after the process is done.

With the old Google Cardboard SDK we didn't have this problem, but because iOS 14 dropped support for the old SDK we were forced to upgrade.

I've more or less recreated the bugs in the Cardboard Sample project and included the project with this issue. I wasn't able to make the screen stay magenta the same way it happens in our game, but I did include a recreation of the loading scene in the project.

[Magenta Bug Project.zip](https://github.com/googlevr/cardboard/files/5593464/Magenta.Bug.Project.zip)
To load a scene and get the bug, the cog button or cross button can be pressed. The cog buttons loads the sample scene and the cross button loads a bare bones version of the loading scene from our game.

It would be greatly appreciated if this bug could get fixed and/or if we could get feedback on what the cause of the problem is and how to fix it.

**Comment by jballoffet** [comment] 2020-11-30 20:41
Thank you for reporting this issue and providing a repro project. I confirm I'm able to repro it locally. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by arilow** [comment] 2021-06-21 18:26
Hi @ChaosAlfa! Sorry for the long delay here. 

We have been reviewing your app. This is what we’ve found so far:

- First of all we built and ran the project with Unity 2019.4.25f1
- Effectively, the app starts with both eyes in red:

<img src="https://user-images.githubusercontent.com/43258762/122418916-f1794a00-cf60-11eb-8018-1c2533ce49bd.jpg" width="200" height="90">

- After touching the gear button the first time, we got the normal image:

<img src="https://user-images.githubusercontent.com/43258762/122420226-e377f900-cf61-11eb-9e4f-1d23e1a176cd.jpg" width="200" height="90">

- And after touching it for the second time, the magenta flashes start:

<img src="https://user-images.githubusercontent.com/43258762/122420672-3baefb00-cf62-11eb-9524-3ed0841d5ed1.jpg" width="200" height="90">

- These flashes are intensified every time the button is touched.

- One detail to have in mind: If you touch the object between flashes, it disappears (as expected). But it appears again after the next magenta flash. This makes me think that maybe these flashes are caused by the rendering being (not properly) restarted.

Once we’ve finished the behavioral testing, we took a look at the code. Given the current complexity of the provided source code and the fact that it uses a custom scene loader, we’ll need your help to continue debugging this. This is what we were able to do so far:

- We started at `CardboardStartup.cs` where the `update()` method is called. 

-  Given that the issue was shown when pressing the gear button, we started debugging from here:
```
        if (Api.IsGearButtonPressed)
        {   
            stageManager.LoadStage(nextStage);
            //SceneManager.LoadScene(nextStageName);
        }
```
Where only `stageManager.LoadStage(nextStage)` is being called (since SceneManager.LoadScene(nextStageName) was already commented out).

- Commenting some lines out and adding a couple of logs, we came to the conclusion that the magenta flashes seems to be caused by these lines inside `HandleStage()`:
```
		loadingStage = TransitStage(stage);
		yield return loadingStage;
```
We can not be completely sure about this, because if we comment those lines out, the app just shows a black screen when you touch the gear button. 

- We kept digging in `TransitStage(stage)` which took us to the `StartStage()` in the `SimpleStage` class and then to the `public 
StartStageResult(AsyncOperation[] operations)` constructor. It would be great If you could lend us a hand continuing debugging from here.

We would really appreciate some help here to finish sorting this out. Furthermore, if by any chance there were a way to simplify the provided project, that would also be really helpful for us in order to continue debugging it. Thanks!

**Comment by ChaosAlfa** [comment] 2021-06-28 09:30
I've been very busy, but I should be able to look into this somewhere this
week

**Comment by ChaosAlfa** [comment] 2021-07-22 21:04
The scene load system has been created by a previous company who worked on
the project
I don't completely understand how the system works and can't find what is
responsible for the bug

I've recreated the system in the example project with the minimal amount of
code possible.
If anything more gets removed it stops working.

I will try to get in contact with the developers who created it to see if
they can help

**Comment by jballoffet** [comment] 2021-07-26 15:27
Sounds good, thanks for the heads up!

**Comment by jballoffet** [comment] 2022-06-09 14:21
Closing this ticket, please retry using release v1.15.0 and reopen this issue if the error persists. Thanks!

**Closed by jballoffet** 2022-06-09 14:21 UTC
Labels: bug
