### ISSUE TITLE
Reflection render error on Android mobile phone

### ISSUE THREAD

**Issue by ChenYiyangSJTU** [googlevr/cardboard#346] opened 2022-04-25 02:41 UTC
When using built-in reflection probes in cardboard VR, error occurs: When you turn your head left and right, the reflection shifts around the bottom of the object across an unusually large area, and when you tilt your head to left/right, the reflection UV  seems to break up in the edge.

**Comment by arilow** [comment] 2022-05-04 14:25
Thanks for reporting this issue. in order to allow us to reproduce this issue, could you please provide:
- The required steps to expose the issue.
- The Cardboard XR Plugin version being used.
- Unity version.
- OpenGL version.
- A simple Unity project where this issue is depicted would also be very helpful.

Thanks!

**Comment by arilow** [comment] 2023-04-18 18:23
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:23 UTC
Labels: bug
