### ISSUE TITLE
Build failing for iOS with header file not found error

### ISSUE THREAD

**Issue by Steve-0628** [googlevr/cardboard#303] opened 2021-10-21 12:11 UTC
Xcode tells me that some header files can't be found. I once fixed it on #294 but it wont build now. 
I looked around header paths for a while but I couldn't manage to fix it. 
![image](https://user-images.githubusercontent.com/49326405/138273737-3fed81c4-3117-4e32-86dd-696580a4b757.png)

**Comment by arilow** [comment] 2022-03-04 19:16
Thanks @Steve-0628 for your response and sorry for the long delay here. I tried to reproduce the error by following the steps you described and I couldn’t.


The error in the image you shared states that those header files cannot be found by Xcode. Are you able to see them in your project?
Let me share their path with you:
- [`cardboard_v1.h`](https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/cardboard_v1/cardboard_v1.h)
- [`vectorutils.h`](https://github.com/googlevr/cardboard/blob/master/sdk/util/vectorutils.h)


Furthermore, in order to allow us to reproduce this issue, could you please provide a link to a simple Xcode project where this issue is shown? (it's ok if it's just an Xcode project with the HelloCardboard sample). That would help us to pinpoint the issue and find a way to fix it.


Thanks!

**Comment by arilow** [comment] 2023-04-18 18:24
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:24 UTC
Labels: bug
