### ISSUE TITLE
Bluetooth Controller not working.

### ISSUE THREAD

**Issue by abssuper20** [googlevr/cardboard#348] opened 2022-05-05 09:45 UTC
Issue is pretty self explanatory. I can't use my bluetooth controller in the build. When I make a standard non VR build of the same then the controller works fine.

**Comment by abssuper20** [comment] 2022-08-02 10:03
This is running in Unity 2020.3.25 for android. Carboard version v.1.15.0

**Comment by arilow** [comment] 2022-08-03 21:09
Thanks for your answer @abssuper20.

Were you able to make the bluetooth controller work with another VR plugin? 
That information would allow us to confirm that this is an issue in the Cardboard XR Plugin instead of an issue related to any XR Plugin on Unity.

On the other hand, which bluetooth controller are you trying to use?

**Comment by Mandelbrow** [comment] 2022-08-16 16:55
Are you sure it's the bluetooth controller that stops working, and not what you are trying to do with the input from the controller? If you for example are using the input to control the camera rotation, and/or position then it may work fine without VR. But in VR all of that is controlled by the gyro, and your headset position, and that maybe makes you believe the controller is broken.

**Comment by jballoffet** [comment] 2023-04-17 13:00
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by jballoffet** 2023-04-17 13:00 UTC
