### ISSUE TITLE
Camera drifts after enabeling VR on Android

### ISSUE THREAD

**Issue by ChaosAlfa** [googlevr/cardboard#169] opened 2020-11-29 21:12 UTC
After having manually enabled the Cardboard SDK in the app the camera starts drifting. It takes a few seconds before it stops and sometimes it doesn't stop. This only happens on Android and not on iOS. I assume this is a SDK problem, because this didn't happen when we used the GVR Cardboard SDK.

I have recreated the bug in a the sample project.
[Camera Drifting Bug.zip](https://github.com/googlevr/cardboard/files/5612860/Camera.Drifting.Bug.zip)
To enable VR tap the screen once.

It would be greatly appreciated if this bug could get fixed and/or if we could get feedback on what the cause of the problem is and how to fix it.

**Comment by jballoffet** [comment] 2020-12-01 13:05
Thank you for reporting this issue and providing a repro project. However, I cannot reproduce the issue locally, running the app and placing the phone on a table. I'd appreciate it if you could record a video where the issue is shown on a device placed on a table (to avoid the holding jittering). I'd also appreciate it if you could test it on a different Android phone and provide more information about on what devices the issue takes place.

**Comment by ChaosAlfa** [comment] 2020-12-02 19:42
I have tried to reproduce the bug on 3 different phones while having the phone placed on a table. The bug doesn't occur anymore. It could be that while holding the phone the weight of it made us unconsciously move it. 

Thanks for looking into it, the issue can be closed now.

**Comment by jballoffet** [comment] 2020-12-02 19:55
Thanks for the confirmation. Closing the issue now.

**Closed by jballoffet** 2020-12-02 19:56 UTC
Labels: bug
