### ISSUE TITLE
UI Canvas Problem

### ISSUE THREAD

**Issue by Mallo-Lucas** [googlevr/cardboard#247] opened 2021-04-13 15:04 UTC
Hi! currently im using unity 2020.2.0 and i could install and use the xr cardboard plugin, but when i build the game the ui canvas only apears at the right eye. why this hapend? here is a photo:
![WhatsApp Image 2021-04-13 at 11 53 55](https://user-images.githubusercontent.com/61807778/114575170-4a222300-9c50-11eb-9e3c-be974901b09f.jpeg)

**Comment by kukuhbr** [comment] 2021-04-14 07:22
Have you made sure that the canvas is World Space Canvas?

**Comment by jballoffet** [comment] 2021-04-28 21:14
Thanks for reaching out to us, @Mallo-Lucas !

It seems this issue is a duplicate of #65. Could you please share a simple repro project where the issue is depicted and the steps required to reproduce it in #65 ? That would be really helpful in order to help solving it. Thanks!

**Closed by jballoffet** 2021-04-28 21:14 UTC
