### ISSUE TITLE
Possible to use Gyro with VR disabled?

### ISSUE THREAD

**Issue by ImmotionPeterL** [googlevr/cardboard#290] opened 2021-08-04 09:16 UTC
Is it possible to have the Cardboard subsystem loaded, VR disabled and use the gyro for 360 movement?

**Comment by andrewio** [comment] 2021-08-05 09:50
You can use this asset called [AR Camera Lite](https://makaka.org/o/ar-camera-gyro).

**Comment by ImmotionPeterL** [comment] 2021-08-05 10:04
> You can use this asset called [AR Camera Lite](https://makaka.org/o/ar-camera-gyro).

Thanks, I'm aware of your asset. But that doesn't answer my question.

**Comment by Layfully** [comment] 2021-08-06 09:47
Why would you need cardboard then?

**Comment by jballoffet** [comment] 2021-08-09 03:03
Thanks for reaching out to us. I'm closing this issue as it is a duplicate of #48 (see https://github.com/googlevr/cardboard/issues/48#issuecomment-710061004). As stated on that issue, you should be able to prevent the Display subsystem to start, and therefore, use only the Input subsystem. Please feel free to leave comments on that issue if needed. Thanks!

**Closed by jballoffet** 2021-08-09 03:03 UTC
Labels: duplicate
