### ISSUE TITLE
Fov not correct if android screen changed from WQHD to FHD

### ISSUE THREAD

**Issue by emile0909** [googlevr/cardboard#363] opened 2022-08-17 04:58 UTC
## Fov not correct if android screen changed from WQHD to FHD

Device: xiaomi mi 11, Android version 12
Cardboard SDK 1.16.0

## STEPS TO REPRODUCE THE ISSUE
Install google cardboard.
In xiaomi settings: set screen resolution WQHD (3200x1440), start app, you feel ok.
In xiaomi settings: set screen resolution FHD (2400x1080), start app, you feel dizzy.

#### When set screen resolution WQHD (3200x1440):
displayMetrics.xdpi = 515.154, displayMetrics.ydpi = 515.082
https://github.com/googlevr/cardboard/blob/13be8f3ff9a27f43e67d6f5d29d51256e34d4620/sdk/screen_params/android/java/com/google/cardboard/sdk/screenparams/ScreenParamsUtils.java#L69

width = 3063, height = 1440
https://github.com/googlevr/cardboard/blob/13be8f3ff9a27f43e67d6f5d29d51256e34d4620/hellocardboard-android/src/main/java/com/google/cardboard/VrActivity.java#L159

This is correct, xiaomi mi 11 has device size 164.3mm x 74.6mm
1440 / 515.082 * 25.4 = 71.01 ~= 74.6mm
3200 / 515.082 * 25.4 = 157.8mm ~= 164.3mm
where 25.4 is the millimeters for one inch.

#### These remain same.
displayMetrics.xdpi = 515.154, displayMetrics.ydpi = 515.082

#### These are different.
The width and height from onSurfaceChanged() is
2297, 1080 respectively.

So the screen_width_meters_ and screen_height_meters_ are wrongly calculated. So calculated fov are wrong, too.
https://github.com/googlevr/cardboard/blob/13be8f3ff9a27f43e67d6f5d29d51256e34d4620/sdk/lens_distortion.cc#L54

**Comment by arilow** [comment] 2022-09-19 14:03
Thanks @emile0909 for reaching out to us! Unfortunately, we weren’t able to reproduce the issue you are mentioning.


Details:
- Device: Samsung Galaxy S21
- Logs:
WQHD:
```
onSurfaceChanged, width: 3063
onSurfaceChanged, height: 1440
getScreenPixelDensity, displayMetrics.xdpi: 530.087
getScreenPixelDensity, displayMetrics.ydpi: 527.792
```
3102 / 530 * 25.4 ~= 148.7
1440 / 527.7 * 25.4 ~= 69.3


FHD:
```
onSurfaceChanged, width: 2327
onSurfaceChanged, height: 1080
getScreenPixelDensity, displayMetrics.xdpi: 397.56525
getScreenPixelDensity, displayMetrics.ydpi: 395.844
```


2327 / 397.5 * 25.4 ~= 148.7
1080 / 395. 8 * 25.4 ~= 69.3


Would you be so kind as to try to reproduce this issue on another phone just to be sure that this is not device-specific?


 Thanks!

**Comment by emile0909** [comment] 2022-09-20 02:08
Thanks for the reply.

Unfortunately, I don't have a second phone which has WQHD. But from what you have shown from a Samsung phone, it's probably a bug in xiaomi miui sdk. Cardboard doesn't need to do any modification.

If there's a work around, e.g. read some other parameters instead of displayMetrics.xdpi and displayMetrics.ydpi, it would be great.

If not, it's ok. Feel free to close this bug.

**Comment by arilow** [comment] 2023-04-18 18:22
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:22 UTC
Labels: bug
