### ISSUE TITLE
Android / Unity : Render is broken on Redmi note 10 pro

### ISSUE THREAD

**Issue by aldryss** [googlevr/cardboard#391] opened 2022-12-26 18:15 UTC
### SPECIFIC ISSUE ENCOUNTERED
Left Eye doesn't have the exepected orientation
Right Eye have several sliced views instead of one

### SMARTPHONE (please complete the following information):
- Device: Redmi Note 10 pro
- OS
  - [X] Android
  - [ ] iOS
- OS version 11

### STEPS TO REPRODUCE THE ISSUE
1. Follow guide on https://developers.google.com/cardboard/develop/unity/quickstart
2. Run
3. Cry a little

### EXPECTED BEHAVIOR
Run the HelloCardboard scene and see it

### VERSIONS USED
**What version of Google Cardboard are you using?**
I'm using master

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2021.3.12f1

- Select in which graphics API you can reproduce the bug.
   - Vulkan

### SCREENSHOTS
![Screenshot_2022-12-26-19-10-11-301_com DefaultCompany Cardboardtest](https://user-images.githubusercontent.com/1390959/209574538-676ce2fc-0778-4207-be2a-0c40b01b3ef5.jpg)

**Comment by arilow** [comment] 2023-01-02 14:30
Thanks @aldryss for reaching out to us!


I’ve been able to reproduce something similar to what you are describing by checking `Apply display rotation during rendering` checkbox in **Project Settings > Player > Other Settings > Vulkan Settings**. If this is your case, please uncheck it as it is stated in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#other_settings). 


Another way of getting that issue is setting autorotation as Default Orientation in **Player Settings > Resolution and Presentation** and Checking all the possible orientations. Given that auto rotation from landscape to portrait is not yet supported that would lend to a bug. If that is your case, a workaround would be unchecking Portrait and Portrait Upside Down. 


If none of the possibilities above solve you issue, could you please provide:
- The Cardboard SDK version being used.
- The required steps to expose the issue. You said you are following the Quickstart, but please write each step you are doing. So we can check any slight difference that might be.
- Device fingerprint. You can get it using adb with the following command:
```
adb shell getprop ro.build.fingerprint
```
- A simple Unity project where this issue is depicted would also be very helpful.
- Do you have another device to test? If so, please test it. In this way we can check if the issue is device specific.
Thanks!

**Comment by arilow** [comment] 2023-04-18 18:18
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:18 UTC
Labels: bug
