### ISSUE TITLE
URP error

### ISSUE THREAD

**Issue by marcolbx** [googlevr/cardboard#220] opened 2021-03-03 16:11 UTC
When enabling VR on URP the initialization is not completed and the app is stucked.

**Comment by joaoborks** [comment] 2021-03-08 12:06
Try following some of the guidelines at #140 

URP should not be the cause of your app not initializing, but maybe the Graphics API (that URP auto sets to vulkan which is unsupported at the moment) or some other cause.

**Comment by marcolbx** [comment] 2021-03-10 19:43
I will try again hopefully in the near future and come back with the result. Thank you in advance.

**Comment by jballoffet** [comment] 2021-03-10 21:53
Closing this issue as it seems to be a duplicate of #199.

**Closed by jballoffet** 2021-03-10 21:53 UTC
Labels: bug, duplicate
