### ISSUE TITLE
Cardboard XR switch vr mode and non-vr mode

### ISSUE THREAD

**Issue by imkrystal** [googlevr/cardboard#152] opened 2020-11-04 10:11 UTC
Hi Team.

I have create new Project and follow everything in document about Cardboard XR Plugin. It worked!
I want to make a button and toggle vr mode (2 eyes) and non vr mode (single eye). 
Can you help me?

Thank you so much.

Best Regards!

**Comment by JoaoBorks** [comment] 2020-11-04 13:57
@imkrystal I've created issue #140 with common tips (including the one you asked for). I've also submitted a Pull Request including a sample with this feature googlevr/cardboard-xr-plugin#13

**Comment by JoaoBorks** [comment] 2020-11-04 13:59
Also, this is a duplicate of #53

**Comment by imkrystal** [comment] 2020-11-05 01:37
Hi @JoaoBorks 
Thank you for your sample. 
But when I toggle VR mode, it not show 2 eyes mode, just single eye mode (I'm not edit anything your code and scene, just open your sample and test in iPhone).

1. Here my Project Setting:
<img width="747" alt="Screen Shot 2020-11-05 at 08 33 27" src="https://user-images.githubusercontent.com/46667579/98186566-9cdd0d80-1f41-11eb-8b75-a680f2baf613.png">

2. I tested in iPhone11 (it not 2 eyes mode)
![IMG_0047](https://user-images.githubusercontent.com/46667579/98186782-137a0b00-1f42-11eb-946e-e7afcec19524.PNG)

Do I need to do something else?
Thank you so much!
Best Regards!

**Comment by imkrystal** [comment] 2020-11-05 02:47
**"Choose only OpenGLES2 in Graphics APIs."**
When I config again, it worked!!! 
Here my config:
<img width="554" alt="Screen Shot 2020-11-05 at 09 14 00" src="https://user-images.githubusercontent.com/46667579/98189458-981b5800-1f47-11eb-9061-283bcaaa3f7b.png">

If I select "ARKit", I can use ARKit and Cardboard XR Plugin together?
<img width="745" alt="Screen Shot 2020-11-05 at 09 14 54" src="https://user-images.githubusercontent.com/46667579/98189358-66a28c80-1f47-11eb-9a33-b8964dfee444.png">

**Comment by JoaoBorks** [comment] 2020-11-05 02:53
Unfortunately, there's no way to use **ARKit** or any other **AR Framework** until OpenGLES 3 #40 or Metal #11 are supported.

**Comment by imkrystal** [comment] 2020-11-05 13:51
I understand. Maybe this plugin is still pretty new so it hasn't some function like: Magic window, support OpenGL3, Metal, Vulkan,...
I hope that you will release a new update plugin.
Thank you so much!
Best Regards!

**Comment by jballoffet** [comment] 2020-11-09 17:31
This is a duplicate issue, please take a look at #53.

**Closed by jballoffet** 2020-11-09 17:31 UTC
Labels: duplicate, question
