### ISSUE TITLE
Close and settings buttons don't respond (Unity cardboard-xr-plugin, iOS/Xcode build)

### ISSUE THREAD

**Issue by rubyfeller** [googlevr/cardboard#417] opened 2023-06-14 18:42 UTC
When building an app for iOS in Unity using the Cardboard XR Plugin, I encountered issues with the settings/gear button and the close button. These buttons are not responding. The rest of the app functions as expected.

### Smartphone
- Device: iPhone 12
- OS
  - iOS 16.5

### Expected behaviour
I expect the close button to terminate the app, and the gear/settings button to prompt me for camera permission and provide the functionality to scan the Cardboard QR code (the permission message has been set in the build settings).

### Versions used
**Google Cardboard XR plugin version**
- Cardboard XR Plugin v1.21.0

**Unity version**
- 2021.3

**Used Graphics API**
- Metal

**Screenshot**

![Screenshot of app with close/settings buttons](https://i.imgur.com/ws7uLhs.jpg) 

Relevant code for this is in **CardboardStartup**.cs:

    public void Update()
    {
        if (Api.IsGearButtonPressed)
        {
            Api.ScanDeviceParams();
        }

        if (Api.IsCloseButtonPressed)
        {
            Application.Quit();
        }

        if (Api.IsTriggerHeldPressed)
        {
            Api.Recenter();
        }

        if (Api.HasNewDeviceParams())
        {
            Api.ReloadDeviceParams();
        }

        Api.UpdateScreenParams();
    }

**Comment by arilow** [comment] 2024-02-26 23:30
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2024-02-26 23:30 UTC
Labels: bug

**Comment by drooJohnson** [comment] 2025-04-10 20:14
This is still an issue, I'll try to put together a minimal repro tonight.

**Comment by rjcausarano** [comment] 2025-04-15 13:00
@drooJohnson Is your issue the same as #475 ?
If it is the same issue please feel free to follow up on that ticket and that way maintain this issue as closed.
