### ISSUE TITLE
cardboard-xr-plugin stereo is not working on android

### ISSUE THREAD

**Issue by ar2vrPeter** [googlevr/cardboard#191] opened 2021-01-13 08:02 UTC
use Unity 2019.4.14f1,  cardboard v1.4.1 sample
it looks not stereo, the left and right eyes is the same( I have scan other viewer qr code)
![Screenshot_20210113-143650](https://user-images.githubusercontent.com/74162859/104421186-f9018500-55b5-11eb-8ff4-b6978a0e1238.png)
my unity setting
<img width="475" alt="截圖 2021-01-13 下午3 44 14" src="https://user-images.githubusercontent.com/74162859/104421787-c86e1b00-55b6-11eb-97b4-d02cd5e609aa.png">

use Unity 2019.4.14f1, cardboard v1.200.1
the left and right eyes is different
![Screenshot_20210113-141259](https://user-images.githubusercontent.com/74162859/104422296-885b6800-55b7-11eb-9870-53e6ea307957.jpg)

my project and apk link:
https://drive.google.com/drive/folders/1I20RLDppPpCZBGPKtRUVuPAbOlpwWJK5?usp=sharing

**Comment by Mandelbrow** [comment] 2021-01-14 13:57
Perhaps it has to do with the distance where the stereo images converges?
There was a setting for it in the camera with the previous built in vr system.
[https://docs.unity3d.com/ScriptReference/Camera-stereoConvergence.html](url)

Believe it's called fixation point in the new XR system:
[https://docs.unity.cn/2020.2/Documentation/Manual/xrsdk-input.html](url)

**Comment by jballoffet** [comment] 2021-01-15 15:47
Closing this issue as it is a duplicate of #128.

**Closed** 2021-01-15 15:47 UTC
Labels: duplicate
