### ISSUE TITLE
Android 10, AndroidX, Gradle, Gradle Plugin version upgrade

### ISSUE THREAD

**Issue by nagkumar** [googlevr/cardboard#131] opened 2020-10-05 13:06 UTC
The code still uses app compact, not androidx and other latest android 10, Gradle versions.

**Comment by jballoffet** [comment] 2020-10-16 15:19
Thanks for requesting these features. We are unable to fully migrate yet to AndroidX due to internal reasons. We’ll proceed when possible. About updating to Gradle 6.0, that has been prioritized and we’re currently working on it. About Android 10, the required modifications to support it will be included in the next release (v1.3.0) to be released very soon.

**Comment by andyz** [comment] 2021-03-16 16:42
This is a breaking issue for us as I do not know how (if) I can use this plugin alongside an androidx plugin in Unity.
Adding the required manifest items for this plugin leads to an error on building:

Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
    is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
    Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:3-83 to override

Not being an android expert I do not know the fix

**Comment by jballoffet** [comment] 2021-04-29 11:57
@andypoly, I think that the easiest thing for you to do in order to solve the issue is to migrate the Cardboard SDK to use AndroidX on your side (we weren't able to prioritize this task yet). You can use #92 for guidance. Hope this helps.

**Comment by andypoly** [comment] 2021-04-29 12:54
> @andypoly, I think that the easiest thing for you to do in order to solve the issue is to migrate the Cardboard SDK to use AndroidX on your side (we weren't able to prioritize this task yet). You can use #92 for guidance. Hope this helps.

yes I am not sure I have the time to learn & do that. Was hoping it was part of 1.5 but I see not.
Unfortunately I think even Unity 2019 LTS is all about metal and android X now so any plugin without those 2 is hard to use

**Comment by jballoffet** [comment] 2021-06-02 13:22
I'm glad to let you know that the next release of Cardboard will include the AndroidX migration and Gradle 6.8.3 support (Gradle 6.7 support was already included in v1.5.0).

**Comment by TassiDK** [comment] 2021-06-02 15:11
> I'm glad to let you know that the next release of Cardboard will include the AndroidX migration and Gradle 6.8.3 support (Gradle 6.7 support was already included in v1.5.0).

@jballoffet That sounds amazing! We could really use this fix right now, but is there any deadline for when 1.6.0 will be available? Many thanks. :)

**Comment by xinyunh0929** [comment] 2021-06-08 21:06
This was fixed in v1.6.0.

**Closed** 2021-06-08 21:06 UTC
Labels: feature request
