### ISSUE TITLE
Terrain Elements Popping into Frame in Right Eye

### ISSUE THREAD

**Issue by julien-tamade** [googlevr/cardboard#301] opened 2021-10-05 00:18 UTC
### SPECIFIC ISSUE ENCOUNTERED
In Unity, certain terrain elements pop into frame in the right eye when they move off the screen in the left eye. This creates a really bad effect

### SMARTPHONE (please complete the following information):
- Device: [e.g. iPhone 6]
- OS
  - [ ] Android
  - [ x] iOS
- OS version 14.7

### EXPECTED BEHAVIOR
We'd expect the trees and grass to be visible in both eyes as long as they are in frame

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.4.1

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2019.4.11f1

- Select in which graphics API you can reproduce the bug.
   - [x ] OpenGL ES2

### SCREENSHOTS

https://user-images.githubusercontent.com/44389340/135941320-7a5a2ed2-2112-49b4-8ecc-47e930d47212.MP4

**Comment by whizzkid** [comment] 2021-10-05 08:42
Same problem as [https://github.com/googlevr/cardboard/issues/54](https://github.com/googlevr/cardboard/issues/54)
Hopefully they will fix this soon. It's over a year old..

**Comment by arilow** [comment] 2022-01-24 14:51
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of [#54](https://github.com/googlevr/cardboard/issues/54). A fix for the aforementioned issue has been submitted and it will be included in v1.12.0. Please reopen this ticket if this is still an issue for you.

Thanks!

**Closed by arilow** 2022-01-24 14:51 UTC
Labels: bug, duplicate
