### ISSUE TITLE
iPhone 16 using Default DPI

### ISSUE THREAD

**Issue by chappee2000** [googlevr/cardboard#479] opened 2024-11-03 19:52 UTC
### SPECIFIC ISSUE ENCOUNTERED
iPhone 16 devices are showing the VR view too small on the screen

### SMARTPHONE (please complete the following information):
iPhone 16Pro
iOS 18

### STEPS TO REPRODUCE THE ISSUE
1. Open a google cardboard application using an iPhone 16 or any other in the iPhone 16 series of device

### EXPECTED BEHAVIOR
VR View should use the full width of the device
![RMB_LuckyCornerDriverWave_MeshMissingTexture](https://github.com/user-attachments/assets/d458332e-c723-472a-870f-d2c1fac408c6)

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK v1.23.0 and v1.26.0

- What version of Unity are you using?
2022.3.14f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ ] OpenGL ES3
   - [ ] Metal

### SCREENSHOTS
![IMG_1144](https://github.com/user-attachments/assets/7230b087-a772-4b30-8626-3eb137bae87d)

**Comment by lneumarkt** [comment] 2024-11-15 19:32
Thank you @chappee2000  for reaching out to us.
The screen parameters for the new iOS devices have been internally submitted and will be included in v1.27.0.

I'm closing this issue as it is a duplicate of [#428](https://github.com/googlevr/cardboard/issues/428). Please feel free to leave comments on that issue if needed.
Thank you!

**Closed by lneumarkt** 2024-11-15 19:32 UTC
Labels: bug
