### ISSUE TITLE
toggle between vr and nonvr in non-unity-projec

### ISSUE THREAD

**Issue by aniltirola** [googlevr/cardboard#196] opened 2021-01-26 21:26 UTC
I searched in the issues for the toggle between vr (2 eyes) and non-vr-mode (single-full-screen-view); but everything I find is related to unity-pluging. Could you please tell me how to toggle in the examples of `hellocardboard-android` and `hellocardboard-ios`?

**Comment by jballoffet** [comment] 2021-01-29 19:45
Closing this issue as it is a duplicate of #25.

**Closed by jballoffet** 2021-01-29 19:45 UTC
Labels: duplicate
