### ISSUE TITLE
initialize Cardboard XR loader before calling this function

### ISSUE THREAD

**Issue by KristynaPavlatova** [googlevr/cardboard#324] opened 2022-01-22 11:47 UTC
### SPECIFIC ISSUE ENCOUNTERED
Google's Cardboard VR sample scene in Unity gives an error.
Issue is in HelloCardboard sample scene from the Google Cardboard imported plugin.
Error message:
Please initialize Cardboard XR loader before calling this function.
UnityEngine.Debug:LogError (object)
Google.XR.Cardboard.Api:UpdateScreenParams () (at Library/PackageCache/com.google.xr.cardboard@891dec0b1a/Runtime/Api.cs:295)
CardboardStartup:Update () (at Assets/Samples/Google Cardboard XR Plugin for Unity/1.11.0/Hello Cardboard/Scripts/CardboardStartup.cs:70)

Unity 2020.3.20f1, android build
Packages installed: XR Plugin management, Google Cardboard XR Plugin for Unity (installed through GIT, import package via URL)
Google Cardboard imported as it is described here: https://developers.google.cn/cardboard/develop/unity/quickstart

### SMARTPHONE (please complete the following information):
- Device: Samsung Galaxy S8+
- OS
  - [x] Android
- OS version: Android 9, API level 27

### STEPS TO REPRODUCE THE ISSUE
1. Have GIT installed on your PC
2. Create empty 3D project in Unity
3. in the project go to Package Manager > + > import with URL > paste the given URL from the "Google's Quickstart for Google Cardboard" (the link to import package: https://github.com/googlevr/cardboard-xr-plugin.git)
4. In Package Manager > XR Plugin management > import
5. In Assets > Samples > ... > Hello Cardboard > Scenes > open the HelloCardboard scene
6. Editor > Project settings > XR Plug-in Management > Android > check "Initialize XR on startup" & check "Cardboard XR Plugin" in the Plug-in providers section
7. Back in the HelloCardboard scene hit Play button and the error message shows up "Please initialize Cardboard XR loader before calling this function.
UnityEngine.Debug:LogError (object)
Google.XR.Cardboard.Api:UpdateScreenParams () (at Library/PackageCache/com.google.xr.cardboard@891dec0b1a/Runtime/Api.cs:295)
CardboardStartup:Update () (at Assets/Samples/Google Cardboard XR Plugin for Unity/1.11.0/Hello Cardboard/Scripts/CardboardStartup.cs:70)"

### EXPECTED BEHAVIOR
HelloCardboard scene can be played without any errors.

### VERSIONS USED
Cardboard SDK/Cardboard XR Plugin 1.11.0
Unity 2020.3.20f1, android build

- Select in which graphics API you can reproduce the bug.
   - [x] Automatic graphics API

![Screenshot (336)](https://user-images.githubusercontent.com/60941311/150637205-f8562f1c-5ac9-46bc-9d03-cbe74ab2e912.png)
![Screenshot (335)](https://user-images.githubusercontent.com/60941311/150637209-a84bda06-b5a1-4cb8-9210-eaf3576cd6d7.png)
![Screenshot (334)](https://user-images.githubusercontent.com/60941311/150637216-8b77326c-feb6-4122-8984-eed3f20b8f71.png)

**Comment by arilow** [comment] 2022-01-25 16:35
Thanks @KristynaPavlatova for reaching out to us! I confirm that I could reproduce your issue.


Currently, Editor Play mode is not supported by the Cardboard SDK. That is why the error message appears when the play button is pressed.
At the moment, the Cardboard XR Plugin can only be executed on Android and iOS devices as it is pointed out in the [Quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#build_your_project).
Issue #51 is currently tracking the feature request for adding Editor Play mode support. I’m closing this issue now as it is a duplicate of the aforementioned one. 

Thanks!

**Closed by arilow** 2022-01-25 16:35 UTC
Labels: bug, duplicate

**Comment by Cat9199** [comment] 2024-02-15 11:14
Thank you
