### ISSUE TITLE
Unity XR plugin + Android: choppy gyro performance with demo project

### ISSUE THREAD

**Issue by msuencksen** [googlevr/cardboard#99] opened 2020-08-26 16:14 UTC
This problem of motion judder already occured with the older (Unity 2018) cardboard integration. 

Regarding the latter, the following fix worked: 
`Input.gyro.enabled = true;`

However, that does not help with the new XR plugin.

I am seeing this problem with Unity 2020.1.3 on a Xiaomi (Snapdragon 660 / Android 10) phone.

**Comment by jballoffet** [comment] 2020-10-16 15:42
Thank you for reporting this issue. I confirm I’m able to repro de issue locally. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by agalbachicar-gg** [comment] 2020-10-29 21:16
I confirm @jballoffet's comment. Release 1.3 was tested in the following Unity versions and I got the following results:

- 2019.4.13f1: it works fine, no error is noticeable.
- 2020.1.11f1: I can reproduce the bug.
- 2020.2.0b9: I can reproduce the bug.

It was tested on a Pixel 4XL using Android 10. Sample project created with [Cardboard's quickstart](https://developers.google.com/cardboard/develop/unity/quickstart). I hope this little investigation gives you more information.

Please, let us know if you find something else. Given that this issue was not prioritised for this release we cannot allocate more cycles to it but will consider it for next one with others.

**Comment by agalbachicar-gg** [comment] 2020-11-17 21:00
Update: we have tested this on iOS with Unity 2020.1 and it is not happening (Unity 2020.2 not because there is no support for OpenGL anymore).

**Comment by agalbachicar-gg** [comment] 2020-12-03 21:05
This comment https://github.com/googlevr/cardboard/issues/165#issuecomment-736847787 showed the right path forward to deal with the situation and uncovered another bug. Thanks @TediumInteractive for the investigation.

To sum up:

- In Unity 2020.1 the option `Optimized Frame Pacing` was set to enabled by default whereas in 2019.4 was set to disabled by default. To find this configuration go to: `Project Settings > Player > Resolution and Presentation`
- I verified that enabling `Optimized Frame Pacing` in Unity 2019.4.15f1 the application behaves the same as in 2020.1 and 2020.2 with that setting (platform Android).
- We will update the quickstart to ask users to disable `Optimized Frame Pacing` option and run an internal investigation on how to properly deal with that flag as a known issue.

I'll close this ticket once the quickstart is updated.

**Comment by agalbachicar-gg** [comment] 2020-12-12 01:09
Quickstart has been updated.

**Closed by agalbachicar-gg** 2020-12-12 01:09 UTC
Labels: bug
