### ISSUE TITLE
URP post processing not working

### ISSUE THREAD

**Issue by HeavyArmoredMan** [googlevr/cardboard#318] opened 2021-12-19 18:36 UTC
### SPECIFIC ISSUE ENCOUNTERED
Using the Unity URP build-in post processing (not the Post Processing Stack V2 from package manager) freezes the screen.

### SMARTPHONE:
- Device: [Motorola Edge S]
- OS
  - [X] Android
- OS version [Android 11]

### STEPS TO REPRODUCE THE ISSUE
1. Add a Volume game object with post processing profile to the scene;
2. Add a post processing effect to the profile. For example, Bloom;
3. Enable Post Processing in Main Camera;
4. Build and run.

### EXPECTED BEHAVIOR
Stereoscopic rendering with post processing effects.

### VERSIONS USED
Cardboard XR Plugin v1.10.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2021.2.7f1

- Select in which graphics API you can reproduce the bug.
   - [X] OpenGL ES3

**Comment by arilow** [comment] 2022-05-11 12:25
Thanks @HeavyArmoredMan for reaching out to us! And sorry for the long delay. We have tried to reproduce the bug you have reported without success.


The steps we followed were:
- Set up a Cardboard sample project by following the steps in the [Cardboard Quickstart for Unity](https://developers.google.com/cardboard/develop/unity/quickstart).
- Setup URP as it is shown in the following [Unity video](https://youtu.be/m6YqTrwjpP0?t=174).
- Create a URP volume object adding post-processing from [“Configuring post-processing in a new URP Scene” from the Unity manual](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/integration-with-post-processing.html).
- Create a volume object with bloom as you mentioned.
- Build and Run.
- The Cardboard sample works as it should.

Useful information:
- Cardboard OSS version: 1.15
- Phone: Samsung Galaxy S20 FE
- OS: Android 12
- Unity version: 2020.3
- URP version: 10.8.1

Could you please give it a try again using the latest release of the Cardboard XR Plugin? Some issues related to URP have been solved lately so this issue might have been solved as well.

In case the issue hasn’t been solved, it would be great if you could share a simple repro project with us so as to continue debugging it.

Thanks!

**Comment by arilow** [comment] 2023-05-08 14:27
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-05-08 14:27 UTC
Labels: bug
