### ISSUE TITLE
"Corrugated" tracking on iOS 14

### ISSUE THREAD

**Issue by yoxallj** [googlevr/cardboard#164] opened 2020-11-19 09:52 UTC
As a result of the recent iOS 14 issues we are in the process of upgrading to Unity 2019.4.13f1 and the new Google cardboard plugin.  We have however found an issue where the gyroscope tracking is now “jerky” on iPhone (one user described it as “like running your fingers across corrugated cardboard”).  

It is very evident with iOSv14, and also detectable on v13 (although the effect seems reduced, but is very subjective).  It is however completely smooth on Android.

The problem is easily observed with the sample app provided with the plugin.

Interestingly, if you try to video capture it the images are completely smooth, so the problem must be in the interaction between the 2 parts of the image.

Has anyone else observed this?

**Comment by Excubitor** [comment] 2020-11-21 17:07
I’m using google vr in Unity. The one thing I’ve noticed is that it is jerky when you are turning your head fast, which I guess is update speed of the gyro. Don’t know if something can be done about that. Slow turnes work much  smoother.

**Comment by yoxallj** [comment] 2020-12-02 19:19
@jballoffet - I would be very keen to know, given that you have marked this as a bug, whether you have been able to confirm the issue yourself.  We are finding it odd that there aren't a chorus of other voices saying they are having the same problem, so knowing you have seen it would be at least rule out that the problem is something at our end.  And if so, would it be possible to get any sense of possible timescales for resolution, as this is undermining the viability of our app - even if just at a level of weeks, months, or years.  

@Excubitor - the effect we have seen is still observable if you move your head slowly.  Also, it didn't occur with the old version of the google cardboard plugin.  And it doesn't occur on low-end Android phones, but does occur on high-end iPhones.  We are still hoping therefore that it is something specific that can be resolved.

To add one further bit of info, I have tried all configuration options within new Tracked Pose Driver component and no improvement was observed.

**Comment by CreaProjects** [comment] 2020-12-21 09:00
Same here. Before iOS 14 I was using Unity 2018 with the integrated Cardboard SDK it was working fluently.
Now with iOS 14, I had to update Unity to 2019 and manually install the new Cardboard SDK. It's very laggy, like 25fps instead of 60...

**Comment by Mandelbrow** [comment] 2020-12-23 18:10
Perhaps the xr plugin should read the gyro at a higher frequency?

**Comment by jballoffet** [comment] 2021-01-06 12:38
Thanks for reporting this issue. Unfortunately, I cannot repro it locally on my devices (iOS 14.0 on an iPhone 8 Plus and iOS 13.5.1 on an iPhone SE (Gen 2)). A ticket for performing a deeper research has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by yoxallj** [comment] 2021-01-13 19:37
Hi jballoffet.  Thank you for looking into this.  

Our experience was that we saw the issue on every iPhone we tested it on with iOS 14, across a test group of 5 people with a range of devices.  On iOS 13 it was still observed, but was reported as less obvious (I don’t have an iOS13 device, so haven’t seen it myself).  

To provide you with some specifics we have now upgraded to the latest version of the Unity plugin and retested it on:
- iPhone 6S - 13.6 - observable but very faint
- iPhone 7 - 14.1
- iPhone X - 14.2
- iPhone 12 - 14.3

However, if you aren’t seeing it then maybe the issue is elsewhere, such as in the config of our version of the demo project.  We could quickly confirm this if you had a release of the demo app we could install, so we are definitely looking at the same thing.  Equally, I can add you to TestFlight for the version of the demo I built.

**Comment by jballoffet** [comment] 2021-04-29 12:55
Sorry for the long delay here, @yoxallj. The new release of the Cardboard SDK (v1.5.0 to be release soon) includes some changes related to the HeadTracker module. I'd suggest that you give it a try once it is out and in case the issue is still taking place, please reach out to us again providing a simple Unity repro project that we can build and execute in order to try to reproduce the issue locally.

**Comment by chaosemer** [comment] 2021-04-30 00:55
This was fixed in v1.5.0.

**Closed by chaosemer** 2021-04-30 00:55 UTC
Labels: bug, fixed in upcoming release
