### ISSUE TITLE
The git package import fails.

### ISSUE THREAD

**Issue by synthercat** [googlevr/cardboard#255] opened 2021-04-30 17:44 UTC
I tried adding https://github.com/googlevr/cardboard-xr-plugin.git but got some errors.

[Package Manager Window] Unable to add package [https://github.com/googlevr/cardboard-xr-plugin.git]:
  Could not clone [https://github.com/googlevr/cardboard-xr-plugin.git]. Revision [HEAD] could not be found.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/googlevr/cardboard-xr-plugin.git]:
  Could not clone [https://github.com/googlevr/cardboard-xr-plugin.git]. Revision [HEAD] could not be found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Error adding package: https://github.com/googlevr/cardboard-xr-plugin.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

It used to work and my system had minor changes since the last time I used it. Any ideas would be appreciated.

**Comment by synthercat** [comment] 2021-05-03 09:44
After more tests I found out that 2020.3.6 can't import the repository (or if manually imported, can't download the extra parts).
On the other hand 2019.4.21 is able to import it fine.

**Comment by AmigaAbattoir** [comment] 2021-05-03 16:01
Did you try with 2019.3.15? I was able to do it with that. I think I removed the Cardboard SDK first, then tried importing it.

**Comment by synthercat** [comment] 2021-05-03 17:00
Thank you the reply Amiga (epic name!). However as I wrote above, it did work fine with 2019.4.21 so I have no need to go to something older such as 2019.3.15.

**Comment by AmigaAbattoir** [comment] 2021-05-04 15:11
Thanks! The reason I mentioned it was that I thought I saw some other project had issues with adding a git, which worked in 2019.3.7, so I thought it might be one of those quirky Unity issues. Also, if you had other things in your project that might prevent you from updating to 2019.4, that there was still an option.

**Comment by jballoffet** [comment] 2021-05-10 14:39
Thanks for reaching out to us, @synthercat ! I cannot reproduce the reported issue on Unity 2020.3.3f1. Would you be so kind as to give it a try with the latest Unity 2020.3 version (2020.3.7f1)?

**Comment by synthercat** [comment] 2021-05-11 13:52
I just did and still has the same issue.

Completely empty (new) 3d project in 2020.3.7f1. 

[Package Manager Window] Unable to add package [https://github.com/googlevr/cardboard-xr-plugin.git]:
  Could not clone [https://github.com/googlevr/cardboard-xr-plugin.git]. Revision [HEAD] could not be found.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/googlevr/cardboard-xr-plugin.git]:
  Could not clone [https://github.com/googlevr/cardboard-xr-plugin.git]. Revision [HEAD] could not be found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/googlevr/cardboard-xr-plugin.git]:
  Could not clone [https://github.com/googlevr/cardboard-xr-plugin.git]. Revision [HEAD] could not be found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Error adding package: https://github.com/googlevr/cardboard-xr-plugin.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()


My current git is installed via the "scoop" command line installer. I know it causes issues some times, for example it's ffmpeg doesn't work exactly as me downloading ffmpeg. However I didn't had any issues with 2019LTS

**Comment by paulorenanmelo** [comment] 2021-05-14 09:35
Just started a new unity project on 2020.3.6 using the VR Template and switched to Android (not sure if that's a requirement to reproduce the issue) and when adding the https repo through the package manager I get the exact same error mentioned above.

I opened a unity bug on that with a link to this issue here.

2020 was so bad that even the LTS version from it hunts us with bugs
lol

**Comment by jballoffet** [comment] 2021-05-17 21:36
I tried to reproduce the reported issue using Unity 2020.3.8f1 and I couldn't, the package is properly imported locally on my machine (macOS). I suspect there is something going on between Unity and your Git client. Would you be so kind as to double check whether this only takes place with the Cardboard XR Plugin or this not strictly related to it? (for instance, trying to import another package from a git URL). Thanks!

**Comment by paulorenanmelo** [comment] 2021-06-01 15:57
Thank you jballoffet!
After more debugging, this issue happens on any public git repo here.
I'll try to remember to feed back to this thread once I hear back from Unity. Seems like something is not right on the engine _(or perhaps I'm the one not right)_ when you try to import a git package from URL, while having a private key setup for private git repos. Works fine on the command prompt on windows, but unity package manager fails to import it.

**Comment by jballoffet** [comment] 2021-09-20 18:16
Closing this issue since according to the last comments it was related to a Unity issue and it's been a while since the last comment. In case the issue persists and only takes place when using Cardboard, please feel free to reopen.

**Closed by jballoffet** 2021-09-20 18:16 UTC
Labels: bug
