### ISSUE TITLE
Wrong input detection

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#429] opened 2023-08-27 18:49 UTC
ISSUE
When I am pointing on object nothing happens, but if I am pointing on the right side it works. In editor no such issue.

### SMARTPHONE (please complete the following information):
- Device: Iphone 11
  -  iOS
  
Unity: 2022.1.24.f1

### VERSIONS USED
Unity Cardboard XR Plugin 1.21.0
![photo_2023-08-27 20 38 34](https://github.com/googlevr/cardboard/assets/55288472/24898f0d-a87d-44be-94ad-08557ad754a3)

**Comment by arilow** [comment] 2023-09-08 14:05
Thanks @MusemoDeveloper  for reaching out to us!


Unfortunately we haven’t been able to repro this issue on unity 2022.1.24.
In order to allow us to reproduce this issue, could you please provide:

- The required steps to expose the issue. Even if you are following the quickstart, please write the steps you are doing. So we can check any differences there might be.

- iOS version.

- A simple Unity project where this issue is depicted would also be very helpful.

On the other hand, when using the latest Cardboard XR Plugin version, a text view and the wall behind the treasure is expected to be seen, showing the graphics API being used. Do you see it? Because by takinga look at the image shared, it seems it is not there.


Thanks!

**Comment by arilow** [comment] 2024-02-26 23:21
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2024-02-26 23:21 UTC
Labels: bug
