### ISSUE TITLE
Recenter not working in v. 1.18

### ISSUE THREAD

**Issue by Mandelbrow** [googlevr/cardboard#379] opened 2022-11-07 16:35 UTC
Api.Recenter();  seems to be broken. It was working fine in SDK v.1.8, but in v.1.18 not much is happening in Unity 2020.3.41, and building for Android.

Continuing from the last post in #63:

        Thanks for reaching out to us @rodrigozol! In case this is an issue of the Cardboard SDK or the XR Plugin, please create a new issue adding the following information:
- The required steps to expose the issue.
- The Cardboard XR Plugin version being used.
- Unity version.
- Rendering API used.
- A simple Unity project where this issue is depicted would also be very helpful.

Thanks!

_Originally posted by @arilow in https://github.com/googlevr/cardboard/issues/63#issuecomment-1117402930_

**Comment by arilow** [comment] 2022-11-11 14:55
Thanks @Mandelbrow for reaching out to us! Unfortunately I couldn’t reproduce the issue locally on my Samsung Galaxy S20.


In order to help us to reproduce this behavior, could you please:
- Provide us the device model and fingerprint. You can get the fingerprint using adb with the following command:
```
adb shell getprop ro.build.fingerprint
```
- The recenter method is called [here](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Samples~/hellocardboard-unity/Scripts/CardboardStartup.cs#L62). Could you try calling it outside the `if()` so we can check if the issue is in the function or in the timing.
- Another option would be to add a log within the recenter function to see if it is being called.


Thanks!

**Comment by arilow** [comment] 2023-04-18 18:20
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-04-18 18:20 UTC

**Comment by Mandelbrow** [comment] 2023-06-05 13:04
Reopening this as the Recenter error is still present in SDK v. 1.21.0.

After some testing it turns out that leaning the head at any side will make Recenter to fail. It was working fine in SDK v. 1.8.0.

![v1 21 0_leaning_head_before_recenter](https://github.com/googlevr/cardboard/assets/74099150/674c77ce-f898-48d6-8825-c5f566514975)
![v1 21 0_failed_recenter_when_leanng_head](https://github.com/googlevr/cardboard/assets/74099150/cd26c2c7-1eae-4939-a13c-7ba114690916)

It looks better when the head is held in an upright position.
![v1 21 0_upright_head_before_recenter](https://github.com/googlevr/cardboard/assets/74099150/f9000f7c-2e53-4ad0-b81a-99d77a91ff1a)
![v1 21 0_upright_head_after_recenter](https://github.com/googlevr/cardboard/assets/74099150/4ae5bfd5-a160-4a58-9e37-56d4f70d52de)
