### ISSUE TITLE
 IOS Failed to initialize subsystem Input [error: 1]

### ISSUE THREAD

**Issue by Git327017278** [googlevr/cardboard#149] opened 2020-10-27 07:35 UTC

**Comment by Git327017278** [comment] 2020-10-28 08:54
Vuforia  SDK  have a conflict

**Comment by JoaoBorks** [comment] 2020-10-29 13:43
Duplicate of #133

**Comment by jballoffet** [comment] 2020-11-09 16:31
This is a duplicate issue, please take a look at #133.

**Closed by jballoffet** 2020-11-09 16:31 UTC
Labels: bug, duplicate
