### ISSUE TITLE
Unity XR Plugin (SDK) — Do you have plans to release this new SDK to Unity?

### ISSUE THREAD

**Issue by zxcvb7653** [googlevr/cardboard#8] opened 2019-11-09 14:00 UTC

**Comment by alapparikh** [comment] 2019-11-14 10:02
If so, what is the expected release date? There are existing bugs in the Google VR SDK for iOS which I hope will be resolved with this new open source initiative. 

Thanks!

**Comment by jballoffet** [comment] 2019-11-15 15:27
As mentioned in our [announcement](http://developers.googleblog.com/2019/11/open-sourcing-google-cardboard.html.), we're in the process of developing an SDK (package) for Unity 2019.2 and later. Please star or watch this issue to be notified when the SDK becomes available.

**Comment by andrewio** [comment] 2020-01-25 01:01
Glad to waiting for a new plugin. I hope, it will be released soon.

**Comment by synthercat** [comment] 2020-01-30 13:36
Do you need any help with this plugin? I don't have plenty of extra time but I'd love to help if possible.

**Comment by tallenbaugh** [comment] 2020-02-04 17:22
Subscribed to this issue and waiting for the Unity plugin with bated breath!

**Comment by caspermm** [comment] 2020-02-05 18:25
+1

**Comment by danielshervheim** [comment] 2020-02-05 18:27
+2 =)

**Comment by GilbertoBitt** [comment] 2020-02-05 21:41
+3

**Comment by Momeo** [comment] 2020-02-06 07:08
+4  I can't wait for this plugin any more :)

**Comment by Bakalino** [comment] 2020-02-09 08:29
Any idea when the SDK is released?

**Comment by jballoffet** [comment] 2020-02-10 12:27
Thank you for your patience. We're still working to build an initial release of the new Unity XR Plugin. We'll update this issue once the plugin is available.

**Comment by caspermm** [comment] 2020-02-10 20:25
@jballoffet It will support Cardboard VR too right?

**Comment by qqshnep** [comment] 2020-02-13 05:17
+5

**Comment by 78Star** [comment] 2020-02-13 08:10
+6 since google took away updating their other system, thus keep any use with newer versions of unity broken untill this new system is released.

**Comment by atteneder** [comment] 2020-02-13 08:17
It would be nice if everyone who wants to express, that they're eagerly waiting for this does not post a comment. You trigger useless notifications for all subscribers.
Respond with an emoji response or something, ffs

**Comment by synthercat** [comment] 2020-02-14 10:43
Ι just realized that my last bug report to Unity is regarding the previous version of this plug in that probably affects the one being developed. To make a long story short:
A project using GVR 1.200.1 and ResonanceAudio 1.2.1 runs at 60fps when build with 2018.4 but on 30fps when build with 2019.2 or 2019.3 versions (same project, same device Xiaomi Mi8). I noticed on the (android run) profiler that the only difference is a huge amount of vsync delay on the 30fps version so my guess is that it accidental locks in vsync x 2 mode. Maybe you guys should take a look at this too.

**Comment by technomacx** [comment] 2020-03-05 13:08
Waiting +1

**Comment by jballoffet** [comment] 2020-03-09 12:35
Thank you @synthercat for the heads up. We expect the in-development Cardboard Unity SDK to run at both 60fps and 30fps, based on project settings. If you notice otherwise, please file a new bug once it is released.

**Comment by cdytoby** [comment] 2020-03-10 10:10
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

This is getting critical, because UIWebView in old Cardboard is no longer acceptable start from next month.

**Comment by cdytoby** [comment] 2020-03-12 09:16
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

Somehow I feel Apple is playing with us. Anyway, they changed the deadline. So we have more time to get things right.

**Comment by Ethan-VisualVocal** [comment] 2020-03-12 18:06
New app submissions rejected starting next month, April 2020
Updates to existing apps rejected starting December 2020

https://developer.apple.com/news/?id=12232019b

I thought Apple had sent us that warning in error, as we could find no reference to UIWebview in our code, so thank you for revealing it was the Google GVR plugin that used UIWebView, @cdytoby !  Unfortunately this causes a lot of problems for us on the April timeline.

**Comment by danilofaugusto** [comment] 2020-03-16 17:32
Hi, @jballoffet !

Do you folks have some kind of release roadmap (alpha, beta, final...) that you could share? 

I understand you might be having hiccups, but to help the other devs/companies and I to plan, a roadmap would be very helpful. :)

Thanks

**Comment by eduard-88** [comment] 2020-03-18 08:58
@danilofaugusto totally the same here.

@jballoffet, in our case we want to help in relieving some markets with covid19, so it would be great to have access now after the long wait.

**Comment by eduard-88** [comment] 2020-03-18 09:06
> Thank you for your patience. We're still working to build an initial release of the new Unity XR Plugin. We'll update this issue once the plugin is available.

Hi @jballoffet , thanks for all your efforts!! We are trying to relieve some groups during the current covid19 crisis now, with our application. For this we are only waiting for this SDK to be released. So it would be really awesome if you could share any clue when it will be available, as it would really helpful for us all right now ^^

Thanks and good luck everyone!

**Comment by cdytoby** [comment] 2020-03-18 11:03
I was just given a deadline to find potencial alternatives until Friday Mornin. We're preparing, that if Google doesn't provide any solutions in time, we need an alternative as a backup. So, does anybody have resource or alternative to Google Cardboard for iOS?

**Comment by Momeo** [comment] 2020-03-18 11:07
> I was just given a deadline to find potencial alternatives until Friday Morning. We're preparing for worst case, that if Google doesn't provide any solutions in time, we need an alternative as a backup. So, does anybody have resource or alternative to Google Cardboard for Unity iOS?

use webvr-polyfill (javascript)? Maybe you can build and watch your scene in the brower.

**Comment by interactivespace** [comment] 2020-03-18 11:33
Sometimes, also bad news can be helpful. So when the Unity Plugin is for sure not ready within the next months, it would be also nice to know :)

**Comment by mi3ctf** [comment] 2020-03-18 12:23
> I was just given a deadline to find potencial alternatives until Friday Morning. We're preparing for worst case, that if Google doesn't provide any solutions in time, we need an alternative as a backup. So, does anybody have resource or alternative to Google Cardboard for Unity iOS?

Possible alternatives, if you aren't tied specifically to using Unity have you checked out AWS Sumerian - https://aws.amazon.com/sumerian/

If you are already embedded or upskilled on Unity and want to continue on that platform then is there a problem with just using the existing Google VR iOS package that is available and supported in Unity 2019.3.

The package is marked as deprecated but that is only to point out that it won't be supported Unity 2020. Given that Unity 2019 still hasn't even reached it LTS build yet there is plenty of life and support for Production development and app releases built on Unity 2019.

I am also looking forward to the Unity XR Plugin for Google Cardboard to be made available but only really to provide backwards compatibility for certain apps being developed that I want to be cross device compatible when using the Unity XR framework and libraries. 

For the time being the Google VR iOS  and Android packages have been very usable with decent sample examples provided and documented.

I am not holding my breath waiting for the Google Unix XR plugin to be available any time soon, haven't heard of any alpha or beta testing availability or if we even will. Also given no roadmap or rough timeline information e.g. 2020? I wouldn't be making any plans that rely on it being available and usable anytime soon. Hopefully we will be otherwise surprised :)

**Comment by cdytoby** [comment] 2020-03-18 15:02
@mi3ctf I wish I could continue using the Google VR SDK, but as I mentioned in previous comments, when using it on iOS, the app CAN'T be published after April. And I got answers that we HAVE TO use Cardboard on iOS, with Unity developed, and should also work with new apps on iOS Store, and submission should be sucessful without rejection. Because we already makes some of our clients and their clients unhappy with another bad news.

Technical issue is (If I'm correct):
Current GoogleVR Unity SDK ->UnityVR->Unity GoogleVR -> GVRSDK Pod on XCode. And this GVRSDK Pod for XCode uses UIWebView, which has been deprecated and make Apple unhappy. 

So, If someone have solution, that prevent the final app uses UIWebView, please help me and some potencial other devs. 

(PS, I'm just trying to use Unity Cardboard SDK 0.8.1, which is before unity vr integration. It crashes on Android before Unity splash screen. I don't know what will happen on iOS.)

**Comment by Ethan-VisualVocal** [comment] 2020-03-18 17:48
@cdytoby This is a very long shot, but: Since it's all open source now, you could implement your own cardboard support on iOS for Unity. 

HOWEVER, given the complexity of the problem, you probably would want to use Unity's XR plugin SDK -- getting access to this requires sign-up and then an invite: 

- Signup link: https://create.unity3d.com/vsp-signup-form 
- Original source of signup link: https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/ 
- Link to discussion where I found this: https://forum.unity.com/threads/xr-plugins-and-subsystems.693463/page-5#post-5438901 

This is basically what Google would/will be doing.  (And, unfortunately for us, we just don't have the budget to do the same.)

**Comment by cdytoby** [comment] 2020-03-19 11:11
Thanks for all the replys. I'll share what I've found.

- There is a Cardboard SDK alternative, but it seems stopped developing long ago. https://www.durovis.com/en/sdk.html   You can check out yourself. I tested on iOS, it works, but it uses just double unity cameras without lens correction. But it works at least on my iPad Air (I don't have an iphone in my hand), with test project. I haven't tested if it can upload to itunes correctly.
- There is another guy who made Cardboard iOS available BEFORE Google make cardboard for iOS available. https://github.com/psklf/CardboardSDK-iOS  (It's a fork from another guy because this repository did some further changes). Anyway, I haven't tested it out yet because it's so complicated and I didn't understand how this Unity project with iOS plugin works, it has strange folder structure.
- Here you go, libsdk.a, compiled on XCode, I have no idea if it can be used in Unity as plugin. [libsdk.zip](https://github.com/googlevr/cardboard/files/4354081/libsdk.zip). Anyway, this is compiled from this repository, on MacOS, with XCode. 
- In theory this libsdk.a (I hope I can rename it to libCardboardSdk.a) can be used as plugin. The old cardboard project version 0.8.1 don't have Unity VR support and it used tradition 2 cameras setup for VR, and it also had a `libgvrunity.a` and referenced in unity code with `DLLImport`. Combine this file with old cardboard code, I think it's possible to reproduce a Cardboard Unity Plugin, for iOS.

**Comment by cdytoby** [comment] 2020-03-20 15:15
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK

OK, we decided to make an unofficial cardboard unity sdk, and I was given permission to make it public so that we can get more help from you.

On behalf of my company, may I present, work in progress Cardboard VR Unity SDK.

I'm still fighting against the cardboard initializing on iOS.

**Comment by andrewio** [comment] 2020-03-20 18:08
> https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK
> 
> OK, we decided to make an unofficial cardboard unity sdk, and I was given permission to make it public so that we can get more help from you.
> 
> On behalf of my company, may I present, work in progress Cardboard VR Unity SDK.
> 
> I'm still fighting against the cardboard initializing on iOS.

Good Luck!

**Comment by googelybear** [comment] 2020-04-08 16:31
@jballoffet any update when we can expect the new version that works on iOS?

**Comment by cdytoby** [comment] 2020-04-15 15:28
To all of you who is watching this:

We made some progress on unofficial cardboard unity sdk.

![test](https://user-images.githubusercontent.com/15671368/79355629-35785580-7f3e-11ea-9bf7-dfddf5fd70e6.gif)

Details are here:  
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/wiki/Current-Development-Status  
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK

**Comment by 78Star** [comment] 2020-04-15 20:16
Okay everyone knows about it now. Can we stop spamming this thread again.

**Comment by x0rzkov** [comment] 2020-04-29 12:43
any updates about the official SDK ?

**Comment by rickknowles-cognitant** [comment] 2020-05-04 08:18
@jballoffet patience is one thing, but come on ... we're talking about months with no updates at all here, and Apple having now locked down submissions to the app store (I've already started getting "Invalid Binary rejected" messages in test flight). 

We need *something* if only to convince us this isn't another platitude from google in the hope that people who use Cardboard will just disappear.

**Comment by Bubu-Shawn** [comment] 2020-05-05 14:51
> To all of you who are watching this:
> 
> We made some progress on unofficial cardboard unity sdk.
> 
> ![test](https://user-images.githubusercontent.com/15671368/79355629-35785580-7f3e-11ea-9bf7-dfddf5fd70e6.gif)
> 
> Details are here:
> https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/wiki/Current-Development-Status
> https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK

@cdytoby thanks for sharing. By the way, is the gaze navigator work already? I guessed it still work in progress?

**Comment by cdytoby** [comment] 2020-05-05 15:15
> 
> @cdytoby thanks for sharing this. By the way, is the gaze navigator work already? I guessed it still work in progress?

@Bubu-Shawn The plugin is still work in progress, and we're planning to have a beta release by the end of this week, will be available for iOS only. About natigator, I'm actually not planning this because I believe each team should have its own navigation system or control system. What we provide there is just a stereo view, and you can build any kind of navigation system or interaction system on your own.

You can also use the google interaction system from old plugin, if it doesn't contain any native codes.

**Comment by chaosemer** [comment] 2020-05-05 19:53
Our Unity SDK is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the initial version in the coming week.

Thank you for your excitement and your continued patience.

**Comment by linojon** [comment] 2020-05-05 20:06
Would be awesome if someone were working gone a companion project for 3DOF Bluetooth controller that works with Legacy Input arm model and XR Interaction Toolkit?

**Comment by GabrielR** [comment] 2020-05-05 20:44
@chaosemer Thank you for the update, Jared.  It's massively helpful to know Google is still planning to release the Open Source Unity sdk.  We were looking at some difficult business decisions to keep supporting our Cardboard based apps.  

Question:  Does the new SDK support Single Pass rendering?  That has been our biggest performance issue with Cardboard.

**Comment by chaosemer** [comment] 2020-05-05 21:14
The Unity SDK when initially released will use multi-pass rendering with OpenGL ES 2.0 to provide support to the most devices. Adding support for OpenGL ES 3.0 (on Android) and Metal (on iOS) is on our roadmap and would enable single-pass rendering support.

**Comment by perceval1190** [comment] 2020-05-06 08:29
Is the unity xr plugin will incluse the seetrough mode for non daydream phone ?

**Comment by synthercat** [comment] 2020-05-06 08:53
> 
> 
> Is the unity xr plugin will incluse the seetrough mode for non daydream phone ?

[https://github.com/googlevr/cardboard/issues](https://github.com/googlevr/cardboard/issues/23)

PLEASE refrain for chatting on this thread! We are all jumping up and down on our seats ready to stress test this as fast as it comes out. Use the Issues page to see any relevant threads, refrain from asking if it will feature the "X" feature that you are interested in as you will find out in about a week while testing this baby your self. The devs can't implement anything new in the last pre-release days anyway. Thank you for understanding.

**Comment by leoncvlt** [comment] 2020-05-12 15:27
Any news about this? I have an older VR Cardboard Unity App that I need to update, but the App Store doesn't allow me to upload the new version because the older Goggle VR implementation in Unity doesn't use UIWebView. https://developer.apple.com/documentation/uikit/uiwebview

**Comment by rickknowles-cognitant** [comment] 2020-05-12 17:20
> Our Unity SDK is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the initial version in the coming week.

@chaosemer So does the lack of an announcement this week mean things didn't go as planned? Can you at least announce that the release will pass the app store approval process by removing the reference to UIWebView that so many people in the people are agonizingly waiting on?

**Comment by rickknowles-cognitant** [comment] 2020-05-12 17:24
... and for the love of whichever god you believe in, please don't describe fixing this error in the release notes as a "Feature" the way the Firebase team did.

![firebase announcements](https://user-images.githubusercontent.com/37247203/81725403-afd4c080-947d-11ea-9711-ec6a2591fee1.png)

**Comment by chaosemer** [comment] 2020-05-12 20:50
I just checked, there is no reference to `UIWebView` in the upcoming release.

**Comment by rickknowles-cognitant** [comment] 2020-05-17 18:00
@jballoffet @chaosemer 

Come on you guys ... this is getting kind of stupid. We all need this NOW. If you can't finish it (which clearly seems to be the case) RELEASE IT NOW so people who can help, need it now and are very motivated can help you and in doing so help us all.

You might think that it's inappropriate as Google to release something that doesn't meet the quality standards we've come to expect from you. I applaud that as a motive - it's honorable, and we should all aim for that under other circumstances.

BUT not releasing it when you're so close and leaving a whole army of devs who want to help you sit around bleeding cash and professional opportunities because you're under-resourced is NOT OK.

This is kind of the point of open source, isn't it? "Many hands make light work" and all that? 

If you're open-sourcing this for valid reasons, you'll not be bothered by the idea of releasing something with a documented list of known bugs, and then if you wanted to, even following up with a commit that fixed them! Imagine that! Or maybe someone else might, and save you the trouble?

I don't really care for Eric Raymond's views on things most of the time, but his essay "The Cathedral and the Bazaar" describes the way FOSS should work rather well, and leaving us all sitting around in various forms of technical and/or commercial pain while you wait for testing to complete is the antithesis of that.

Please please please .... quit stalling and release this, even if it's broken.

**Comment by chaosemer** [comment] 2020-05-18 20:29
We are happy to announce that we have release v1.1 which includes the [Google Cardboard XR plugin for Unity](/googlevr/cardboard-xr-plugin). The quickstart should be up soon at https://developers.google.com/cardboard/develop/unity/quickstart.

**Closed by chaosemer** 2020-05-18 20:29 UTC
Labels: feature request, question

**Comment by rickknowles-cognitant** [comment] 2020-05-18 21:02
Thank you - sorry for the tough love, but we were all hurting out here waiting for it. Will dive in immediately

**Comment by SRochem** [comment] 2020-05-24 22:33
Hello, 
Sorry I don't understand something. 
I followed the quickstart and everything went well but when I start to launch the "HelloCardBoard" in editor I get :

**Comment by mjjohns** [comment] 2020-05-31 15:54
I am having the same issue as SRochem - I followed the steps fromvided by Google, I get the same DllNotFound error when I hit play in Unity. I built to Android phone and iPad to test and both resulted with an unresponsive black screen with the cardboard overlay. Tested in Unity 2019.3.

**Comment by linojon** [comment] 2020-05-31 16:23
> I am having the same issue as SRochem - I followed the steps fromvided by Google, I get the same DllNotFound error when I hit play in Unity. I built to Android phone and iPad to test and both resulted with an unresponsive black screen with the cardboard overlay. Tested in Unity 2019.3 and 2020.

The workaround that works for me is https://github.com/googlevr/cardboard/issues/35#issuecomment-632656395

**Comment by genvangus** [comment] 2020-07-07 19:39
We made a port of the Cardboard SDK in C # for use in Unity Engine. It does not depend on third-party libraries, including the Google SDK. This asset doesn't use deprecated UIWebView, which helps you publish your apps in AppStore without restrictions https://assetstore.unity.com/packages/tools/camera/cardboard-net-168945

**Comment by z-a-p-k-i-n-g** [comment] 2020-07-17 07:29
> I am having the same issue as SRochem - I followed the steps fromvided by Google, I get the same DllNotFound error when I hit play in Unity. I built to Android phone and iPad to test and both resulted with an unresponsive black screen with the cardboard overlay. Tested in Unity 2019.3 and 2020.

For me it is working well, after building and running it on my phone. But I get same errors as yours when trying to play on editor.
Any fixes on this problem??
Thanks in advance

**Comment by chaosemer** [comment] 2020-07-18 21:40
Please star Issue #51 to track editor play mode support. Supporting editor play mode is very low on our priority list as there are other VR systems compatible with Unity's XR subsystems that work on PC and Mac.

**Comment by rabi92** [comment] 2020-07-27 07:49
How about the metal support @chaosemer ? as the quickstart guide tells us to use OpenGles2 only, which is now deprecated. i am afraid the app will not work in iOS 14 or will be rejected by the appstore ?

**Comment by chaosemer** [comment] 2020-07-27 20:00
Metal support is tracked in Issue #11. Please follow that to keep up to date on Metal support. To our knowledge, OpenGLES 2.0 will continue to run on iOS 14. There's no OpenGL APIs removed according to Apple's official API docs.
