### ISSUE TITLE
Unity render issue. Half of the screen is black out, the rest of the view were all in the other half

### ISSUE THREAD

**Issue by gooddereklu** [googlevr/cardboard#293] opened 2021-08-18 09:02 UTC
long story short 

here's my phone screenshot : 

https://upload.cc/i1/2021/08/18/uyA8za.jpg

and here's my working background

Hardware
 -MacOS 11.4(BigSur)
 -Android (9.0)
Software
 -Unity 2019.4.25
     GraphicsAPI : OPENGLES3
     XR-Plug-in Management : Only Cardboard XR Plugin selected

I've already try the solution #168 provided but it didn't work, any suggestion ？

**Comment by Layfully** [comment] 2021-08-18 11:44
Plugin version?

**Comment by TngBlt** [comment] 2021-08-28 09:34
I have a similar problem with almost same setup. I have android 10, Unity 2019.4.22 and plugin version 1.5. 

I have a problem of black screen with the version 1.5 of the plugin. No crash, I have a video playing and can still hear the sound. 

I have use the same code as the sample, only have the Cardboard XR plugin selected. It seems like it is not starting for whatever reason..

I tried with Unity 2020.2.5 and the plugin v1.7, and the apk crash. 

I used to have a working version on the Play store, published in July and the Cardboard VR view is now crashing the application.

**Comment by jballoffet** [comment] 2021-08-30 19:21
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of #285. Please feel free to leave comments on that issue if needed. Furthermore, please try to reproduce the issue using the latest version (1.7.0) and in case you're able to do it, please send a repro project and the steps required to reproduce the issue. Thanks!

**Closed by jballoffet** 2021-08-30 19:21 UTC
