### ISSUE TITLE
[iPhone 16 pro] Not rendering in full view

### ISSUE THREAD

**Issue by ocularbioengarhku** [googlevr/cardboard#478] opened 2024-10-29 12:44 UTC
### SPECIFIC ISSUE ENCOUNTERED
The render view is not full size in iPhone 16 pro. 

With reference to the previous bug reports, it happen every time when iPhone release a new model every year. 

1. May I know will it be fixed in next round of release and the possible release date?
2. Does [this solution](https://github.com/googlevr/cardboard/issues/144#issuecomment-718041213) still work? In case I can't wait until next release date.

As a frequent user where my app is published on both Apple Store and Google Play, with monthly 200+ participants using the app in different events, this plugin is truly a great tool while knowing mobile version VR is not common nowadays. Your continue support is appreciated and hopefully your team will keep to update in the future!! Thank you very much:)

### SMARTPHONE (please complete the following information):
- Device: iPhone 16 pro (ios: 18.0)
- OS
  - [ ] Android
  - [x] iOS

### EXPECTED BEHAVIOR
Expected the rendering is in full screen

### VERSIONS USED
Cardboard XR Plugin 1.24.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Unity 2021.3.34f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [x] OpenGL ES3
   - [x] Metal

### SCREENSHOTS
![WhatsApp Image 2024-10-29 at 1 24 54 PM](https://github.com/user-attachments/assets/5b92b7d2-32a1-4da0-a0f4-17c836e21358)

**Comment by lneumarkt** [comment] 2024-10-31 17:57
Thank you @ocularbioengarhku for reaching out to us!

The screen parameters for the new iOS devices have been internally submitted and will be included in v1.27.0.

In case you need them in the short time, please follow [Instructions to add the screen params of new iOS devices to the Cardboard SDK](https://developers.google.com/cardboard/develop/ios/screen-params).

I'm closing this issue as it is a duplicate of [#428](https://github.com/googlevr/cardboard/issues/428). Please feel free to leave comments on that issue if needed.

Thank you!

**Closed by lneumarkt** 2024-10-31 17:57 UTC
Labels: bug

**Comment by prakyath-07** [comment] 2024-11-15 07:05
this pull request worked for me 
https://github.com/googlevr/cardboard/pull/480
