### ISSUE TITLE
No Unreal Engine plugin ?

### ISSUE THREAD

**Issue by kinectsources** [googlevr/cardboard#359] opened 2022-07-05 14:04 UTC
This is totally ridiculous not having UE support. Even though it has unity support with regular builds.

**Comment by kafumanto** [comment] 2022-07-05 14:43
Hi, I don't share any link because it could be inappropriate, but we developed a plugin for Unreal Engine 4/5 integrating this SDK. You can find it searching for "Cardboard" in the Unreal Engine Marketplace. Just to avoid any misunderstanding, it's a paid plugin.

**Comment by arilow** [comment] 2022-07-08 18:15
Thanks @kinectsources for reaching out to us! Unfortunately, there are currently no plans to support Unreal Engine. However, adding support for it may be considered in a future update. In case you would like to implement it yourself, please feel free to read CONTRIBUTING.md and follow the process to send a PR. 


 I'm closing this issue as it is a duplicate of #76. Please feel free to leave comments on that issue if needed.


Thanks!

**Closed by arilow** 2022-07-08 18:15 UTC
Labels: duplicate
