### ISSUE TITLE
Feeling without depth of field

### ISSUE THREAD

**Issue by abao0616** [googlevr/cardboard#188] opened 2020-12-31 19:48 UTC
Use old XRSetting , I can see the different between two eyes, and  I feel the depth of field.
![XRSetting](https://user-images.githubusercontent.com/74150462/103421256-4b19d200-4bd6-11eb-8546-227ddb720125.jpg)

But use new XR Plug-in , the rendering of the left and right eyes is the same , and I feel without depth of field.
![XR Plugin 1 4 1](https://user-images.githubusercontent.com/74150462/103421149-e494b400-4bd5-11eb-90d5-d3d8a81dd96a.jpg)

I try to build Android sample code (Native) , it work ( I feel the depth of field) , but not in Unity to build for Android. How can I do ?

Unity 2019.4.14f1 , cardboard xr plug-in v1.4.1

**Comment by jballoffet** [comment] 2021-01-05 11:52
Closing this issue as it is a duplicate of #128.

**Closed** 2021-01-05 11:52 UTC
Labels: duplicate
