### ISSUE TITLE
UImask not working in version 1.30 (cannot see enabling stencil buffer)

### ISSUE THREAD

**Issue by richard12121212** [googlevr/cardboard#162] opened 2020-11-17 22:04 UTC
Hi all,

The UImasks are not working in our project for the new XR plugin version 1.30. (they do not mask things, but the whole picture is being showed.)  Just like in https://stackoverflow.com/questions/41426351/unity-ui-mask-not-working-on-google-pixel-device

In the new XR version we cannot find the 24-bit depth | 8-bit stencil setting anymore which we did enable in previous versions. (are we overlooking a setting somewhere?) We also enabled the Rectmask2d which do not work.

Any ideas? (thanks in advance)

**Comment by jballoffet** [comment] 2020-11-20 22:21
In order to allow us to reproduce this issue, could you please provide a link to a simple Unity project where this issue is shown? Please also provide:
- The required steps to expose the issue.
- The version of Unity being used.
- The phone being used.
- The viewer’s parameters being used.

**Comment by richard12121212** [comment] 2020-11-21 01:39
Hereby:

**link to a simple Unity project where this issue is shown?**
shorturl.at/jnG38 


**The required steps to expose the issue.**
Install Package GooogleVR 1.30 through package manager and GIT url
Enable Cardboard at XR settings
Enable start XR at init

Create scene with:
1. Create ui Canvas
2. Add Image component to canvas 
3. Add sourceimage to Image a .png with transparance.(for example a circle_
4. Add Mask to Image 
5. (add rectMask2d to Image) optional
6. Add Rawimage as child to Image.
7. Add photo.jpg as Texture to RawImage
See working mask in editor
![Editor](https://user-images.githubusercontent.com/74576463/99864129-faa86100-2ba1-11eb-88f0-d5e6ba08a1b9.png)

Build app and deploy to Android Phone. 
App starts, and masking does not work- 
![Screenshot_20201121-022146](https://user-images.githubusercontent.com/74576463/99864133-01cf6f00-2ba2-11eb-887e-44b0fcc87e96.jpg)

  

**The version of Unity being used.**
unity 2020.1.13.1f

 **The phone being used.**
Oneplus 6

**Comment by JoaoBorks** [comment] 2020-11-24 14:37
@richard12121212 what type of canvas are you using? **World Space**, **Screen Space Camera** or **Screen Space Overlay**?

**Comment by richard12121212** [comment] 2020-11-24 14:40
We use WORLD SPACE canvases.

**Comment by JoaoBorks** [comment] 2020-11-24 15:14
@richard12121212 do you have MSAA enabled on the Camera? If so, please disable it and try again.

**Comment by richard12121212** [comment] 2020-11-24 15:52
@JoaoBorks Turning of MSAA does not have any effect:(

**Comment by richard12121212** [comment] 2020-11-26 23:00
> 
> 
> @JoaoBorks Turning of MSAA does not have any effect:(

Hi, thanks for helping, do might have any other ideas?

**Comment by richard12121212** [comment] 2020-11-29 11:07
@chaosemer Do you have any ideas to turn on the stencil buffer? or other solutions? Sorry for asking, but it is really a blocker for us.

**Comment by richard12121212** [comment] 2020-12-05 23:21
I had a little hope the just released version 1.4 had an solution. But problem still exist. Tried many things. Hope there are any ideas.

**Comment by wei292224644** [comment] 2020-12-07 05:45
I have the same problem, I don't know how to solve it.

**Comment by richard12121212** [comment] 2020-12-19 13:24
@jballoffet 

> 
> 
> In order to allow us to reproduce this issue, could you please provide a link to a simple Unity project where this issue is shown? Please also provide:
> 
>     * The required steps to expose the issue.
> 
>     * The version of Unity being used.
> 
>     * The phone being used.
> 
>     * The viewer’s parameters being used.

Hi @jballoffet, I provided the info above. Do you need any more? Can you give us a little update/expectation management? is it being researched?

**Comment by rajanaveen** [comment] 2020-12-24 16:28
Im waiting for the same to get fixed. Hope they sort this out.

**Comment by jballoffet** [comment] 2021-01-29 21:56
@richard12121212, sorry for the long delay here. Thanks for all the provided details, nevertheless, I cannot download the project from the provided link (shorturl.at/jnG38), would you be so kind as to share a new link to download it? Thanks!

**Comment by richard12121212** [comment] 2021-01-31 12:22
https://tinyurl.com/y4gv4vdy

**Comment by iamtheonly** [comment] 2021-04-09 18:12
Hello, any update here @jballoffet ?

**Comment by kukuhbr** [comment] 2021-04-14 08:32
Hi, I'm also having this problem, tried with MSAA off, MaskRect2D, and/or Mask.

**Comment by jballoffet** [comment] 2021-04-29 12:49
Sorry for the long delay here. I confirm I can reproduce the reported issue with the provided project. A ticket for debugging and fixing this issue has been added to our backlog and will be prioritized along with other issues. We haven't been able to prioritize this issue before since we focus on the Metal integration. We'll update this issue once we have some updates about it. In case you'd like to propose the required changes, please feel free to do so. Patches are welcome.

**Comment by 3493000** [comment] 2021-08-02 11:38
Hello, any update here @jballoffet ？

**Comment by jballoffet** [comment] 2021-08-09 15:35
@3493000, unfortunately, we haven't been able to prioritize this issue yet. I'll update this issue once we have some updates about it. Thanks!

**Comment by 3493000** [comment] 2022-08-26 09:26
using UnityEngine;

public class Test : MonoBehaviour
{
    `private` void OnRenderImage(RenderTexture source, RenderTexture destination)
    {
        Graphics.Blit(source,destination);
    }
}

**Comment by arilow** [comment] 2023-01-19 13:59
@matheusIMVR thanks for reaching out to us. I confirm this issue is still reproducible in Unity 2022.1, but unfortunately, we haven't been able to prioritize it yet. Sorry for the long delay here, I'll come back to this ticket once we have some updates about it. 

Thanks!

**Comment by arilow** [comment] 2023-04-20 17:46
A fix for this issue has been submitted and it will be included in v1.21.0. Thanks for reaching out!

**Comment by matheusamazonas** [comment] 2023-04-21 06:59
Awesome. Thank you very much!

**Comment by xinyunh0929** [comment] 2023-05-23 21:18
This was fixed in v1.21.0

**Closed by xinyunh0929** 2023-05-23 21:18 UTC
Labels: bug, fixed in upcoming release
