### ISSUE TITLE
getting error message: Building for iOS Simulator, but the linked library 'GfxPluginCardboard.a' was built for iOS

### ISSUE THREAD

**Issue by comsyspro** [googlevr/cardboard#351] opened 2022-05-07 09:43 UTC
I get following error message when starting an unity app in the iOS simulator (build failed message):
`/Users/username/demo/build1/Unity-iPhone.xcodeproj Building for iOS Simulator, but the linked library 'GfxPluginCardboard.a' was built for iOS`

-should it be possible to run unity app in iOS simulator?
-can the GfxPluginCardboard.a be compiled for iOS simulator, if yes how to do it?

Unity version: 2021.3.1f1
macOS: 11.6.5
Xcode: 13.2.1
google cardboard XR plugin for unity: 1.15.0

**Comment by arilow** [comment] 2022-05-11 12:22
Thanks for reaching out to us @comsyspro! In order to be able to use the iOS Simulator you will need to recompile the prebuilt binary for the needed architecture. 


You can rebuild the prebuilt binary with the SDK Xcode project, by selecting the configuration that best suits your needs. Once the SDK has been rebuilt, you'll need to update the binary file (GfxPluginCardboard.a) in the Cardboard XR Plugin. You'll find instructions to do so [here](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/iOS/generate_gfx_plugin_cardboard_a.md).


 I'm closing this issue as it is a duplicate of #294.


Thanks!

**Closed by arilow** 2022-05-11 12:22 UTC
Labels: duplicate

**Comment by Moncader** [comment] 2022-05-17 01:38
@arilow 
In modern iOS development you should not have to rebuild a library to make things work on device/simulator.
This should be supported using a Universal Framework which is the standard method of providing iOS frameworks to users.

**Comment by comsyspro** [comment] 2022-05-17 04:22
I could get rid of the error now. Before I cloned the git repo from here and used the package in Unity. With that I got this error message. But later when I used the "add git repo" button inside Unity the error message has gone. (I don't know why this happened). Another issue that persists is that I can't simulate the Unity project with iOS simulator and I do need a real Iphone. And I don't know why the iOS simulator is not working.
