### ISSUE TITLE
Not working with AR Foundation Unity3D.

### ISSUE THREAD

**Issue by ti-hardikshah** [googlevr/cardboard#313] opened 2021-11-25 10:18 UTC
### SPECIFIC ISSUE ENCOUNTERED
I am trying to run a project with 2 scenes one is AR (AR Foundation) and the second is VR (cardboard) but the VR scene not working. 
XR, not initialize error. 

- Device: [Any device]
- OS
  - [X] Android
  - [x] iOS

### STEPS TO REPRODUCE THE ISSUE
1. install AR Foundation
2. install Cardboard XR plugin
3. create AR Foundation scene plane tracking
4. create a Cardboard VR Scene sample that will work
5. Try to run in device (getting black screen only)

### EXPECTED BEHAVIOR
AR and Vr both scene work perfectly in different scene

### VERSIONS USED
**What version of Google Cardboard are you using?**
Latest from github

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Unity 2020 , 2019  i had try in all version 

- Select in which graphics API you can reproduce the bug.
   - [X] OpenGL ES2
   - [ ] OpenGL ES3
   - [ ] Metal

**Comment by plavist** [comment] 2021-12-16 03:54
you have enabled ARCore?

**Comment by ti-hardikshah** [comment] 2021-12-17 07:08
Yes definatly !! but XR Carboard plugin not working with AR Foundation. 
Even on Android or iOS

**Comment by irojdest** [comment] 2022-02-03 19:42
Ti, have you solved this issue. Struggling with the same, Cardboard does not build, Gradle issues

**Comment by ti-hardikshah** [comment] 2022-02-04 11:20
Nop, at the end, I have to figure out another way, create a fake illusion using 2 cameras for VR. !!

**Comment by Warwlock** [comment] 2022-02-04 15:12
You can use that script for changing between XR Plugins:
[XRSwitcher.cs](https://github.com/Warwlock/additionalThings/blob/main/XRSwitcher.cs)

**Comment by Warwlock** [comment] 2022-02-04 15:14
And I wanted to make both ArCore and Cardboard work together to make positional change but both of them not working together. The first working plugin suppresses the other ones unfortunately.

**Comment by GeneralKodenobi** [comment] 2022-02-18 20:42
I'm facing the same issue but have found some success but am havning issues still. So i have boith AR Core and Cardboard Api's Selected, none set to start. 

I use the following code to set up the loaders 
`
private IEnumerator StartXR()
    {

        Screen.sleepTimeout = SleepTimeout.NeverSleep;
        Debug.Log("Initializing XR...");
        yield return XRGeneralSettings.Instance.Manager.InitializeLoader();
        if (m_ARLoader == null || m_VRLoader == null)
        {
            foreach (var loader in XRGeneralSettings.Instance.Manager.activeLoaders)
            {
                if (loader is ARCoreLoader)
                {
                    m_ARLoader = loader;
                }
                else if (loader is Google.XR.Cardboard.XRLoader)
                {
                    m_VRLoader = loader;
                }
            }
        }

        if (!HasARLoader || !HasVRLoader)
        {
            Debug.LogError($"Loaders are missing from the list!{(!HasVRLoader ? "\n\tVR Loader Missing" : "")}{(!HasARLoader ? "\n\tAR Loader Missing." : "")}");
            enabled = false;
        }
        if (XRGeneralSettings.Instance.Manager.activeLoader == null)
        {
            Debug.LogError("Initializing XR Failed.");
        }
        else
        {
            Debug.Log("XR initialized.");

         Debug.Log("switching to VR Attempt" +SwitchToVR());
            Debug.Log("Starting XR...");
              XRGeneralSettings.Instance.Manager.StartSubsystems();
           
            Debug.Log("XR started.");
        }
            Api.ReloadDeviceParams();
        if (Api.HasNewDeviceParams())
        {
            Api.ReloadDeviceParams();
        }
        if(SceneManager.GetActiveScene().buildIndex!=1)
        SceneManager.LoadScene(1);// scene with Cardboard        
    }`

So the loaders all claim succes. however my scene is in 2d mode. NOW the the interesting thing is that when I leave the app and come back the VR mode is on. Any clues what could be the source here ?

**Comment by arilow** [comment] 2022-04-22 14:36
Thanks for reaching out to us! And sorry for the  long delay. I'm closing this issue as it is a duplicate of #291. Please feel free to leave comments on that issue if needed.


Also, thanks for your contribution @GeneralKodenobi. In case you find a suitable way of using ARCore along with Cardboard, please feel free to read CONTRIBUTING.md and follow the process to send a PR. Thanks!

**Closed by arilow** 2022-04-22 14:36 UTC
Labels: bug, duplicate

**Comment by tomsuperman** [comment] 2022-09-17 14:53
I did try https://github.com/Aryzon/cardboard-xr-plugin with v1.17, just use SixDoFCardboardStartup.cs in the Sample Scripts folder at the game start. You should able combine AR and VR.

**Comment by pdnellius** [comment] 2023-01-18 01:42
@tomsuperman any idea how you would enable AR passthrough using the Aryzon implementation?
