### ISSUE TITLE
Unity Metal rendering same image for both eyes resulting in terrible image. Quick fix.

### ISSUE THREAD

**Issue by maartenslaa** [googlevr/cardboard#259] opened 2021-05-07 06:55 UTC
Unity Metal rendering same image for both eyes
-

It took me a while to figure this one out, at first it looks like the images are too far apart, however adjusting the eye camera poses did not change anything. Overlaying the images made me see what's wrong: both images for the left and right eye are the same. This results in a terrible image especially on larger devices the user is not able to focus because the images are too far apart.

The cause of this lies in MetalRenderer.mm where a single MTLTexture and a single IOSurfaceRef is used for both eyes. Unless you plan on converting to Single Pass rendering (which I would applaud) I would suggest changing the SDK to use two render textures as in the (quick and a bit dirty) fix below.

The Fix
-
Look at the [MetalRenderer.mm here](https://github.com/Aryzon/cardboard/blob/4c32aaf703ed19d48e75b465e0d8644a6d5e7493/sdk/unity/xr_unity_plugin/metal_renderer.mm) in our 6dof Aryzon MR branch

Or look at the specific commit here: 4c32aaf703ed19d48e75b465e0d8644a6d5e7493 to see the changes.

<br/>
Note: I also stripped out the black texture rendering. I solved that by changing the cardboard-xr-plugin to render full screen instead of just the safe area.

**Comment by jballoffet** [comment] 2021-05-10 11:32
Thanks @maartenslaa for reaching out to us! I confirm I'm able to reproduce the reported issue. Is there a chance that you can send a PR with the proposed changes/fix? In that way, due to the CLA check, we'd be able to review them and given the severity of the issue start migrating them internally as soon as possible. Thanks!

**Comment by xiesi88** [comment] 2021-05-12 18:28
Found the same problem and hope to migrate as soon as possible.Thanks!

**Comment by Git327017278** [comment] 2021-05-13 03:58
I hope as soon as possible.

**Comment by jballoffet** [comment] 2021-05-31 11:37
A fix for this has been submitted and it will be included in v1.6.0. Thanks for reaching out!

**Comment by tallestorange** [comment] 2021-06-06 04:03
I tested https://github.com/googlevr/cardboard/commit/4c32aaf703ed19d48e75b465e0d8644a6d5e7493 and found some bugs.

## https://github.com/googlevr/cardboard/commit/4c32aaf703ed19d48e75b465e0d8644a6d5e7493 Result
![IMG_5524](https://user-images.githubusercontent.com/13891795/120911960-4b0e8880-c6c6-11eb-8e67-184374e97667.PNG)

## Expected Result(https://github.com/tallestorange/cardboard/commit/e99241727e0c398178abe65c7d07129d46a48d3b)
![IMG_5522](https://user-images.githubusercontent.com/13891795/120911942-1d294400-c6c6-11eb-919a-58663ebeebd2.PNG)

## The fix

I added black_texture on https://github.com/googlevr/cardboard/commit/4c32aaf703ed19d48e75b465e0d8644a6d5e7493 .

https://github.com/tallestorange/cardboard/commit/e99241727e0c398178abe65c7d07129d46a48d3b

**Comment by xinyunh0929** [comment] 2021-06-08 21:04
This was fixed in v1.6.0.

**Closed by xinyunh0929** 2021-06-08 21:04 UTC
Labels: bug, fixed in upcoming release
