### ISSUE TITLE
Abnormal darken color in VR mode on iPhone, Unity 2021.3+

### ISSUE THREAD

**Issue by ocularbioengarhku** [googlevr/cardboard#453] opened 2024-02-01 11:10 UTC
### SPECIFIC ISSUE ENCOUNTERED
I tried to open the VrMode scene in Unity 2023.1.20 and 2021.3.34f1, the display is darken in VR mode on iPhone. But when click close button and exit VR mode, the color resume normal. 

### SMARTPHONE (please complete the following information):
- Device: iPhone 13 mini (OS: 16.5)
- OS
  - [ ] Android
  - [x] iOS

### STEPS TO REPRODUCE THE ISSUE
1. Create new project in Unity 2023.1.20 and 2021.3.34f1
2. Import Google Cardboard package
3. Open VrMode scene in sample 
4. Build on iPhone and see error

### EXPECTED BEHAVIOR
It is expect the color is the same as in non-VR mode.

### VERSIONS USED
[Google Cardboard XR Plugin for Unity](https://github.com/googlevr/cardboard-xr-plugin) 1.23.0
Unity 2023.1.20 and 2021.3.34f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ ] OpenGL ES3
   - [x] Metal

### SCREENSHOTS
This is the darken color in VR mode
![IMG_8340](https://github.com/googlevr/cardboard/assets/143391033/5b0ead11-1d6a-4a41-815e-37d87aad93d0)

This should be the normal color
![IMG_8323](https://github.com/googlevr/cardboard/assets/143391033/e0ee6a9d-24e0-415c-a039-8cd1d9885872)

Not only in 3d world, when i display the webcamtexture, the color will be darken too
![IMG_8336](https://github.com/googlevr/cardboard/assets/143391033/37fd2141-efdf-479a-818a-4883ac3ab9b1)

This is the normal camera feed, in non-VR mode
![IMG_8337](https://github.com/googlevr/cardboard/assets/143391033/6dc29e60-7f0e-4fbf-a244-fddc782ae7f8)

**Comment by lneumarkt** [comment] 2024-02-05 12:47
Thanks for reaching out to us! I'm closing this issue as it is a duplicate of [#382](https://github.com/googlevr/cardboard/issues/382).

You are welcome to leave your comments and findings on the original issue to help us gather all the information needed to 
solve this bug. 

Thank you!

**Closed** 2024-02-05 14:33 UTC
Labels: bug, duplicate
