### ISSUE TITLE
OnPointerExit has no receiver

### ISSUE THREAD

**Issue by DaReign** [googlevr/cardboard#405] opened 2023-04-30 06:39 UTC
### ISSUE
I haven't any interactive objects in my scene but it seems that retina pointer enters interaction with some objects and give such error
![image](https://user-images.githubusercontent.com/11806754/235339433-bd1fcf51-ed66-4865-b704-123f939e5aaf.png)
Every object and terrain is on default layer.

### DEVICE
Unity 2021.3.16f1
Cardboard 1.20.0

**Comment by arilow** [comment] 2023-05-02 19:02
Thanks @DaReign for reporting this issue. In order to allow us to reproduce it, could you please provide:

- The required steps to expose the issue.
- A simple Unity project where this issue is depicted would also be very helpful.

Thanks!

**Comment by DaReign** [comment] 2023-05-08 18:39
Please look in this repository https://github.com/DaReign/VRBugs on scene Scenes/VRScene. It looks that problem is related with terrain because it pop up when you gaze at hill.

**Comment by arilow** [comment] 2023-05-11 14:37
Thanks @DaReign for your response and for providing a repro project.


I confirm I can reproduce this problem. An internal ticket has been created to track this.


In the meantime, this might be a workaround for your project: please go to VRScene -> PlayerCapsule -> MainCamera -> CardboardReticlePointer and open the script attached to it, replace the update method for this one:

```
​​    private void Update()
    {
        // Casts ray towards camera's forward direction, to detect if a GameObject is being gazed
        // at.
        RaycastHit hit;
        bool isInteractive = false;
        
        if (_gazedAtObject != null) {
            isInteractive = (1 << _gazedAtObject.layer & ReticleInteractionLayerMask) != 0;
        }


        if (Physics.Raycast(transform.position, transform.forward, out hit, _RETICLE_MAX_DISTANCE))
        {
            // GameObject detected in front of the camera.
            if (_gazedAtObject != hit.transform.gameObject)
            {
                if (isInteractive) {
                    _gazedAtObject?.SendMessage("OnPointerExit");
                }
                // New GameObject.
                _gazedAtObject = hit.transform.gameObject;
                isInteractive = (1 << _gazedAtObject.layer & ReticleInteractionLayerMask) != 0;
                if (isInteractive) {
                    _gazedAtObject.SendMessage("OnPointerEnter");
                }
            }


            SetParams(hit.distance, isInteractive);
        }
        else
        {
            // No GameObject detected in front of the camera.
            if (isInteractive) {
                _gazedAtObject?.SendMessage("OnPointerExit");
            }
            _gazedAtObject = null;
            ResetParams();
        }


        // Checks for screen touches.
        if (Google.XR.Cardboard.Api.IsTriggerPressed)
        {
            if (isInteractive) {
                _gazedAtObject?.SendMessage("OnPointerClick");
            }
        }


        UpdateDiameters();
    }
```


Let us know how it goes.


Thanks!

**Comment by DaReign** [comment] 2023-05-15 10:59
It looks that helped. I will let you know if experience any other problems with interactions ;)

**Comment by DaReign** [comment] 2023-05-25 17:50
Well I have new variant of this problem :) Now I see that when Raycast hit tree (which is part of terrain) then error pop up 

![image](https://github.com/googlevr/cardboard/assets/11806754/b065c29e-72ec-49d7-abce-c500cc68f9a2)

**Comment by DaReign** [comment] 2023-05-25 18:26
After some research the this time problem was when interaction was with object which didn't have any layer set :)

**Comment by arilow** [comment] 2023-05-31 17:22
Thanks for the provided information @DaReign! Unfortunately I could not reproduce the issue locally.


On the other hand, with “didn't have any layer set” you mean the object has the default layer? I’m not aware of the possibility of not having any layer set ([Link](https://forum.unity.com/threads/objects-with-no-layers.441954/)).


Could you please share the steps to create an object that would allow us to reproduce the issue?

Thanks!

**Comment by DaReign** [comment] 2023-05-31 17:26
No the object haven't any  layer set. Select box for selecting layer is empty :)

**Comment by DaReign** [comment] 2023-05-31 17:45
And this is last case from link you provided :)

"This might also happen if you import some objects from another project, and they were using layers in that project that don't exist in this one."

**Comment by arilow** [comment] 2023-06-16 14:01
Given the impossibility of reproducing the issue on our side, we will need a repro project where the issue can be depicted to continue debugging.


Thanks!

**Comment by NYH-Dolphin** [comment] 2023-11-10 22:05
I encounter the same problem. It even exists in the `HelloCardboard` Scene. When you try to move the player to view other object rather than those have `ObjectController.cs`, the error happens. 

Developer need to modify the `CardboardReticlePointer.cs` code. The problem happens in the following section:
```c#
private void Update()
    {
        // Casts ray towards camera's forward direction, to detect if a GameObject is being gazed
        // at.
        RaycastHit hit;
        if (Physics.Raycast(transform.position, transform.forward, out hit, _RETICLE_MAX_DISTANCE))
        {
            // GameObject detected in front of the camera.
            if (_gazedAtObject != hit.transform.gameObject)
            {
                _gazedAtObject?.SendMessage("OnPointerExit");
                _gazedAtObject = hit.transform.gameObject;
                _gazedAtObject.SendMessage("OnPointerEnter");
            }

            bool isInteractive = (1 << _gazedAtObject.layer & ReticleInteractionLayerMask) != 0;
            SetParams(hit.distance, isInteractive);
        }
        else
        {
            _gazedAtObject?.SendMessage("OnPointerExit");
            _gazedAtObject = null;
            ResetParams();
        }

        // Checks for screen touches.
        if (Google.XR.Cardboard.Api.IsTriggerPressed)
        {
            _gazedAtObject?.SendMessage("OnPointerClick");
        }

        UpdateDiameters();
    }
```

The reason is because the object which doesn't constains the methods of `OnPointerExit` or `OnPointerEnter` can not successfully trigger the events. Possible is to detect the layer of the object like `Interactive` and require all the objects in this layer should be attached a specific script contains those functions.

Here is a possible modification:
```c#
private void Update()
        {
            // Casts ray towards camera's forward direction, to detect if a GameObject is being gazed
            // at.
            RaycastHit hit;
            if (Physics.Raycast(transform.position, transform.forward, out hit, _RETICLE_MAX_DISTANCE))
            {
                // GameObject detected in front of the camera.
                if (_gazedAtObject != hit.transform.gameObject)
                {
                    if (_gazedAtObject?.layer == LayerMask.NameToLayer("Interactive"))
                    {
                        _gazedAtObject?.SendMessage("OnPointerExit");
                    }

                    _gazedAtObject = hit.transform.gameObject;

                    if (_gazedAtObject?.layer == LayerMask.NameToLayer("Interactive"))
                    {
                        _gazedAtObject.SendMessage("OnPointerEnter");
                    }
                }

                bool isInteractive = (1 << _gazedAtObject.layer & ReticleInteractionLayerMask) != 0;
                SetParams(hit.distance, isInteractive);
            }
            else
            {
                if (_gazedAtObject?.layer == LayerMask.NameToLayer("Interactive"))
                {
                    _gazedAtObject?.SendMessage("OnPointerExit");
                }

                _gazedAtObject = null;
                ResetParams();
            }

            // Checks for screen touches.
            if (Google.XR.Cardboard.Api.IsTriggerPressed)
            {
                if (_gazedAtObject?.layer == LayerMask.NameToLayer("Interactive"))
                {
                    _gazedAtObject?.SendMessage("OnPointerClick");
                }
            }

            UpdateDiameters();
        }
```

**Comment by NYH-Dolphin** [comment] 2023-11-10 22:11
To reproduce the problem
0. My Unity Version `2022.3.11f1`
1. Follow the instruction to install Google Cardboard
2. Enter the `HelloCardboard` Scene
3. Hit `Play`
4. In the `Scene` window, Move the `player` GameObject until the `CardboardReticlePointer` hits the GameObjects other than 
those in `Treasure`
5. You'll notice the error happens in the `Console` window

**Comment by xinyunh0929** [comment] 2023-12-15 17:01
This was fixed in v1.23.0

**Closed by xinyunh0929** 2023-12-15 17:01 UTC
Labels: bug, fixed in upcoming release

**Comment by wbm001** [comment] 2024-01-23 05:34
Im using unity 22.3.14f , this problem reappears...i have 1.23.0

**Comment by wbm001** [comment] 2024-01-23 05:39
Im using unity 22.3.14f , this problem reappears...i have 1.23.0 , i have changed the script to those mentioned @arilow  any ideas?
