### ISSUE TITLE
Serious lag in URP

### ISSUE THREAD

**Issue by Raj2509** [googlevr/cardboard#350] opened 2022-05-06 07:10 UTC
### SPECIFIC ISSUE ENCOUNTERED
There is a very heavy lag when I install universal render pipeline in unity and run the build in my samsung F41. I am getting 8fps. Although build is running fine without URP with legacy render pipeline.

Please help

**Comment by arilow** [comment] 2022-07-25 14:44
Thanks @Raj2509 for reporting this issue! Unfortunately, I couldn’t reproduce the described behavior on my phone (Samsung Galaxy S20 FE).


Could you please try to reproduce this issue on another phone just to be sure that this is not device-specific?


If you are able to reproduce it, I would ask if you could please provide:
- Device model.
- Android version.
- The Cardboard XR Plugin version being used.
- Unity version.
- A simple Unity project where this issue is depicted would also be very helpful.
Thanks!

**Comment by arilow** [comment] 2023-05-08 14:28
Closing this due to our inability to reproduce the issue. Perhaps our releases since the report have fixed this issue.

If this is still happening for you, please reopen this issue and share a repro project along with steps that show the issue.

**Closed by arilow** 2023-05-08 14:28 UTC
Labels: bug
