### ISSUE TITLE
Unity HalloCardboard scene laggy on iOS 

### ISSUE THREAD

**Issue by unitydevelopers-artur** [googlevr/cardboard#276] opened 2021-06-21 12:38 UTC
In General view is very laggy and looks like few frame delays based on the device movement.  

Tested on iPhone 11 with IOS 14.5.
Project created in Unity 2019.4.26
SDK version 1.6.0

Setup done based on the documentation.

**Comment by jballoffet** [comment] 2021-06-25 15:51
Thanks for reaching out to us. I'm closing this issue as it is a duplicate of #173. Please feel free to leave comments on that issue. Thanks!

**Closed by jballoffet** 2021-06-25 15:51 UTC
Labels: bug, duplicate
