### ISSUE TITLE
Weird rendering line on webcamtexture

### ISSUE THREAD

**Issue by ocularbioengarhku** [googlevr/cardboard#461] opened 2024-04-17 10:19 UTC
### SPECIFIC ISSUE ENCOUNTERED
I am applying a [blur shader](http://www.vetasoft.store/camerafilterpack/Effects/Blur_Dithering2x2.html) on the webcamtexture. It blur as expectedly, but there is a extra weird line render on the top and the bottom. The top weird line will render the bottom color pixel, while the bottom weird line will render the top color pixel.

For example, the camera is looking at a rainbow flag.

### EXPECTED BEHAVIOR
When is it not using the blur shader or using the blur shader without in VR mode, it can show the color correctly and there is no weird line.
![Screenshot_20240417-154430](https://github.com/googlevr/cardboard/assets/143391033/8e070d20-b5a4-4778-85de-38b0ceecf298)
![Screenshot_20240417-154423](https://github.com/googlevr/cardboard/assets/143391033/11b4a163-7b33-485e-abd2-a9837a0d7f93)

### SCREENSHOTS
However, when using the blur shader in VR mode, in picture 1, there is a extra yellow line at the bottom. In which, as the top now is showing yellow pixel, so it will render a yellow bottom weird line.
![Screenshot_20240417-154307](https://github.com/googlevr/cardboard/assets/143391033/6ef56580-4138-45af-ac5c-a55e109be96a)

For picture 2, there is a extra blue line at the top. 
![Screenshot_20240417-154257](https://github.com/googlevr/cardboard/assets/143391033/d59e66e7-e6f2-41fb-b3dd-6101cc988d0e)

Sorry for the confusion, it maybe hard to understand by text only. Therefore, with the [attached project file](https://drive.google.com/file/d/160hhIDgt8SWUqHk2M1pB1A_tFWSKytcx/view?usp=sharing),  the [apk file](https://drive.google.com/file/d/1Qspn-PSJ4vhR9RDUB6ZzgDoOPLO72eq2/view?usp=sharing) and the [xcode project](https://drive.google.com/file/d/1I-FzLyHlfAO7GcvTEodxF9tI73CyShVB/view?usp=sharing) hope it can easily understand the problem. Thank you. 

### SMARTPHONE (please complete the following information):
- Device:
UleFone Armor 8 Pro (Android 11)
iPhone 13 mini (iOS 16.5)
- OS
  - [x ] Android
  - [ x] iOS

### VERSIONS USED
[cardboard-xr-plugin v1.24.0](https://github.com/googlevr/cardboard-xr-plugin/releases/tag/v1.24.0)
Unity 2021.3.34f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [x ] OpenGL ES3
   - [x ] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
[attached project file](https://drive.google.com/file/d/160hhIDgt8SWUqHk2M1pB1A_tFWSKytcx/view?usp=sharing)
[apk file](https://drive.google.com/file/d/1Qspn-PSJ4vhR9RDUB6ZzgDoOPLO72eq2/view?usp=sharing)
[xcode project](https://drive.google.com/file/d/1I-FzLyHlfAO7GcvTEodxF9tI73CyShVB/view?usp=sharing)

**Comment by lneumarkt** [comment] 2024-05-22 12:34
Thanks @ocularbioengarhku for reaching out to us!

We were able to observe the reported issue using the provided project.
Notice the red line at the bottom of the following image when using the blur shader.
![rainbow-stereo](https://github.com/googlevr/cardboard/assets/78873247/ac450c6b-ed65-4d4e-a070-eed4a3dde16a)


However, after further testing, we also observed that the rendering issue persists after disabling the **Cardboard XR plugin** from `Player Settings > XR Plug-in Management` on Unity.
![rainbow-mono](https://github.com/googlevr/cardboard/assets/78873247/6c9fcef0-b3d7-4fff-88bf-af9e1fb80ed2)


I’m closing this ticket as it seems that the issue is not related to the Cardboard SDK.

Please feel free to reopen this ticket in case you have any other questions regarding this topic. Thanks!

**Closed by lneumarkt** 2024-05-22 12:34 UTC
Labels: bug
