### ISSUE TITLE
VR view not working in IOS. 

### ISSUE THREAD

**Issue by saurabhburadkar** [googlevr/cardboard#446] opened 2023-12-18 05:09 UTC
### SPECIFIC ISSUE ENCOUNTERED
When I opened the app, my app showed me a normal view. It must open in VR view. On Android, it's working fine, But on IOS shows me only a normal view.

### SMARTPHONE (please complete the following information):
- Device: iphone 7
- OS
  - [ ] iOS
- 15.8

### STEPS TO REPRODUCE THE ISSUE
1. Just build the project with hello card board scene and open app on IOS.

### EXPECTED BEHAVIOR
It must open in VR mode.

### VERSIONS USED
unity version 2021.3.33f1
Google Cardboard XR Plugin for Unity - 1.23.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2021.3.33f1

- Select in which graphics API you can reproduce the bug.
there are no graphics API settings in IOS

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
[e.g. https://github.com/googlevr/cardboard]

### SCREENSHOTS
If applicable, add screenshots to help depict your problem.

### ADDITIONAL CONTEXT
![IMG_EE6BE5A24512-1](https://github.com/googlevr/cardboard/assets/71985034/432e71aa-6790-45d7-b90f-c6ccc2ca4772)

**Comment by lneumarkt** [comment] 2023-12-20 18:23
@saurabhburadkar Thank you for reaching out and reporting the issue you encountered.

I’ve tried to replicate the problem on my end using an iPhone SE with iOS 14.6 and Unity 2021.3.33, but I couldn’t reproduce the bug; it seems to be working fine when using the HelloCardboard sample app from Cardboard XR Plugin v1.23.

Could you please confirm whether the [Cardboard XR Plugin under Plug-in Providers](https://developers.google.com/cardboard/develop/unity/quickstart#xr_plug-in_management_settings_2) was enabled during setup? (see image below):

![PlayerSettings-XR-Plugin-Management](https://github.com/googlevr/cardboard/assets/78873247/cf809d55-4e79-4ffc-b852-0842b9370a46)

If so, we would need you to share with us a simple repro project where this issue is depicted, either via a zip file containing the Unity project or a link to a git repo. It would be of great help so as to be able to reproduce and solve this issue.

Thanks!

**Comment by arilow** [comment] 2024-02-28 22:51
Closing as this seems to be fixed. Feel free to reopen if this is an issue for you.

**Closed by arilow** 2024-02-28 22:51 UTC
Labels: bug
