### ISSUE TITLE
[1.11.0]How fix mismatch ?

### ISSUE THREAD

**Issue by plavist** [googlevr/cardboard#317] opened 2021-12-15 14:27 UTC
How to fix the mismatch of the left and right eyes?

Redmi note 8 pro
![Screenshot_2021-12-14-22-19-49-120_com DefaultCompany GoogleVR](https://user-images.githubusercontent.com/75023511/146204422-0443d686-58ab-4909-950e-4a1c52708dd2.jpg)
o

**Comment by Layfully** [comment] 2021-12-16 09:50
I think it is supposed to be like that. IRL your eyes "render" different things too :)

**Comment by arilow** [comment] 2022-01-24 15:06
As @layfully pointed out, the difference between each eye is intended, it is called [binocular disparity](https://en.wikipedia.org/wiki/Binocular_disparity) and it is caused by the [parallax](https://en.wikipedia.org/wiki/Parallax) between eyes. I've found [this](https://www.quora.com/How-are-we-able-to-see-3D-objects-when-our-retina-is-just-a-2D-screen/answer/Joyce-Schenkein?ch=10&oid=15170752&share=26b2b233&target_type=answer) post that shows how it applies to 3D experiences.

I am closing this issue now given that this is expected behavior. Please feel free to reopen it if this is still an issue for you and provide more details about it. Thanks!

**Closed by arilow** 2022-01-24 15:06 UTC
Labels: question
